"""Both-arm native material landmarks, mixed-joint skin, and physical cap checks."""
import bpy,json,collections,importlib.util,math
import numpy as np
from pathlib import Path
from mathutils import Vector
from gate_config import ROOT,OUTPUT,INPUTS,sha,verify_loaded
spec=importlib.util.spec_from_file_location('measure','/workspace/shared/practical_ads_audit_recovery_algorithms.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)
refs=json.loads((ROOT/'shared_pose_fit/portable_recipe/native_frame_reference.json').read_text())['anatomy'];out={};P='mixamorig:'
def mesh(o):o.data.calc_loop_triangles();return np.array([q.vertices[:] for q in o.data.loop_triangles])
def pos(o):return np.array(m.evaluated_positions(o,bpy.context.evaluated_depsgraph_get()))
for label,path,pin in INPUTS:
 assert sha(path)==pin;bpy.ops.wm.open_mainfile(filepath=str(path));verify_loaded(bpy,label);bpy.context.scene.frame_set(0);bpy.context.view_layer.update();r=bpy.data.objects['SWAT_Mixamo_Rig'];b=bpy.data.objects['SWAT_Wearer'];assert np.allclose(np.array(r.matrix_world),np.eye(4),atol=1e-7),'Native anatomical helper requires identity rig object frame';V=pos(b);T=mesh(b);RV=np.array([b.matrix_world@v.co for v in b.data.vertices]);native=np.array([q.value for q in b.data.attributes['native_vertex_id'].data]);lookup={int(v):i for i,v in enumerate(native)};W=[{b.vertex_groups[q.group].name:q.weight for q in v.groups} for v in b.data.vertices];tags,tw=m.triangle_weight_tags(T,W);C,groups=m.components(T,len(V));NV=[Vector((0,0,0)) for _ in range(int(native.max())+1)]
 for i,j in lookup.items():NV[i]=Vector(V[j])
 pb={x.name:np.array(r.matrix_world@x.matrix) for x in r.pose.bones};rb={x.name:np.array(r.matrix_world@x.matrix_local) for x in r.data.bones};lbs,J=m.normalized_all_influence_lbs(RV,W,pb,rb);normal=m.material_normal_transport(RV,V,T,J);sv=np.linalg.svd(J,compute_uv=False)[:,-1];row={'source':str(path),'sha256':pin,'action':r.animation_data.action.name,'frame':0,'method':'The dorsal relation uses native evaluated forearm-hardware and hand-dorsal skin centroids through compact native_vertex_id mapping, with recorded native offsets. Hinge uses the recorded native arm-frame offset. Wrist/elbow axis angles are supplemental. Mixed-joint skin uses normalized all-influence Jacobians; not a clinical range assessment.','all_body_LBS_max_error_mm':float(np.linalg.norm(lbs-V,axis=1).max()*1000),'sides':{}}
 for side,suffix in [('Left','L'),('Right','R')]:
  reference=refs[side];required=reference['hardware_ids']+reference['hand_dorsal_ids'];assert all(i in lookup for i in required),(side,'native material landmark missing; no substituted marker permitted');a=m.arm_material_frame_anatomy(r,NV,side,refs);a['hardware_marker_count']=len(reference['hardware_ids']);a['dorsal_marker_count']=len(reference['hand_dorsal_ids']);a['evaluated_hardware_centroid_world_m']=np.mean([V[lookup[i]] for i in reference['hardware_ids']],axis=0).tolist();a['evaluated_dorsal_skin_centroid_world_m']=np.mean([V[lookup[i]] for i in reference['hand_dorsal_ids']],axis=0).tolist();a['mixed_joint_skin']={}
  for joint,names in [('shoulder',('Shoulder','Arm')),('elbow',('Arm','ForeArm')),('wrist',('ForeArm','Hand'))]:
   ids=np.array([i for i,w in enumerate(W) if all(w.get(P+side+n,0)>.05 for n in names)]);assert len(ids)>0;(lo,hi)=names;mask=np.isin(T,ids).any(1);ti=np.flatnonzero(mask);a['mixed_joint_skin'][joint]={'vertices':len(ids),'minimum_normalized_skin_J_singular_value':float(sv[ids].min()),'minimum_skin_J_determinant':float(np.linalg.det(J[ids]).min()),'minimum_geometric_vs_transported_normal_alignment':float(normal['normal_alignment'][ti].min()),'negative_face_alignment_count':int(sum(normal['normal_alignment'][ti]<0)),'minimum_face_area_over_rest':float(normal['area_ratio'][ti].min())}
  a['segment_length_errors_mm']={}
  for name,n1,n2 in [('upper','Arm','ForeArm'),('fore','ForeArm','Hand')]:
   current=(r.pose.bones[P+side+n2].head-r.pose.bones[P+side+n1].head).length;rest=(r.data.bones[P+side+n2].head_local-r.data.bones[P+side+n1].head_local).length;a['segment_length_errors_mm'][name]=abs(current-rest)*1000
  armti=np.array([i for i,t in enumerate(tags) if t in [P+side+'Arm',P+side+'ForeArm']]);cap=bpy.data.objects['SWAT_ElbowCap_'+suffix];CV=pos(cap);CT=mesh(cap);hits=m.finite_crossings([Vector(v) for v in CV],list(map(tuple,CT)),list(range(len(CT))),[Vector(v) for v in V],list(map(tuple,T)),list(map(int,armti)));a['elbow_cap_vs_actual_arm_skin']={'exact_triangle_crossing_pairs':len(hits),'witnesses_first20':list(hits.values())[:20],'cap_native_topology':m.topology_edges(CT)}
  row['sides'][side]=a;print('ANATOMY',label,side,'wrist',a['wrist_deg'],'hinge_native_residual',a['hinge_native_residual_deg'],'dorsal_residual',a['dorsal_residual_deg'],'cap_crossings',len(hits),flush=True)
 assert sha(path)==pin;row['sha256_after']=sha(path);out[label]=row;(OUTPUT/'anatomy_material_comparison.json').write_text(json.dumps(out,indent=2)+'\n')
