"""Exact local-channel and native-skin comparison with immutable sealed C."""
import bpy,json,collections,importlib.util,math
import numpy as np
from pathlib import Path
from gate_config import ROOT,OUTPUT,CANDIDATE,CANDIDATE_SHA,SEALED_C,SEALED_C_SHA,sha,verify_loaded
spec=importlib.util.spec_from_file_location('m','/workspace/shared/practical_ads_audit_recovery_algorithms.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m)
allowed_bone='mixamorig:LeftHandIndex1';allowed_path='pose.bones["'+allowed_bone+'"].rotation_quaternion';prefix='mixamorig:LeftHandIndex';reference=None;out={}
def maxabs(a,b):return float(np.max(np.abs(np.asarray(a)-np.asarray(b))))
def curve_signature(fc):
 return {'extrapolation':fc.extrapolation,'keyframes':[{'co':list(k.co),'interpolation':k.interpolation,'easing':k.easing,'handle_left_type':k.handle_left_type,'handle_right_type':k.handle_right_type,'handle_left':list(k.handle_left),'handle_right':list(k.handle_right)} for k in fc.keyframe_points],'modifiers':[mod.type for mod in fc.modifiers]}
for label,path,pin in [('C',SEALED_C,SEALED_C_SHA),('C1',CANDIDATE,CANDIDATE_SHA)]:
 assert sha(path)==pin;bpy.ops.wm.open_mainfile(filepath=str(path));bpy.context.scene.frame_set(0);bpy.context.view_layer.update();r=bpy.data.objects['SWAT_Mixamo_Rig'];action=r.animation_data.action
 if label=='C':assert action.name=='Support Grip / Surface Constrained Candidate C'
 else:verify_loaded(bpy,'C1')
 curves={(f.data_path,int(f.array_index)):curve_signature(f) for f in action.fcurves};basis={b.name:np.array(b.matrix_basis) for b in r.pose.bones};pose={b.name:np.array(r.matrix_world@b.matrix) for b in r.pose.bones};b=bpy.data.objects['SWAT_Wearer'];b.data.calc_loop_triangles();T=np.array([q.vertices[:] for q in b.data.loop_triangles]);N=np.array([q.value for q in b.data.attributes['native_vertex_id'].data]);V=np.array(m.evaluated_positions(b,bpy.context.evaluated_depsgraph_get()));RV=np.array([b.matrix_world@v.co for v in b.data.vertices]);W=[{b.vertex_groups[q.group].name:q.weight for q in v.groups} for v in b.data.vertices];C,groups=m.components(T,len(V));hi=groups[C[int(np.flatnonzero(N==7923)[0])]];native_tris=[set(map(int,N[t])) for t in T];target=next(i for i,t in enumerate(native_tris) if t=={8513,8515,8516});t=T[target];restarea=np.linalg.norm(np.cross(RV[t[1]]-RV[t[0]],RV[t[2]]-RV[t[0]]))/2;posedarea=np.linalg.norm(np.cross(V[t[1]]-V[t[0]],V[t[2]]-V[t[0]]))/2;edges=np.linalg.norm(V[t[[1,2,0]]]-V[t],axis=1);pb={x.name:np.array(r.matrix_world@x.matrix) for x in r.pose.bones};rb={x.name:np.array(r.matrix_world@x.matrix_local) for x in r.data.bones};lbs,J=m.normalized_all_influence_lbs(RV,W,pb,rb);norm=m.material_normal_transport(RV,V,T,J);lookup={int(n):i for i,n in enumerate(N)}
 row={'source':str(path),'sha256':pin,'action':action.name,'frame':0,'target_face':{'native_vertices':N[t].tolist(),'dominant_region':'mixamorig:LeftHandIndex1','rest_area_mm2':float(restarea*1e6),'posed_area_mm2':float(posedarea*1e6),'posed_over_rest_ratio':float(posedarea/restarea),'longest_edge_mm':float(edges.max()*1000),'altitude_to_longest_edge_mm':float(2*posedarea/edges.max()*1000),'normal_transport_alignment':float(norm['normal_alignment'][target]),'posed_vertices_world_m':V[t].tolist()},'native_hand_skin_vertex_count':len(hi)}
 if reference is None:reference={'curves':curves,'basis':basis,'pose':pose,'vertices':{int(N[i]):V[i] for i in hi}}
 else:
  RC=reference['curves'];allkeys=set(curves)|set(RC);changed=[k for k in sorted(allkeys) if curves.get(k)!=RC.get(k)];unexpected=[k for k in changed if k[0]!=allowed_path or k[1] not in range(4)];basis_delta={name:maxabs(mat,reference['basis'][name]) for name,mat in basis.items()};pose_delta={name:maxabs(mat,reference['pose'][name]) for name,mat in pose.items()};skin_delta={int(N[i]):float(np.linalg.norm(V[i]-reference['vertices'][int(N[i])])*1000) for i in hi};unaffected=[i for i in hi if sum(weight for name,weight in W[i].items() if name.startswith(prefix))==0];index_frame_delta=basis[allowed_bone][:3,:3]@np.linalg.inv(reference['basis'][allowed_bone][:3,:3]);from mathutils import Matrix;dq=Matrix(index_frame_delta).to_quaternion();angle=math.degrees(dq.angle);axis=list(dq.axis)
  row['comparison_to_sealed_C']={'changed_action_channels':[{'path':k[0],'index':k[1],'before':RC.get(k),'after':curves.get(k)} for k in changed],'unexpected_changed_channels':[list(k) for k in unexpected],'all_unexpected_channels_exactly_preserved':not unexpected,'changed_basis_bones_nonzero':[{'bone':name,'max_matrix_element_delta':delta} for name,delta in basis_delta.items() if delta>0],'maximum_basis_delta_outside_Index1':max(v for k,v in basis_delta.items() if k!=allowed_bone),'maximum_world_pose_delta_outside_Index_chain':max(v for k,v in pose_delta.items() if not k.startswith(prefix)),'protected_world_pose_deltas':{name:pose_delta[name] for name in ['mixamorig:LeftArm','mixamorig:LeftForeArm','mixamorig:LeftHand','Gear_Elbow_L','Prop_Rifle','mixamorig:RightHand']},'maximum_left_glove_skin_delta_mm':max(skin_delta.values()),'maximum_skin_delta_with_zero_Index_chain_weight_mm':max([skin_delta[int(N[i])] for i in unaffected],default=0),'zero_Index_chain_weight_vertices':len(unaffected),'largest_skin_delta_vertices':[{'native_vertex':i,'delta_mm':v} for i,v in sorted(skin_delta.items(),key=lambda q:q[1],reverse=True)[:12]],'local_Index1_rotation_delta_degrees':angle,'local_Index1_rotation_delta_axis':axis,'note':'Rotational delta is a matrix/quaternion descriptor. Actual face restoration and surface contact decide the result.'}
 assert sha(path)==pin;row['sha256_after']=sha(path);out[label]=row;print('SEALED_C_COMPARISON',label,'face_area_mm2',row['target_face']['posed_area_mm2'],'unexpected_channels',row.get('comparison_to_sealed_C',{}).get('unexpected_changed_channels'),flush=True)
(OUTPUT/'sealed_C_channel_and_skin_comparison.json').write_text(json.dumps(out,indent=2)+'\n')
