#!/usr/bin/env python3
"""Generate compact C NPC/scenario tables from recorded authoritative rooms."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


def f(value: object) -> str:
    rendered = f"{float(value or 0):.8g}"
    if "." not in rendered and "e" not in rendered.lower():
        rendered += ".0"
    return rendered + "f"


def vec(values: list[object] | None) -> str:
    values = values or [0, 0, 0]
    return "{" + ",".join(f(v) for v in values) + "}"


def array(values: list[object]) -> str:
    return "{" + ",".join(f(v) for v in values) + "}"


def build(episodes_path: Path, npc_path: Path, calibration_path: Path, output: Path) -> None:
    episodes = json.loads(episodes_path.read_text(encoding="utf-8"))["episodes"]
    npc_rows = json.loads(npc_path.read_text(encoding="utf-8"))
    npc_by_name = {row["name"]: row for row in npc_rows}
    calibration = json.loads(calibration_path.read_text(encoding="utf-8"))
    observed_names = sorted({
        entity["name"]
        for episode in episodes
        for room in episode["rooms"]
        for entity in room["entities"]
        if entity["role"] == "HostileNpc"
    })
    npc_index = {name: index for index, name in enumerate(observed_names)}

    lines = [
        "// Generated by tools/build_scenario_catalog.py. Do not edit manually.",
        "typedef struct {",
        "    float signature, shield, armor, hull, max_speed, orbit_speed, orbit_range;",
        "    float optimal, falloff, tracking, turret_dps, missile_dps, missile_range;",
        "    float missile_explosion_radius, missile_explosion_velocity, missile_drf;",
        "    float neutralizer, radial_gain, orbit_speed_scale;",
        "    float shield_resist[4], armor_resist[4], hull_resist[4];",
        "    float turret_damage_mix[4], missile_damage_mix[4];",
        "    unsigned char gate_required, suppressor_vulnerable;",
        "} GeneratedNpcDef;",
        "typedef struct { unsigned short npc; float position[3]; } GeneratedSpawn;",
        "typedef struct { unsigned char kind; float position[3]; } GeneratedTower;",
        "typedef struct {",
        "    unsigned char hostile_count, gate_kind, tower_count;",
        "    float cache_position[3], gate_position[3];",
        "    GeneratedSpawn hostiles[3];",
        "    GeneratedTower towers[4];",
        "} GeneratedRoom;",
        "",
        f"#define GENERATED_NPC_COUNT {len(observed_names)}",
        f"#define GENERATED_EPISODE_COUNT {len(episodes)}",
        f"#define GENERATED_ROOM_COUNT {len(episodes) * 3}",
        "static const GeneratedNpcDef GENERATED_NPCS[GENERATED_NPC_COUNT] = {",
    ]
    for name in observed_names:
        row = npc_by_name.get(name)
        if row is None:
            raise ValueError(f"observed NPC missing from catalog: {name}")
        vulnerable = int(name.endswith("lance Tessella"))
        movement = calibration.get(name, {"radial_gain": 0.7, "orbit_speed_scale": 1.0})
        lines.append(
            "    {"
            + ",".join(f(row[key]) for key in (
                "signature_radius_m", "shield_hp", "armor_hp", "structure_hp",
                "max_speed_mps", "orbit_speed_mps", "orbit_range_m", "turret_optimal_m",
                "turret_falloff_m", "turret_tracking", "turret_dps", "missile_dps",
                "missile_range_m", "missile_explosion_radius_m",
                "missile_explosion_velocity_mps", "missile_damage_reduction_factor",
                "neutralizer_gj_per_s",
            ))
            + f",{f(movement['radial_gain'])},{f(movement['orbit_speed_scale'])}"
            + f",{array(row['shield_resists'])},{array(row['armor_resists'])},"
            + f"{array(row['structure_resists'])},{array(row['turret_damage_mix'])},"
            + f"{array(row['missile_damage_mix'])},1,{vulnerable}}},"
            + f" // {name}"
        )
    lines.extend(["};", "", "static const GeneratedRoom GENERATED_ROOMS[GENERATED_ROOM_COUNT] = {"])

    for episode in episodes:
        rooms = {room["room_index"]: room for room in episode["rooms"]}
        for room_index in (1, 2, 3):
            room = rooms[room_index]
            hostiles = [e for e in room["entities"] if e["role"] == "HostileNpc"]
            cache = next(e for e in room["entities"] if e["role"] == "LiveCache")
            gates = [e for e in room["entities"] if e["role"] in {"TransferConduit", "OriginConduit"}]
            if not gates:
                raise ValueError(f"episode {episode['episode_index']} room {room_index}: missing conduit")
            gate = gates[0]
            gate_kind = 2 if gate["role"] == "OriginConduit" else 1
            tower_kinds = {
                "Short-Range Deviant Automata Suppressor": 1,
                "Medium-Range Deviant Automata Suppressor": 2,
                "Short-Range Multibody Tracking Pylon": 3,
                "Medium-Range Multibody Tracking Pylon": 4,
            }
            towers = [
                (tower_kinds[e["name"]], e["position_m"])
                for e in room["entities"]
                if e.get("name") in tower_kinds and e.get("position_m", [None])[0] is not None
            ]
            if len(towers) > 4:
                raise ValueError(f"episode {episode['episode_index']} room {room_index}: more than four towers")
            spawns = [f"{{{npc_index[e['name']]},{vec(e['position_m'])}}}" for e in hostiles]
            spawns.extend(["{0,{0,0,0}}"] * (3 - len(spawns)))
            tower_spawns = [f"{{{kind},{vec(position)}}}" for kind, position in towers]
            tower_spawns.extend(["{0,{0,0,0}}"] * (4 - len(tower_spawns)))
            lines.append(
                f"    {{{len(hostiles)},{gate_kind},{len(towers)},{vec(cache['position_m'])},{vec(gate['position_m'])},"
                + "{" + ",".join(spawns) + "},{" + ",".join(tower_spawns) + "}},"
                + f" // episode {episode['episode_index']} room {room_index}"
            )
    lines.extend(["};", ""])
    output.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--episodes", type=Path, default=Path("ocean/abyss/data/recorded/episodes.json"))
    parser.add_argument("--npcs", type=Path, default=Path("ocean/abyss/data/npc_catalog.json"))
    parser.add_argument("--calibration", type=Path, default=Path("ocean/abyss/data/trajectory_calibration.json"))
    parser.add_argument("--output", type=Path, default=Path("ocean/abyss/generated_scenarios.h"))
    args = parser.parse_args()
    build(args.episodes, args.npcs, args.calibration, args.output)
    print(f"wrote {args.output}")


if __name__ == "__main__":
    main()
