#!/usr/bin/env python3
"""Fetch the QSNA / abyssal.space historical Abyss spawn statistics.

Downloads two snapshots from qsna.eu (the frontend for abyssal.space
player-submitted run data):

- spawn_stats_qsna.json: per-tier spawn tables. For every tier and spawn type
  it records the observed room sample size, min/max/average enemies per room,
  and per-NPC-type occurrence chance and count range.
- npc_types_qsna.json: the NPC catalog with dogma attributes for every
  Abyss-relevant NPC type (groups 1982 and 1997).

The spawn tables are weather-independent: weather only modifies attributes,
not which rooms can roll which spawns. Regenerate with:

    python ocean/abyss/tools/fetch_qsna_spawns.py
"""

from __future__ import annotations

import argparse
import json
import urllib.request
from pathlib import Path

STATS_URL = "https://www.qsna.eu/api/eve/custom/abyss/stats"
NPCS_URL = "https://www.qsna.eu/api/eve/universe/items/npcs/1982;1997"

TIER_ORDER = [
    "tranquil", "calm", "agitated", "fierce", "raging", "chaotic", "cataclysmic",
]


def fetch(url: str) -> dict:
    request = urllib.request.Request(url, headers={"User-Agent": "puffertank-abyss-tools"})
    with urllib.request.urlopen(request, timeout=60) as response:
        return json.load(response)


def write_markdown_tables(stats: dict, npcs: dict, path: Path) -> None:
    id2name = {int(tid): entry.get("name", str(tid)) for tid, entry in npcs["data"].items()}
    lines = [
        "# QSNA / abyssal.space spawn tables",
        "",
        "Generated by `tools/fetch_qsna_spawns.py`. Do not edit by hand.",
        "Chances are per-room occurrence frequencies from player-submitted runs",
        "(roomsCount = sample size). Weather does not change spawn tables.",
        "",
    ]
    for tier in TIER_ORDER:
        tier_data = stats["tiers"].get(tier)
        if not tier_data:
            continue
        lines.append(f"## {tier} (penalty {tier_data['penalty']})")
        lines.append("")
        for sname, spawn in tier_data["spawns"].items():
            label = stats["enemies"].get(sname, {}).get("name", sname)
            live = [
                (entry["chance"], entry["min"], entry["max"], entry["avg"], tid)
                for tid, entry in spawn["enemies"].items()
                if entry.get("chance", 0) > 0
            ]
            if not live:
                lines.append(f"- **{label}** (`{sname}`): no T-data samples")
                continue
            live.sort(reverse=True)
            lines.append(f"- **{label}** (`{sname}`), rooms={spawn['roomsCount']}, "
                         f"enemies/room avg={spawn['averageEnemiesPerRoom']} "
                         f"min={spawn['minimumEnemiesPerRoom']} max={spawn['maximumEnemiesPerRoom']}")
            for chance, low, high, avg, tid in live:
                name = id2name.get(int(tid), str(tid))
                lines.append(f"  - {name} (type {tid}): {chance * 100:.0f}% of rooms, "
                             f"x{low}-{high}, avg {avg:.2f}")
        lines.append("")
    path.write_text("\n".join(lines).rstrip() + "\n", encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--data-dir", type=Path, default=Path(__file__).resolve().parents[1] / "data")
    args = parser.parse_args()

    args.data_dir.mkdir(parents=True, exist_ok=True)
    print(f"fetching {STATS_URL}")
    stats = fetch(STATS_URL)
    print(f"fetching {NPCS_URL}")
    npcs = fetch(NPCS_URL)

    stats_path = args.data_dir / "spawn_stats_qsna.json"
    npcs_path = args.data_dir / "npc_types_qsna.json"
    stats_path.write_text(json.dumps(stats, indent=1), encoding="utf-8")
    npcs_path.write_text(json.dumps(npcs, indent=1), encoding="utf-8")
    print(f"wrote {stats_path} ({stats_path.stat().st_size} bytes)")
    print(f"wrote {npcs_path} ({npcs_path.stat().st_size} bytes)")

    tables_path = args.data_dir / "spawn_tables_qsna.md"
    write_markdown_tables(stats, npcs, tables_path)
    print(f"wrote {tables_path}")


if __name__ == "__main__":
    main()
