# Generated stable IDs from Showdown 9fb3a5b99f1a0bea17f495c5cc1bfe04fdd19c3e
import Base

def abilities_adaptability() -> U32:
  1

def abilities_aerilate() -> U32:
  2

def abilities_aftermath() -> U32:
  3

def abilities_airlock() -> U32:
  4

def abilities_analytic() -> U32:
  5

def abilities_angerpoint() -> U32:
  6

def abilities_angershell() -> U32:
  7

def abilities_anticipation() -> U32:
  8

def abilities_arenatrap() -> U32:
  9

def abilities_armortail() -> U32:
  10

def abilities_aromaveil() -> U32:
  11

def abilities_asoneglastrier() -> U32:
  12

def abilities_asonespectrier() -> U32:
  13

def abilities_aurabreak() -> U32:
  14

def abilities_auraguard() -> U32:
  15

def abilities_baddreams() -> U32:
  16

def abilities_ballfetch() -> U32:
  17

def abilities_battery() -> U32:
  18

def abilities_battlearmor() -> U32:
  19

def abilities_battlebond() -> U32:
  20

def abilities_beadsofruin() -> U32:
  21

def abilities_beastboost() -> U32:
  22

def abilities_berserk() -> U32:
  23

def abilities_bigpecks() -> U32:
  24

def abilities_blaze() -> U32:
  25

def abilities_bulletproof() -> U32:
  26

def abilities_cheekpouch() -> U32:
  27

def abilities_chillingneigh() -> U32:
  28

def abilities_chlorophyll() -> U32:
  29

def abilities_clearbody() -> U32:
  30

def abilities_cloudnine() -> U32:
  31

def abilities_colorchange() -> U32:
  32

def abilities_comatose() -> U32:
  33

def abilities_commander() -> U32:
  34

def abilities_competitive() -> U32:
  35

def abilities_compoundeyes() -> U32:
  36

def abilities_contrary() -> U32:
  37

def abilities_corrosion() -> U32:
  38

def abilities_costar() -> U32:
  39

def abilities_cottondown() -> U32:
  40

def abilities_cudchew() -> U32:
  41

def abilities_curiousmedicine() -> U32:
  42

def abilities_cursedbody() -> U32:
  43

def abilities_cutecharm() -> U32:
  44

def abilities_damp() -> U32:
  45

def abilities_dancer() -> U32:
  46

def abilities_darkaura() -> U32:
  47

def abilities_dauntlessshield() -> U32:
  48

def abilities_dazzling() -> U32:
  49

def abilities_defeatist() -> U32:
  50

def abilities_defiant() -> U32:
  51

def abilities_deltastream() -> U32:
  52

def abilities_desolateland() -> U32:
  53

def abilities_disguise() -> U32:
  54

def abilities_download() -> U32:
  55

def abilities_dragonize() -> U32:
  56

def abilities_dragonsmaw() -> U32:
  57

def abilities_drizzle() -> U32:
  58

def abilities_drought() -> U32:
  59

def abilities_dryskin() -> U32:
  60

def abilities_earlybird() -> U32:
  61

def abilities_eartheater() -> U32:
  62

def abilities_eelevate() -> U32:
  63

def abilities_effectspore() -> U32:
  64

def abilities_electricsurge() -> U32:
  65

def abilities_electromorphosis() -> U32:
  66

def abilities_embodyaspectcornerstone() -> U32:
  67

def abilities_embodyaspecthearthflame() -> U32:
  68

def abilities_embodyaspectteal() -> U32:
  69

def abilities_embodyaspectwellspring() -> U32:
  70

def abilities_emergencyexit() -> U32:
  71

def abilities_fairyaura() -> U32:
  72

def abilities_filter() -> U32:
  73

def abilities_firemane() -> U32:
  74

def abilities_flamebody() -> U32:
  75

def abilities_flareboost() -> U32:
  76

def abilities_flashfire() -> U32:
  77

def abilities_flowergift() -> U32:
  78

def abilities_flowerveil() -> U32:
  79

def abilities_fluffy() -> U32:
  80

def abilities_forecast() -> U32:
  81

def abilities_forewarn() -> U32:
  82

def abilities_friendguard() -> U32:
  83

def abilities_frisk() -> U32:
  84

def abilities_fullmetalbody() -> U32:
  85

def abilities_furcoat() -> U32:
  86

def abilities_galewings() -> U32:
  87

def abilities_galvanize() -> U32:
  88

def abilities_gluttony() -> U32:
  89

def abilities_goodasgold() -> U32:
  90

def abilities_gooey() -> U32:
  91

def abilities_gorillatactics() -> U32:
  92

def abilities_grasspelt() -> U32:
  93

def abilities_grassysurge() -> U32:
  94

def abilities_grimneigh() -> U32:
  95

def abilities_guarddog() -> U32:
  96

def abilities_gulpmissile() -> U32:
  97

def abilities_guts() -> U32:
  98

def abilities_hadronengine() -> U32:
  99

def abilities_harvest() -> U32:
  100

def abilities_healer() -> U32:
  101

def abilities_heatproof() -> U32:
  102

def abilities_heavymetal() -> U32:
  103

def abilities_honeygather() -> U32:
  104

def abilities_hospitality() -> U32:
  105

def abilities_hugepower() -> U32:
  106

def abilities_hungerswitch() -> U32:
  107

def abilities_hustle() -> U32:
  108

def abilities_hydration() -> U32:
  109

def abilities_hypercutter() -> U32:
  110

def abilities_icebody() -> U32:
  111

def abilities_iceface() -> U32:
  112

def abilities_icescales() -> U32:
  113

def abilities_illuminate() -> U32:
  114

def abilities_illusion() -> U32:
  115

def abilities_immunity() -> U32:
  116

def abilities_imposter() -> U32:
  117

def abilities_infiltrator() -> U32:
  118

def abilities_innardsout() -> U32:
  119

def abilities_innerfocus() -> U32:
  120

def abilities_insomnia() -> U32:
  121

def abilities_intimidate() -> U32:
  122

def abilities_intrepidsword() -> U32:
  123

def abilities_ironbarbs() -> U32:
  124

def abilities_ironfist() -> U32:
  125

def abilities_justified() -> U32:
  126

def abilities_keeneye() -> U32:
  127

def abilities_klutz() -> U32:
  128

def abilities_leafguard() -> U32:
  129

def abilities_levitate() -> U32:
  130

def abilities_libero() -> U32:
  131

def abilities_lightmetal() -> U32:
  132

def abilities_lightningrod() -> U32:
  133

def abilities_limber() -> U32:
  134

def abilities_lingeringaroma() -> U32:
  135

def abilities_liquidooze() -> U32:
  136

def abilities_liquidvoice() -> U32:
  137

def abilities_longreach() -> U32:
  138

def abilities_magicbounce() -> U32:
  139

def abilities_magicguard() -> U32:
  140

def abilities_magician() -> U32:
  141

def abilities_magmaarmor() -> U32:
  142

def abilities_magnetpull() -> U32:
  143

def abilities_marvelscale() -> U32:
  144

def abilities_megalauncher() -> U32:
  145

def abilities_megasol() -> U32:
  146

def abilities_merciless() -> U32:
  147

def abilities_mimicry() -> U32:
  148

def abilities_mindseye() -> U32:
  149

def abilities_minus() -> U32:
  150

def abilities_mirrorarmor() -> U32:
  151

def abilities_mistysurge() -> U32:
  152

def abilities_moldbreaker() -> U32:
  153

def abilities_moody() -> U32:
  154

def abilities_motordrive() -> U32:
  155

def abilities_mountaineer() -> U32:
  156

def abilities_moxie() -> U32:
  157

def abilities_multiscale() -> U32:
  158

def abilities_multitype() -> U32:
  159

def abilities_mummy() -> U32:
  160

def abilities_myceliummight() -> U32:
  161

def abilities_naturalcure() -> U32:
  162

def abilities_neuroforce() -> U32:
  163

def abilities_neutralizinggas() -> U32:
  164

def abilities_noability() -> U32:
  165

def abilities_noguard() -> U32:
  166

def abilities_normalize() -> U32:
  167

def abilities_oblivious() -> U32:
  168

def abilities_opportunist() -> U32:
  169

def abilities_orichalcumpulse() -> U32:
  170

def abilities_overcoat() -> U32:
  171

def abilities_overgrow() -> U32:
  172

def abilities_owntempo() -> U32:
  173

def abilities_parentalbond() -> U32:
  174

def abilities_pastelveil() -> U32:
  175

def abilities_perishbody() -> U32:
  176

def abilities_persistent() -> U32:
  177

def abilities_pickpocket() -> U32:
  178

def abilities_pickup() -> U32:
  179

def abilities_piercingdrill() -> U32:
  180

def abilities_pixilate() -> U32:
  181

def abilities_plus() -> U32:
  182

def abilities_poisonheal() -> U32:
  183

def abilities_poisonpoint() -> U32:
  184

def abilities_poisonpuppeteer() -> U32:
  185

def abilities_poisontouch() -> U32:
  186

def abilities_powerconstruct() -> U32:
  187

def abilities_powerofalchemy() -> U32:
  188

def abilities_powerspot() -> U32:
  189

def abilities_prankster() -> U32:
  190

def abilities_pressure() -> U32:
  191

def abilities_primordialsea() -> U32:
  192

def abilities_prismarmor() -> U32:
  193

def abilities_propellertail() -> U32:
  194

def abilities_protean() -> U32:
  195

def abilities_protosynthesis() -> U32:
  196

def abilities_psychicsurge() -> U32:
  197

def abilities_punkrock() -> U32:
  198

def abilities_purepower() -> U32:
  199

def abilities_purifyingsalt() -> U32:
  200

def abilities_quarkdrive() -> U32:
  201

def abilities_queenlymajesty() -> U32:
  202

def abilities_quickdraw() -> U32:
  203

def abilities_quickfeet() -> U32:
  204

def abilities_raindish() -> U32:
  205

def abilities_rattled() -> U32:
  206

def abilities_rebound() -> U32:
  207

def abilities_receiver() -> U32:
  208

def abilities_reckless() -> U32:
  209

def abilities_refrigerate() -> U32:
  210

def abilities_regenerator() -> U32:
  211

def abilities_ripen() -> U32:
  212

def abilities_rivalry() -> U32:
  213

def abilities_rkssystem() -> U32:
  214

def abilities_rockhead() -> U32:
  215

def abilities_rockypayload() -> U32:
  216

def abilities_roughskin() -> U32:
  217

def abilities_runaway() -> U32:
  218

def abilities_sandforce() -> U32:
  219

def abilities_sandrush() -> U32:
  220

def abilities_sandspit() -> U32:
  221

def abilities_sandstream() -> U32:
  222

def abilities_sandveil() -> U32:
  223

def abilities_sapsipper() -> U32:
  224

def abilities_schooling() -> U32:
  225

def abilities_scrappy() -> U32:
  226

def abilities_screencleaner() -> U32:
  227

def abilities_seedsower() -> U32:
  228

def abilities_serenegrace() -> U32:
  229

def abilities_shadowshield() -> U32:
  230

def abilities_shadowtag() -> U32:
  231

def abilities_sharpness() -> U32:
  232

def abilities_shedskin() -> U32:
  233

def abilities_sheerforce() -> U32:
  234

def abilities_shellarmor() -> U32:
  235

def abilities_shielddust() -> U32:
  236

def abilities_shieldsdown() -> U32:
  237

def abilities_simple() -> U32:
  238

def abilities_skilllink() -> U32:
  239

def abilities_slowstart() -> U32:
  240

def abilities_slushrush() -> U32:
  241

def abilities_sniper() -> U32:
  242

def abilities_snowcloak() -> U32:
  243

def abilities_snowwarning() -> U32:
  244

def abilities_solarpower() -> U32:
  245

def abilities_solidrock() -> U32:
  246

def abilities_soulheart() -> U32:
  247

def abilities_soundproof() -> U32:
  248

def abilities_speedboost() -> U32:
  249

def abilities_spicyspray() -> U32:
  250

def abilities_stakeout() -> U32:
  251

def abilities_stall() -> U32:
  252

def abilities_stalwart() -> U32:
  253

def abilities_stamina() -> U32:
  254

def abilities_stancechange() -> U32:
  255

def abilities_static() -> U32:
  256

def abilities_steadfast() -> U32:
  257

def abilities_steamengine() -> U32:
  258

def abilities_steelworker() -> U32:
  259

def abilities_steelyspirit() -> U32:
  260

def abilities_stench() -> U32:
  261

def abilities_stickyhold() -> U32:
  262

def abilities_stormdrain() -> U32:
  263

def abilities_strongjaw() -> U32:
  264

def abilities_sturdy() -> U32:
  265

def abilities_suctioncups() -> U32:
  266

def abilities_superluck() -> U32:
  267

def abilities_supersweetsyrup() -> U32:
  268

def abilities_supremeoverlord() -> U32:
  269

def abilities_surgesurfer() -> U32:
  270

def abilities_swarm() -> U32:
  271

def abilities_sweetveil() -> U32:
  272

def abilities_swiftswim() -> U32:
  273

def abilities_swordofruin() -> U32:
  274

def abilities_symbiosis() -> U32:
  275

def abilities_synchronize() -> U32:
  276

def abilities_tabletsofruin() -> U32:
  277

def abilities_tangledfeet() -> U32:
  278

def abilities_tanglinghair() -> U32:
  279

def abilities_technician() -> U32:
  280

def abilities_telepathy() -> U32:
  281

def abilities_teraformzero() -> U32:
  282

def abilities_terashell() -> U32:
  283

def abilities_terashift() -> U32:
  284

def abilities_teravolt() -> U32:
  285

def abilities_thermalexchange() -> U32:
  286

def abilities_thickfat() -> U32:
  287

def abilities_tintedlens() -> U32:
  288

def abilities_torrent() -> U32:
  289

def abilities_toughclaws() -> U32:
  290

def abilities_toxicboost() -> U32:
  291

def abilities_toxicchain() -> U32:
  292

def abilities_toxicdebris() -> U32:
  293

def abilities_trace() -> U32:
  294

def abilities_transistor() -> U32:
  295

def abilities_triage() -> U32:
  296

def abilities_truant() -> U32:
  297

def abilities_turboblaze() -> U32:
  298

def abilities_unaware() -> U32:
  299

def abilities_unburden() -> U32:
  300

def abilities_unnerve() -> U32:
  301

def abilities_unseenfist() -> U32:
  302

def abilities_vesselofruin() -> U32:
  303

def abilities_victorystar() -> U32:
  304

def abilities_vitalspirit() -> U32:
  305

def abilities_voltabsorb() -> U32:
  306

def abilities_wanderingspirit() -> U32:
  307

def abilities_waterabsorb() -> U32:
  308

def abilities_waterbubble() -> U32:
  309

def abilities_watercompaction() -> U32:
  310

def abilities_waterveil() -> U32:
  311

def abilities_weakarmor() -> U32:
  312

def abilities_wellbakedbody() -> U32:
  313

def abilities_whitesmoke() -> U32:
  314

def abilities_wimpout() -> U32:
  315

def abilities_windpower() -> U32:
  316

def abilities_windrider() -> U32:
  317

def abilities_wonderguard() -> U32:
  318

def abilities_wonderskin() -> U32:
  319

def abilities_zenmode() -> U32:
  320

def abilities_zerotohero() -> U32:
  321
