# Generated stable IDs from Showdown 9fb3a5b99f1a0bea17f495c5cc1bfe04fdd19c3e
import Base

def callbacks_basepowercallback() -> U32:
  1

def callbacks_beforemovecallback() -> U32:
  2

def callbacks_beforeturncallback() -> U32:
  3

def callbacks_damagecallback() -> U32:
  4

def callbacks_durationcallback() -> U32:
  5

def callbacks_onaccuracy() -> U32:
  6

def callbacks_onafterboost() -> U32:
  7

def callbacks_onaftereachboost() -> U32:
  8

def callbacks_onafterhit() -> U32:
  9

def callbacks_onaftermega() -> U32:
  10

def callbacks_onaftermove() -> U32:
  11

def callbacks_onaftermovesecondary() -> U32:
  12

def callbacks_onaftermovesecondaryself() -> U32:
  13

def callbacks_onaftersetstatus() -> U32:
  14

def callbacks_onaftersubdamage() -> U32:
  15

def callbacks_onafterterastallization() -> U32:
  16

def callbacks_onafteruseitem() -> U32:
  17

def callbacks_onallyafteruseitem() -> U32:
  18

def callbacks_onallybasepower() -> U32:
  19

def callbacks_onallyfaint() -> U32:
  20

def callbacks_onallymodifyatk() -> U32:
  21

def callbacks_onallymodifyspd() -> U32:
  22

def callbacks_onallysetstatus() -> U32:
  23

def callbacks_onallytryaddvolatile() -> U32:
  24

def callbacks_onallytryboost() -> U32:
  25

def callbacks_onallytryhitside() -> U32:
  26

def callbacks_onanyaccuracy() -> U32:
  27

def callbacks_onanyaftermega() -> U32:
  28

def callbacks_onanyaftermove() -> U32:
  29

def callbacks_onanyaftersetstatus() -> U32:
  30

def callbacks_onanyafterterastallization() -> U32:
  31

def callbacks_onanybasepower() -> U32:
  32

def callbacks_onanydamage() -> U32:
  33

def callbacks_onanydragout() -> U32:
  34

def callbacks_onanyfaint() -> U32:
  35

def callbacks_onanyinvulnerability() -> U32:
  36

def callbacks_onanymodifyaccuracy() -> U32:
  37

def callbacks_onanymodifyatk() -> U32:
  38

def callbacks_onanymodifyboost() -> U32:
  39

def callbacks_onanymodifydamage() -> U32:
  40

def callbacks_onanymodifydef() -> U32:
  41

def callbacks_onanymodifyspa() -> U32:
  42

def callbacks_onanymodifyspd() -> U32:
  43

def callbacks_onanypreparehit() -> U32:
  44

def callbacks_onanypseudoweatherchange() -> U32:
  45

def callbacks_onanyredirecttarget() -> U32:
  46

def callbacks_onanysetstatus() -> U32:
  47

def callbacks_onanysetweather() -> U32:
  48

def callbacks_onanyswitchin() -> U32:
  49

def callbacks_onanytrymove() -> U32:
  50

def callbacks_onanytryprimaryhit() -> U32:
  51

def callbacks_onattract() -> U32:
  52

def callbacks_onbasepower() -> U32:
  53

def callbacks_onbattlestart() -> U32:
  54

def callbacks_onbeforemove() -> U32:
  55

def callbacks_onbeforeswitchin() -> U32:
  56

def callbacks_onbeforeswitchout() -> U32:
  57

def callbacks_onbeforeturn() -> U32:
  58

def callbacks_onbegin() -> U32:
  59

def callbacks_onchangeboost() -> U32:
  60

def callbacks_onchangeset() -> U32:
  61

def callbacks_onchargemove() -> U32:
  62

def callbacks_oncheckshow() -> U32:
  63

def callbacks_onchooseteam() -> U32:
  64

def callbacks_oncopy() -> U32:
  65

def callbacks_oncriticalhit() -> U32:
  66

def callbacks_ondamage() -> U32:
  67

def callbacks_ondamaginghit() -> U32:
  68

def callbacks_ondeductpp() -> U32:
  69

def callbacks_ondisablemove() -> U32:
  70

def callbacks_ondragout() -> U32:
  71

def callbacks_oneat() -> U32:
  72

def callbacks_oneatitem() -> U32:
  73

def callbacks_oneffectiveness() -> U32:
  74

def callbacks_onemergencyexit() -> U32:
  75

def callbacks_onend() -> U32:
  76

def callbacks_onfaint() -> U32:
  77

def callbacks_onfieldend() -> U32:
  78

def callbacks_onfieldresidual() -> U32:
  79

def callbacks_onfieldrestart() -> U32:
  80

def callbacks_onfieldstart() -> U32:
  81

def callbacks_onflinch() -> U32:
  82

def callbacks_onfoeafterboost() -> U32:
  83

def callbacks_onfoebeforemove() -> U32:
  84

def callbacks_onfoebeforeswitchout() -> U32:
  85

def callbacks_onfoedisablemove() -> U32:
  86

def callbacks_onfoemaybetrappokemon() -> U32:
  87

def callbacks_onfoeredirecttarget() -> U32:
  88

def callbacks_onfoetrappokemon() -> U32:
  89

def callbacks_onfoetryeatitem() -> U32:
  90

def callbacks_onfoetrymove() -> U32:
  91

def callbacks_onfractionalpriority() -> U32:
  92

def callbacks_onhit() -> U32:
  93

def callbacks_onhitfield() -> U32:
  94

def callbacks_onhitprotect() -> U32:
  95

def callbacks_onhitside() -> U32:
  96

def callbacks_onimmunity() -> U32:
  97

def callbacks_oninvulnerability() -> U32:
  98

def callbacks_onlockmove() -> U32:
  99

def callbacks_onmaybetrappokemon() -> U32:
  100

def callbacks_onmodifyaccuracy() -> U32:
  101

def callbacks_onmodifyatk() -> U32:
  102

def callbacks_onmodifyboost() -> U32:
  103

def callbacks_onmodifycritratio() -> U32:
  104

def callbacks_onmodifydamage() -> U32:
  105

def callbacks_onmodifydef() -> U32:
  106

def callbacks_onmodifymove() -> U32:
  107

def callbacks_onmodifypriority() -> U32:
  108

def callbacks_onmodifysecondaries() -> U32:
  109

def callbacks_onmodifyspa() -> U32:
  110

def callbacks_onmodifyspd() -> U32:
  111

def callbacks_onmodifyspe() -> U32:
  112

def callbacks_onmodifyspecies() -> U32:
  113

def callbacks_onmodifystab() -> U32:
  114

def callbacks_onmodifytarget() -> U32:
  115

def callbacks_onmodifytype() -> U32:
  116

def callbacks_onmodifyweight() -> U32:
  117

def callbacks_onmoveaborted() -> U32:
  118

def callbacks_onmovefail() -> U32:
  119

def callbacks_onnegateimmunity() -> U32:
  120

def callbacks_onoverrideaction() -> U32:
  121

def callbacks_onpreparehit() -> U32:
  122

def callbacks_onpseudoweatherchange() -> U32:
  123

def callbacks_onredirecttarget() -> U32:
  124

def callbacks_onresidual() -> U32:
  125

def callbacks_onrestart() -> U32:
  126

def callbacks_onsetability() -> U32:
  127

def callbacks_onsetstatus() -> U32:
  128

def callbacks_onsideconditionstart() -> U32:
  129

def callbacks_onsideend() -> U32:
  130

def callbacks_onsideresidual() -> U32:
  131

def callbacks_onsiderestart() -> U32:
  132

def callbacks_onsidestart() -> U32:
  133

def callbacks_onsourceaccuracy() -> U32:
  134

def callbacks_onsourceafterfaint() -> U32:
  135

def callbacks_onsourcebasepower() -> U32:
  136

def callbacks_onsourcedamaginghit() -> U32:
  137

def callbacks_onsourceinvulnerability() -> U32:
  138

def callbacks_onsourcemodifyaccuracy() -> U32:
  139

def callbacks_onsourcemodifyatk() -> U32:
  140

def callbacks_onsourcemodifydamage() -> U32:
  141

def callbacks_onsourcemodifysecondaries() -> U32:
  142

def callbacks_onsourcemodifyspa() -> U32:
  143

def callbacks_onsourcetryheal() -> U32:
  144

def callbacks_onsourcetryprimaryhit() -> U32:
  145

def callbacks_onstallmove() -> U32:
  146

def callbacks_onstart() -> U32:
  147

def callbacks_onswap() -> U32:
  148

def callbacks_onswitchin() -> U32:
  149

def callbacks_onswitchout() -> U32:
  150

def callbacks_ontakeitem() -> U32:
  151

def callbacks_onteampreview() -> U32:
  152

def callbacks_onterrainchange() -> U32:
  153

def callbacks_ontrappokemon() -> U32:
  154

def callbacks_ontry() -> U32:
  155

def callbacks_ontryaddvolatile() -> U32:
  156

def callbacks_ontryboost() -> U32:
  157

def callbacks_ontryeatitem() -> U32:
  158

def callbacks_ontryheal() -> U32:
  159

def callbacks_ontryhit() -> U32:
  160

def callbacks_ontryimmunity() -> U32:
  161

def callbacks_ontrymove() -> U32:
  162

def callbacks_ontryprimaryhit() -> U32:
  163

def callbacks_ontype() -> U32:
  164

def callbacks_onupdate() -> U32:
  165

def callbacks_onuse() -> U32:
  166

def callbacks_onuseitem() -> U32:
  167

def callbacks_onusemovemessage() -> U32:
  168

def callbacks_onvalidaterule() -> U32:
  169

def callbacks_onvalidateset() -> U32:
  170

def callbacks_onvalidateteam() -> U32:
  171

def callbacks_onweather() -> U32:
  172

def callbacks_onweatherchange() -> U32:
  173

def callbacks_onweathermodifydamage() -> U32:
  174

def callbacks_prioritychargecallback() -> U32:
  175

def callbacks_onafterfaint() -> U32:
  176

def callbacks_onaftertakeitem() -> U32:
  177

def callbacks_onbeforefaint() -> U32:
  178

def callbacks_onblah() -> U32:
  179

def callbacks_ondrive() -> U32:
  180

def callbacks_onentryhazard() -> U32:
  181

def callbacks_onheal() -> U32:
  182

def callbacks_onmemory() -> U32:
  183

def callbacks_onplate() -> U32:
  184

def callbacks_onsemilockmove() -> U32:
  185

def callbacks_onsetweather() -> U32:
  186

def callbacks_ontryhitfield() -> U32:
  187

def callbacks_ontryhitside() -> U32:
  188

def callbacks_ontryterrain() -> U32:
  189
