# Generated stable IDs from Showdown 9fb3a5b99f1a0bea17f495c5cc1bfe04fdd19c3e
import Base

def conditions_350cupmod() -> U32:
  1

def conditions_aaarestrictedabilities() -> U32:
  2

def conditions_ability_adaptability() -> U32:
  3

def conditions_ability_aerilate() -> U32:
  4

def conditions_ability_aftermath() -> U32:
  5

def conditions_ability_airlock() -> U32:
  6

def conditions_ability_analytic() -> U32:
  7

def conditions_ability_angerpoint() -> U32:
  8

def conditions_ability_angershell() -> U32:
  9

def conditions_ability_anticipation() -> U32:
  10

def conditions_ability_arenatrap() -> U32:
  11

def conditions_ability_armortail() -> U32:
  12

def conditions_ability_aromaveil() -> U32:
  13

def conditions_ability_asoneglastrier() -> U32:
  14

def conditions_ability_asonespectrier() -> U32:
  15

def conditions_ability_aurabreak() -> U32:
  16

def conditions_ability_auraguard() -> U32:
  17

def conditions_ability_baddreams() -> U32:
  18

def conditions_ability_ballfetch() -> U32:
  19

def conditions_ability_battery() -> U32:
  20

def conditions_ability_battlearmor() -> U32:
  21

def conditions_ability_battlebond() -> U32:
  22

def conditions_ability_beadsofruin() -> U32:
  23

def conditions_ability_beastboost() -> U32:
  24

def conditions_ability_berserk() -> U32:
  25

def conditions_ability_bigpecks() -> U32:
  26

def conditions_ability_blaze() -> U32:
  27

def conditions_ability_bulletproof() -> U32:
  28

def conditions_ability_cheekpouch() -> U32:
  29

def conditions_ability_chillingneigh() -> U32:
  30

def conditions_ability_chlorophyll() -> U32:
  31

def conditions_ability_clearbody() -> U32:
  32

def conditions_ability_cloudnine() -> U32:
  33

def conditions_ability_colorchange() -> U32:
  34

def conditions_ability_comatose() -> U32:
  35

def conditions_ability_commander() -> U32:
  36

def conditions_ability_competitive() -> U32:
  37

def conditions_ability_compoundeyes() -> U32:
  38

def conditions_ability_contrary() -> U32:
  39

def conditions_ability_corrosion() -> U32:
  40

def conditions_ability_costar() -> U32:
  41

def conditions_ability_cottondown() -> U32:
  42

def conditions_ability_cudchew() -> U32:
  43

def conditions_ability_curiousmedicine() -> U32:
  44

def conditions_ability_cursedbody() -> U32:
  45

def conditions_ability_cutecharm() -> U32:
  46

def conditions_ability_damp() -> U32:
  47

def conditions_ability_dancer() -> U32:
  48

def conditions_ability_darkaura() -> U32:
  49

def conditions_ability_dauntlessshield() -> U32:
  50

def conditions_ability_dazzling() -> U32:
  51

def conditions_ability_defeatist() -> U32:
  52

def conditions_ability_defiant() -> U32:
  53

def conditions_ability_deltastream() -> U32:
  54

def conditions_ability_desolateland() -> U32:
  55

def conditions_ability_disguise() -> U32:
  56

def conditions_ability_download() -> U32:
  57

def conditions_ability_dragonize() -> U32:
  58

def conditions_ability_dragonsmaw() -> U32:
  59

def conditions_ability_drizzle() -> U32:
  60

def conditions_ability_drought() -> U32:
  61

def conditions_ability_dryskin() -> U32:
  62

def conditions_ability_earlybird() -> U32:
  63

def conditions_ability_eartheater() -> U32:
  64

def conditions_ability_eelevate() -> U32:
  65

def conditions_ability_effectspore() -> U32:
  66

def conditions_ability_electricsurge() -> U32:
  67

def conditions_ability_electromorphosis() -> U32:
  68

def conditions_ability_embodyaspectcornerstone() -> U32:
  69

def conditions_ability_embodyaspecthearthflame() -> U32:
  70

def conditions_ability_embodyaspectteal() -> U32:
  71

def conditions_ability_embodyaspectwellspring() -> U32:
  72

def conditions_ability_emergencyexit() -> U32:
  73

def conditions_ability_fairyaura() -> U32:
  74

def conditions_ability_filter() -> U32:
  75

def conditions_ability_firemane() -> U32:
  76

def conditions_ability_flamebody() -> U32:
  77

def conditions_ability_flareboost() -> U32:
  78

def conditions_ability_flashfire() -> U32:
  79

def conditions_ability_flowergift() -> U32:
  80

def conditions_ability_flowerveil() -> U32:
  81

def conditions_ability_fluffy() -> U32:
  82

def conditions_ability_forecast() -> U32:
  83

def conditions_ability_forewarn() -> U32:
  84

def conditions_ability_friendguard() -> U32:
  85

def conditions_ability_frisk() -> U32:
  86

def conditions_ability_fullmetalbody() -> U32:
  87

def conditions_ability_furcoat() -> U32:
  88

def conditions_ability_galewings() -> U32:
  89

def conditions_ability_galvanize() -> U32:
  90

def conditions_ability_gluttony() -> U32:
  91

def conditions_ability_goodasgold() -> U32:
  92

def conditions_ability_gooey() -> U32:
  93

def conditions_ability_gorillatactics() -> U32:
  94

def conditions_ability_grasspelt() -> U32:
  95

def conditions_ability_grassysurge() -> U32:
  96

def conditions_ability_grimneigh() -> U32:
  97

def conditions_ability_guarddog() -> U32:
  98

def conditions_ability_gulpmissile() -> U32:
  99

def conditions_ability_guts() -> U32:
  100

def conditions_ability_hadronengine() -> U32:
  101

def conditions_ability_harvest() -> U32:
  102

def conditions_ability_healer() -> U32:
  103

def conditions_ability_heatproof() -> U32:
  104

def conditions_ability_heavymetal() -> U32:
  105

def conditions_ability_honeygather() -> U32:
  106

def conditions_ability_hospitality() -> U32:
  107

def conditions_ability_hugepower() -> U32:
  108

def conditions_ability_hungerswitch() -> U32:
  109

def conditions_ability_hustle() -> U32:
  110

def conditions_ability_hydration() -> U32:
  111

def conditions_ability_hypercutter() -> U32:
  112

def conditions_ability_icebody() -> U32:
  113

def conditions_ability_iceface() -> U32:
  114

def conditions_ability_icescales() -> U32:
  115

def conditions_ability_illuminate() -> U32:
  116

def conditions_ability_illusion() -> U32:
  117

def conditions_ability_immunity() -> U32:
  118

def conditions_ability_imposter() -> U32:
  119

def conditions_ability_infiltrator() -> U32:
  120

def conditions_ability_innardsout() -> U32:
  121

def conditions_ability_innerfocus() -> U32:
  122

def conditions_ability_insomnia() -> U32:
  123

def conditions_ability_intimidate() -> U32:
  124

def conditions_ability_intrepidsword() -> U32:
  125

def conditions_ability_ironbarbs() -> U32:
  126

def conditions_ability_ironfist() -> U32:
  127

def conditions_ability_justified() -> U32:
  128

def conditions_ability_keeneye() -> U32:
  129

def conditions_ability_klutz() -> U32:
  130

def conditions_ability_leafguard() -> U32:
  131

def conditions_ability_levitate() -> U32:
  132

def conditions_ability_libero() -> U32:
  133

def conditions_ability_lightmetal() -> U32:
  134

def conditions_ability_lightningrod() -> U32:
  135

def conditions_ability_limber() -> U32:
  136

def conditions_ability_lingeringaroma() -> U32:
  137

def conditions_ability_liquidooze() -> U32:
  138

def conditions_ability_liquidvoice() -> U32:
  139

def conditions_ability_longreach() -> U32:
  140

def conditions_ability_magicbounce() -> U32:
  141

def conditions_ability_magicguard() -> U32:
  142

def conditions_ability_magician() -> U32:
  143

def conditions_ability_magmaarmor() -> U32:
  144

def conditions_ability_magnetpull() -> U32:
  145

def conditions_ability_marvelscale() -> U32:
  146

def conditions_ability_megalauncher() -> U32:
  147

def conditions_ability_megasol() -> U32:
  148

def conditions_ability_merciless() -> U32:
  149

def conditions_ability_mimicry() -> U32:
  150

def conditions_ability_mindseye() -> U32:
  151

def conditions_ability_minus() -> U32:
  152

def conditions_ability_mirrorarmor() -> U32:
  153

def conditions_ability_mistysurge() -> U32:
  154

def conditions_ability_moldbreaker() -> U32:
  155

def conditions_ability_moody() -> U32:
  156

def conditions_ability_motordrive() -> U32:
  157

def conditions_ability_mountaineer() -> U32:
  158

def conditions_ability_moxie() -> U32:
  159

def conditions_ability_multiscale() -> U32:
  160

def conditions_ability_multitype() -> U32:
  161

def conditions_ability_mummy() -> U32:
  162

def conditions_ability_myceliummight() -> U32:
  163

def conditions_ability_naturalcure() -> U32:
  164

def conditions_ability_neuroforce() -> U32:
  165

def conditions_ability_neutralizinggas() -> U32:
  166

def conditions_ability_noability() -> U32:
  167

def conditions_ability_noguard() -> U32:
  168

def conditions_ability_normalize() -> U32:
  169

def conditions_ability_oblivious() -> U32:
  170

def conditions_ability_opportunist() -> U32:
  171

def conditions_ability_orichalcumpulse() -> U32:
  172

def conditions_ability_overcoat() -> U32:
  173

def conditions_ability_overgrow() -> U32:
  174

def conditions_ability_owntempo() -> U32:
  175

def conditions_ability_parentalbond() -> U32:
  176

def conditions_ability_pastelveil() -> U32:
  177

def conditions_ability_perishbody() -> U32:
  178

def conditions_ability_persistent() -> U32:
  179

def conditions_ability_pickpocket() -> U32:
  180

def conditions_ability_pickup() -> U32:
  181

def conditions_ability_piercingdrill() -> U32:
  182

def conditions_ability_pixilate() -> U32:
  183

def conditions_ability_plus() -> U32:
  184

def conditions_ability_poisonheal() -> U32:
  185

def conditions_ability_poisonpoint() -> U32:
  186

def conditions_ability_poisonpuppeteer() -> U32:
  187

def conditions_ability_poisontouch() -> U32:
  188

def conditions_ability_powerconstruct() -> U32:
  189

def conditions_ability_powerofalchemy() -> U32:
  190

def conditions_ability_powerspot() -> U32:
  191

def conditions_ability_prankster() -> U32:
  192

def conditions_ability_pressure() -> U32:
  193

def conditions_ability_primordialsea() -> U32:
  194

def conditions_ability_prismarmor() -> U32:
  195

def conditions_ability_propellertail() -> U32:
  196

def conditions_ability_protean() -> U32:
  197

def conditions_ability_protosynthesis() -> U32:
  198

def conditions_ability_psychicsurge() -> U32:
  199

def conditions_ability_punkrock() -> U32:
  200

def conditions_ability_purepower() -> U32:
  201

def conditions_ability_purifyingsalt() -> U32:
  202

def conditions_ability_quarkdrive() -> U32:
  203

def conditions_ability_queenlymajesty() -> U32:
  204

def conditions_ability_quickdraw() -> U32:
  205

def conditions_ability_quickfeet() -> U32:
  206

def conditions_ability_raindish() -> U32:
  207

def conditions_ability_rattled() -> U32:
  208

def conditions_ability_rebound() -> U32:
  209

def conditions_ability_receiver() -> U32:
  210

def conditions_ability_reckless() -> U32:
  211

def conditions_ability_refrigerate() -> U32:
  212

def conditions_ability_regenerator() -> U32:
  213

def conditions_ability_ripen() -> U32:
  214

def conditions_ability_rivalry() -> U32:
  215

def conditions_ability_rkssystem() -> U32:
  216

def conditions_ability_rockhead() -> U32:
  217

def conditions_ability_rockypayload() -> U32:
  218

def conditions_ability_roughskin() -> U32:
  219

def conditions_ability_runaway() -> U32:
  220

def conditions_ability_sandforce() -> U32:
  221

def conditions_ability_sandrush() -> U32:
  222

def conditions_ability_sandspit() -> U32:
  223

def conditions_ability_sandstream() -> U32:
  224

def conditions_ability_sandveil() -> U32:
  225

def conditions_ability_sapsipper() -> U32:
  226

def conditions_ability_schooling() -> U32:
  227

def conditions_ability_scrappy() -> U32:
  228

def conditions_ability_screencleaner() -> U32:
  229

def conditions_ability_seedsower() -> U32:
  230

def conditions_ability_serenegrace() -> U32:
  231

def conditions_ability_shadowshield() -> U32:
  232

def conditions_ability_shadowtag() -> U32:
  233

def conditions_ability_sharpness() -> U32:
  234

def conditions_ability_shedskin() -> U32:
  235

def conditions_ability_sheerforce() -> U32:
  236

def conditions_ability_shellarmor() -> U32:
  237

def conditions_ability_shielddust() -> U32:
  238

def conditions_ability_shieldsdown() -> U32:
  239

def conditions_ability_simple() -> U32:
  240

def conditions_ability_skilllink() -> U32:
  241

def conditions_ability_slowstart() -> U32:
  242

def conditions_ability_slushrush() -> U32:
  243

def conditions_ability_sniper() -> U32:
  244

def conditions_ability_snowcloak() -> U32:
  245

def conditions_ability_snowwarning() -> U32:
  246

def conditions_ability_solarpower() -> U32:
  247

def conditions_ability_solidrock() -> U32:
  248

def conditions_ability_soulheart() -> U32:
  249

def conditions_ability_soundproof() -> U32:
  250

def conditions_ability_speedboost() -> U32:
  251

def conditions_ability_spicyspray() -> U32:
  252

def conditions_ability_stakeout() -> U32:
  253

def conditions_ability_stall() -> U32:
  254

def conditions_ability_stalwart() -> U32:
  255

def conditions_ability_stamina() -> U32:
  256

def conditions_ability_stancechange() -> U32:
  257

def conditions_ability_static() -> U32:
  258

def conditions_ability_steadfast() -> U32:
  259

def conditions_ability_steamengine() -> U32:
  260

def conditions_ability_steelworker() -> U32:
  261

def conditions_ability_steelyspirit() -> U32:
  262

def conditions_ability_stench() -> U32:
  263

def conditions_ability_stickyhold() -> U32:
  264

def conditions_ability_stormdrain() -> U32:
  265

def conditions_ability_strongjaw() -> U32:
  266

def conditions_ability_sturdy() -> U32:
  267

def conditions_ability_suctioncups() -> U32:
  268

def conditions_ability_superluck() -> U32:
  269

def conditions_ability_supersweetsyrup() -> U32:
  270

def conditions_ability_supremeoverlord() -> U32:
  271

def conditions_ability_surgesurfer() -> U32:
  272

def conditions_ability_swarm() -> U32:
  273

def conditions_ability_sweetveil() -> U32:
  274

def conditions_ability_swiftswim() -> U32:
  275

def conditions_ability_swordofruin() -> U32:
  276

def conditions_ability_symbiosis() -> U32:
  277

def conditions_ability_synchronize() -> U32:
  278

def conditions_ability_tabletsofruin() -> U32:
  279

def conditions_ability_tangledfeet() -> U32:
  280

def conditions_ability_tanglinghair() -> U32:
  281

def conditions_ability_technician() -> U32:
  282

def conditions_ability_telepathy() -> U32:
  283

def conditions_ability_teraformzero() -> U32:
  284

def conditions_ability_terashell() -> U32:
  285

def conditions_ability_terashift() -> U32:
  286

def conditions_ability_teravolt() -> U32:
  287

def conditions_ability_thermalexchange() -> U32:
  288

def conditions_ability_thickfat() -> U32:
  289

def conditions_ability_tintedlens() -> U32:
  290

def conditions_ability_torrent() -> U32:
  291

def conditions_ability_toughclaws() -> U32:
  292

def conditions_ability_toxicboost() -> U32:
  293

def conditions_ability_toxicchain() -> U32:
  294

def conditions_ability_toxicdebris() -> U32:
  295

def conditions_ability_trace() -> U32:
  296

def conditions_ability_transistor() -> U32:
  297

def conditions_ability_triage() -> U32:
  298

def conditions_ability_truant() -> U32:
  299

def conditions_ability_turboblaze() -> U32:
  300

def conditions_ability_unaware() -> U32:
  301

def conditions_ability_unburden() -> U32:
  302

def conditions_ability_unnerve() -> U32:
  303

def conditions_ability_unseenfist() -> U32:
  304

def conditions_ability_vesselofruin() -> U32:
  305

def conditions_ability_victorystar() -> U32:
  306

def conditions_ability_vitalspirit() -> U32:
  307

def conditions_ability_voltabsorb() -> U32:
  308

def conditions_ability_wanderingspirit() -> U32:
  309

def conditions_ability_waterabsorb() -> U32:
  310

def conditions_ability_waterbubble() -> U32:
  311

def conditions_ability_watercompaction() -> U32:
  312

def conditions_ability_waterveil() -> U32:
  313

def conditions_ability_weakarmor() -> U32:
  314

def conditions_ability_wellbakedbody() -> U32:
  315

def conditions_ability_whitesmoke() -> U32:
  316

def conditions_ability_wimpout() -> U32:
  317

def conditions_ability_windpower() -> U32:
  318

def conditions_ability_windrider() -> U32:
  319

def conditions_ability_wonderguard() -> U32:
  320

def conditions_ability_wonderskin() -> U32:
  321

def conditions_ability_zenmode() -> U32:
  322

def conditions_ability_zerotohero() -> U32:
  323

def conditions_abilityclause() -> U32:
  324

def conditions_accuracymovesclause() -> U32:
  325

def conditions_accuracytrapclause() -> U32:
  326

def conditions_adjustlevel() -> U32:
  327

def conditions_adjustleveldown() -> U32:
  328

def conditions_allowedpokemoves() -> U32:
  329

def conditions_allowtradeback() -> U32:
  330

def conditions_allyswitch() -> U32:
  331

def conditions_alphabetcupmovelegality() -> U32:
  332

def conditions_aptclause() -> U32:
  333

def conditions_aquaring() -> U32:
  334

def conditions_arceus() -> U32:
  335

def conditions_attract() -> U32:
  336

def conditions_auroraveil() -> U32:
  337

def conditions_badnboostedmod() -> U32:
  338

def conditions_banefulbunker() -> U32:
  339

def conditions_batonpassclause() -> U32:
  340

def conditions_batonpassstatclause() -> U32:
  341

def conditions_batonpassstattrapclause() -> U32:
  342

def conditions_batonpasstrapclause() -> U32:
  343

def conditions_beakblast() -> U32:
  344

def conditions_beatupnicknamesmod() -> U32:
  345

def conditions_bestof() -> U32:
  346

def conditions_bide() -> U32:
  347

def conditions_blitz() -> U32:
  348

def conditions_blueberrypokedex() -> U32:
  349

def conditions_bonustypemod() -> U32:
  350

def conditions_bounce() -> U32:
  351

def conditions_brn() -> U32:
  352

def conditions_brokenrecordmod() -> U32:
  353

def conditions_burningbulwark() -> U32:
  354

def conditions_camomonsmod() -> U32:
  355

def conditions_cancelmod() -> U32:
  356

def conditions_categoryswapmod() -> U32:
  357

def conditions_cfzclause() -> U32:
  358

def conditions_charge() -> U32:
  359

def conditions_chillyreception() -> U32:
  360

def conditions_chimera1v1rule() -> U32:
  361

def conditions_choicelock() -> U32:
  362

def conditions_commanded() -> U32:
  363

def conditions_commanding() -> U32:
  364

def conditions_confusion() -> U32:
  365

def conditions_convergencelegality() -> U32:
  366

def conditions_counter() -> U32:
  367

def conditions_craftyshield() -> U32:
  368

def conditions_crowntundrapokedex() -> U32:
  369

def conditions_curse() -> U32:
  370

def conditions_datapreview() -> U32:
  371

def conditions_dctimer() -> U32:
  372

def conditions_dctimerbank() -> U32:
  373

def conditions_defaultlevel() -> U32:
  374

def conditions_defensecurl() -> U32:
  375

def conditions_deltastream() -> U32:
  376

def conditions_deoxyscamouflageclausemod() -> U32:
  377

def conditions_desolateland() -> U32:
  378

def conditions_destinybond() -> U32:
  379

def conditions_desyncclausemod() -> U32:
  380

def conditions_dig() -> U32:
  381

def conditions_disable() -> U32:
  382

def conditions_dive() -> U32:
  383

def conditions_dragoncheer() -> U32:
  384

def conditions_drain() -> U32:
  385

def conditions_drypassclause() -> U32:
  386

def conditions_dynamax() -> U32:
  387

def conditions_dynamaxclause() -> U32:
  388

def conditions_echoedvoice() -> U32:
  389

def conditions_electricterrain() -> U32:
  390

def conditions_electrify() -> U32:
  391

def conditions_embargo() -> U32:
  392

def conditions_encore() -> U32:
  393

def conditions_endlessbattleclause() -> U32:
  394

def conditions_endure() -> U32:
  395

def conditions_enforcesameteratype() -> U32:
  396

def conditions_evasionabilitiesclause() -> U32:
  397

def conditions_evasionclause() -> U32:
  398

def conditions_evasionitemsclause() -> U32:
  399

def conditions_evasionmovesclause() -> U32:
  400

def conditions_eventmovesclause() -> U32:
  401

def conditions_evlimit() -> U32:
  402

def conditions_evlimits() -> U32:
  403

def conditions_exacthpmod() -> U32:
  404

def conditions_fairylock() -> U32:
  405

def conditions_ferventimpersonationmod() -> U32:
  406

def conditions_firepledge() -> U32:
  407

def conditions_firstbloodrule() -> U32:
  408

def conditions_flashfire() -> U32:
  409

def conditions_flatrules() -> U32:
  410

def conditions_flinch() -> U32:
  411

def conditions_fling() -> U32:
  412

def conditions_flippedmod() -> U32:
  413

def conditions_fly() -> U32:
  414

def conditions_focusenergy() -> U32:
  415

def conditions_focuspunch() -> U32:
  416

def conditions_followme() -> U32:
  417

def conditions_forcemonocolor() -> U32:
  418

def conditions_forcemonotype() -> U32:
  419

def conditions_forceofthefallenmod() -> U32:
  420

def conditions_forceopenteamsheets() -> U32:
  421

def conditions_forceselect() -> U32:
  422

def conditions_forceteratype() -> U32:
  423

def conditions_foresight() -> U32:
  424

def conditions_formeclause() -> U32:
  425

def conditions_franticfusionsmod() -> U32:
  426

def conditions_freezeclausemod() -> U32:
  427

def conditions_frz() -> U32:
  428

def conditions_fullarceusclause() -> U32:
  429

def conditions_furycutter() -> U32:
  430

def conditions_futuremove() -> U32:
  431

def conditions_galarexpansionpokedex() -> U32:
  432

def conditions_galarpokedex() -> U32:
  433

def conditions_gastroacid() -> U32:
  434

def conditions_gem() -> U32:
  435

def conditions_gemsclause() -> U32:
  436

def conditions_gen11v1() -> U32:
  437

def conditions_gen1challengecup() -> U32:
  438

def conditions_gen1customgame() -> U32:
  439

def conditions_gen1hackmonscup() -> U32:
  440

def conditions_gen1japaneseou() -> U32:
  441

def conditions_gen1lc() -> U32:
  442

def conditions_gen1nc1997() -> U32:
  443

def conditions_gen1nu() -> U32:
  444

def conditions_gen1ou() -> U32:
  445

def conditions_gen1pu() -> U32:
  446

def conditions_gen1randombattle() -> U32:
  447

def conditions_gen1stadiumou() -> U32:
  448

def conditions_gen1stadiumrentals() -> U32:
  449

def conditions_gen1tradebacksou() -> U32:
  450

def conditions_gen1ubers() -> U32:
  451

def conditions_gen1uu() -> U32:
  452

def conditions_gen1zu() -> U32:
  453

def conditions_gen21v1() -> U32:
  454

def conditions_gen2customgame() -> U32:
  455

def conditions_gen2nc2000() -> U32:
  456

def conditions_gen2nu() -> U32:
  457

def conditions_gen2ou() -> U32:
  458

def conditions_gen2pu() -> U32:
  459

def conditions_gen2randombattle() -> U32:
  460

def conditions_gen2stadiumou() -> U32:
  461

def conditions_gen2ubers() -> U32:
  462

def conditions_gen2uu() -> U32:
  463

def conditions_gen2uubl() -> U32:
  464

def conditions_gen2zu() -> U32:
  465

def conditions_gen31v1() -> U32:
  466

def conditions_gen3adv200() -> U32:
  467

def conditions_gen3adv200doubles() -> U32:
  468

def conditions_gen3customgame() -> U32:
  469

def conditions_gen3doublescustomgame() -> U32:
  470

def conditions_gen3doublesou() -> U32:
  471

def conditions_gen3draft() -> U32:
  472

def conditions_gen3frlgou() -> U32:
  473

def conditions_gen3hoennstadium() -> U32:
  474

def conditions_gen3lc() -> U32:
  475

def conditions_gen3nu() -> U32:
  476

def conditions_gen3orrecolosseum() -> U32:
  477

def conditions_gen3ou() -> U32:
  478

def conditions_gen3pu() -> U32:
  479

def conditions_gen3randombattle() -> U32:
  480

def conditions_gen3ru() -> U32:
  481

def conditions_gen3ubers() -> U32:
  482

def conditions_gen3uu() -> U32:
  483

def conditions_gen3uubl() -> U32:
  484

def conditions_gen3zu() -> U32:
  485

def conditions_gen41v1() -> U32:
  486

def conditions_gen4anythinggoes() -> U32:
  487

def conditions_gen4cap() -> U32:
  488

def conditions_gen4customgame() -> U32:
  489

def conditions_gen4doublescustomgame() -> U32:
  490

def conditions_gen4doublesou() -> U32:
  491

def conditions_gen4draft() -> U32:
  492

def conditions_gen4lc() -> U32:
  493

def conditions_gen4nu() -> U32:
  494

def conditions_gen4ou() -> U32:
  495

def conditions_gen4platinumou() -> U32:
  496

def conditions_gen4pu() -> U32:
  497

def conditions_gen4randombattle() -> U32:
  498

def conditions_gen4ubers() -> U32:
  499

def conditions_gen4uu() -> U32:
  500

def conditions_gen4vgc2009() -> U32:
  501

def conditions_gen4vgc2010() -> U32:
  502

def conditions_gen4zu() -> U32:
  503

def conditions_gen51v1() -> U32:
  504

def conditions_gen5bw1ou() -> U32:
  505

def conditions_gen5cap() -> U32:
  506

def conditions_gen5customgame() -> U32:
  507

def conditions_gen5doublescustomgame() -> U32:
  508

def conditions_gen5doublesou() -> U32:
  509

def conditions_gen5draft() -> U32:
  510

def conditions_gen5gbusingles() -> U32:
  511

def conditions_gen5lc() -> U32:
  512

def conditions_gen5monotype() -> U32:
  513

def conditions_gen5nu() -> U32:
  514

def conditions_gen5ou() -> U32:
  515

def conditions_gen5pu() -> U32:
  516

def conditions_gen5randombattle() -> U32:
  517

def conditions_gen5ru() -> U32:
  518

def conditions_gen5triplescustomgame() -> U32:
  519

def conditions_gen5ubers() -> U32:
  520

def conditions_gen5uu() -> U32:
  521

def conditions_gen5vgc2011() -> U32:
  522

def conditions_gen5vgc2012() -> U32:
  523

def conditions_gen5vgc2013() -> U32:
  524

def conditions_gen5zu() -> U32:
  525

def conditions_gen61v1() -> U32:
  526

def conditions_gen6anythinggoes() -> U32:
  527

def conditions_gen6battlefactory() -> U32:
  528

def conditions_gen6battlespotdoubles() -> U32:
  529

def conditions_gen6battlespotsingles() -> U32:
  530

def conditions_gen6battlespottriples() -> U32:
  531

def conditions_gen6cap() -> U32:
  532

def conditions_gen6customgame() -> U32:
  533

def conditions_gen6doublescustomgame() -> U32:
  534

def conditions_gen6doublesou() -> U32:
  535

def conditions_gen6draft() -> U32:
  536

def conditions_gen6lc() -> U32:
  537

def conditions_gen6monotype() -> U32:
  538

def conditions_gen6nu() -> U32:
  539

def conditions_gen6ou() -> U32:
  540

def conditions_gen6pu() -> U32:
  541

def conditions_gen6purehackmons() -> U32:
  542

def conditions_gen6randombattle() -> U32:
  543

def conditions_gen6ru() -> U32:
  544

def conditions_gen6triplescustomgame() -> U32:
  545

def conditions_gen6ubers() -> U32:
  546

def conditions_gen6uu() -> U32:
  547

def conditions_gen6vgc2014() -> U32:
  548

def conditions_gen6vgc2015() -> U32:
  549

def conditions_gen6vgc2016() -> U32:
  550

def conditions_gen6zu() -> U32:
  551

def conditions_gen71v1() -> U32:
  552

def conditions_gen7anythinggoes() -> U32:
  553

def conditions_gen7balancedhackmons() -> U32:
  554

def conditions_gen7battlefactory() -> U32:
  555

def conditions_gen7battlespotdoubles() -> U32:
  556

def conditions_gen7battlespotsingles() -> U32:
  557

def conditions_gen7bssfactory() -> U32:
  558

def conditions_gen7cap() -> U32:
  559

def conditions_gen7chimera1v1randombattle() -> U32:
  560

def conditions_gen7customgame() -> U32:
  561

def conditions_gen7doublescustomgame() -> U32:
  562

def conditions_gen7doublesou() -> U32:
  563

def conditions_gen7doublesuu() -> U32:
  564

def conditions_gen7draft() -> U32:
  565

def conditions_gen7hackmonscup() -> U32:
  566

def conditions_gen7lc() -> U32:
  567

def conditions_gen7letsgodoublesou() -> U32:
  568

def conditions_gen7letsgoou() -> U32:
  569

def conditions_gen7letsgorandombattle() -> U32:
  570

def conditions_gen7monotype() -> U32:
  571

def conditions_gen7nu() -> U32:
  572

def conditions_gen7ou() -> U32:
  573

def conditions_gen7pu() -> U32:
  574

def conditions_gen7purehackmons() -> U32:
  575

def conditions_gen7randombattle() -> U32:
  576

def conditions_gen7ru() -> U32:
  577

def conditions_gen7ubers() -> U32:
  578

def conditions_gen7uu() -> U32:
  579

def conditions_gen7vgc2017() -> U32:
  580

def conditions_gen7vgc2018() -> U32:
  581

def conditions_gen7vgc2019() -> U32:
  582

def conditions_gen7zu() -> U32:
  583

def conditions_gen81v1() -> U32:
  584

def conditions_gen8almostanyability() -> U32:
  585

def conditions_gen8anythinggoes() -> U32:
  586

def conditions_gen8balancedhackmons() -> U32:
  587

def conditions_gen8battlefactory() -> U32:
  588

def conditions_gen8battlestadiumsingles() -> U32:
  589

def conditions_gen8bdspbattlefestivaldoubles() -> U32:
  590

def conditions_gen8bdspdoublesou() -> U32:
  591

def conditions_gen8bdspou() -> U32:
  592

def conditions_gen8bdsprandombattle() -> U32:
  593

def conditions_gen8bdspubers() -> U32:
  594

def conditions_gen8bssfactory() -> U32:
  595

def conditions_gen8cap() -> U32:
  596

def conditions_gen8cap1v1() -> U32:
  597

def conditions_gen8customgame() -> U32:
  598

def conditions_gen8dlc1nationaldexag() -> U32:
  599

def conditions_gen8doublescustomgame() -> U32:
  600

def conditions_gen8doublesou() -> U32:
  601

def conditions_gen8doublesubers() -> U32:
  602

def conditions_gen8doublesuu() -> U32:
  603

def conditions_gen8draft() -> U32:
  604

def conditions_gen8freeforallrandombattle() -> U32:
  605

def conditions_gen8hackmonscup() -> U32:
  606

def conditions_gen8lc() -> U32:
  607

def conditions_gen8monotype() -> U32:
  608

def conditions_gen8multirandombattle() -> U32:
  609

def conditions_gen8natdex4v4doublesdraft() -> U32:
  610

def conditions_gen8natdexdraft() -> U32:
  611

def conditions_gen8nationaldex() -> U32:
  612

def conditions_gen8nationaldexdoubles() -> U32:
  613

def conditions_gen8nationaldexmonotype() -> U32:
  614

def conditions_gen8nationaldexru() -> U32:
  615

def conditions_gen8nationaldexubers() -> U32:
  616

def conditions_gen8nationaldexuu() -> U32:
  617

def conditions_gen8nu() -> U32:
  618

def conditions_gen8ou() -> U32:
  619

def conditions_gen8pu() -> U32:
  620

def conditions_gen8randombattle() -> U32:
  621

def conditions_gen8ru() -> U32:
  622

def conditions_gen8ubers() -> U32:
  623

def conditions_gen8uu() -> U32:
  624

def conditions_gen8vgc2020() -> U32:
  625

def conditions_gen8vgc2021() -> U32:
  626

def conditions_gen8vgc2022() -> U32:
  627

def conditions_gen8zu() -> U32:
  628

def conditions_gen912switch() -> U32:
  629

def conditions_gen91v1() -> U32:
  630

def conditions_gen91v1factory() -> U32:
  631

def conditions_gen92v2doubles() -> U32:
  632

def conditions_gen9350cup() -> U32:
  633

def conditions_gen94v4doublesdraft() -> U32:
  634

def conditions_gen96v6doublesdraft() -> U32:
  635

def conditions_gen9aaadoubles() -> U32:
  636

def conditions_gen9aaadraft() -> U32:
  637

def conditions_gen9aaaubers() -> U32:
  638

def conditions_gen9aaauu() -> U32:
  639

def conditions_gen9almostanyability() -> U32:
  640

def conditions_gen9alphabetcup() -> U32:
  641

def conditions_gen9anythinggoes() -> U32:
  642

def conditions_gen9babyrandombattle() -> U32:
  643

def conditions_gen9badnboosted() -> U32:
  644

def conditions_gen9balancedhackmons() -> U32:
  645

def conditions_gen9battlefactory() -> U32:
  646

def conditions_gen9battlefields() -> U32:
  647

def conditions_gen9biomechmons() -> U32:
  648

def conditions_gen9brokencup() -> U32:
  649

def conditions_gen9bssfactory() -> U32:
  650

def conditions_gen9bssregi() -> U32:
  651

def conditions_gen9camomons() -> U32:
  652

def conditions_gen9cap() -> U32:
  653

def conditions_gen9categoryswap() -> U32:
  654

def conditions_gen9challengecup1v1() -> U32:
  655

def conditions_gen9challengecup2v2() -> U32:
  656

def conditions_gen9challengecup6v6() -> U32:
  657

def conditions_gen9champions4v4doublesdraft() -> U32:
  658

def conditions_gen9champions4v4doublesuu() -> U32:
  659

def conditions_gen9championsbssregmb() -> U32:
  660

def conditions_gen9championsbssregmc() -> U32:
  661

def conditions_gen9championscustomgame() -> U32:
  662

def conditions_gen9championsdoublescustomgame() -> U32:
  663

def conditions_gen9championsdraft() -> U32:
  664

def conditions_gen9championsnatdexdraft() -> U32:
  665

def conditions_gen9championsou() -> U32:
  666

def conditions_gen9championsrandombattle() -> U32:
  667

def conditions_gen9championsrandomdoublesbattle() -> U32:
  668

def conditions_gen9championsuu() -> U32:
  669

def conditions_gen9championsvgc2026regmb() -> U32:
  670

def conditions_gen9championsvgc2026regmbbo3() -> U32:
  671

def conditions_gen9championsvgc2026regmc() -> U32:
  672

def conditions_gen9championsvgc2026regmcbo3() -> U32:
  673

def conditions_gen9chatbats() -> U32:
  674

def conditions_gen9chimera1v1randombattlebo5() -> U32:
  675

def conditions_gen9convergence() -> U32:
  676

def conditions_gen9crossevolution() -> U32:
  677

def conditions_gen9customgame() -> U32:
  678

def conditions_gen9doublescustomgame() -> U32:
  679

def conditions_gen9doubleshackmonscup() -> U32:
  680

def conditions_gen9doubleslc() -> U32:
  681

def conditions_gen9doublesou() -> U32:
  682

def conditions_gen9doublesubers() -> U32:
  683

def conditions_gen9doublesuu() -> U32:
  684

def conditions_gen9draft() -> U32:
  685

def conditions_gen9draftfactory() -> U32:
  686

def conditions_gen9ferventimpersonation() -> U32:
  687

def conditions_gen9flipped() -> U32:
  688

def conditions_gen9forceofthefallen() -> U32:
  689

def conditions_gen9foresighters() -> U32:
  690

def conditions_gen9formemons() -> U32:
  691

def conditions_gen9fortemons() -> U32:
  692

def conditions_gen9franticfusions() -> U32:
  693

def conditions_gen9freeforall() -> U32:
  694

def conditions_gen9freeforallrandombattle() -> U32:
  695

def conditions_gen9fullpotential() -> U32:
  696

def conditions_gen9godlygift() -> U32:
  697

def conditions_gen9hackmonscup() -> U32:
  698

def conditions_gen9inheritance() -> U32:
  699

def conditions_gen9inverse() -> U32:
  700

def conditions_gen9lc() -> U32:
  701

def conditions_gen9lcuu() -> U32:
  702

def conditions_gen9linked() -> U32:
  703

def conditions_gen9livepatchbattlesver100() -> U32:
  704

def conditions_gen9metronomebattle() -> U32:
  705

def conditions_gen9mixandmega() -> U32:
  706

def conditions_gen9mixandmegadoubles() -> U32:
  707

def conditions_gen9mixandmegalc() -> U32:
  708

def conditions_gen9mixandmegalimitedsupplyrandombattle() -> U32:
  709

def conditions_gen9monocolor() -> U32:
  710

def conditions_gen9monotype() -> U32:
  711

def conditions_gen9monotyperandombattle() -> U32:
  712

def conditions_gen9multirandombattle() -> U32:
  713

def conditions_gen9natdex6v6doublesdraft() -> U32:
  714

def conditions_gen9natdexcamovechaos() -> U32:
  715

def conditions_gen9natdexdraft() -> U32:
  716

def conditions_gen9natdexlcdraft() -> U32:
  717

def conditions_gen9nationaldex() -> U32:
  718

def conditions_gen9nationaldex1v1() -> U32:
  719

def conditions_gen9nationaldex35pokes() -> U32:
  720

def conditions_gen9nationaldexaaa() -> U32:
  721

def conditions_gen9nationaldexag() -> U32:
  722

def conditions_gen9nationaldexbh() -> U32:
  723

def conditions_gen9nationaldexdoubles() -> U32:
  724

def conditions_gen9nationaldexdoublesubers() -> U32:
  725

def conditions_gen9nationaldexgodlygift() -> U32:
  726

def conditions_gen9nationaldexlc() -> U32:
  727

def conditions_gen9nationaldexmixandmega() -> U32:
  728

def conditions_gen9nationaldexmonoletter() -> U32:
  729

def conditions_gen9nationaldexmonotype() -> U32:
  730

def conditions_gen9nationaldexru() -> U32:
  731

def conditions_gen9nationaldexstabmons() -> U32:
  732

def conditions_gen9nationaldexubers() -> U32:
  733

def conditions_gen9nationaldexubersunobtainableformes() -> U32:
  734

def conditions_gen9nationaldexubersuu() -> U32:
  735

def conditions_gen9nationaldexuu() -> U32:
  736

def conditions_gen9natureswap() -> U32:
  737

def conditions_gen9nfe() -> U32:
  738

def conditions_gen9noholdsbarred() -> U32:
  739

def conditions_gen9nu() -> U32:
  740

def conditions_gen9ou() -> U32:
  741

def conditions_gen9partnersincrime() -> U32:
  742

def conditions_gen9passiveaggressive() -> U32:
  743

def conditions_gen9pokebilities() -> U32:
  744

def conditions_gen9pokebilitiesaaa() -> U32:
  745

def conditions_gen9pokemoves() -> U32:
  746

def conditions_gen9pu() -> U32:
  747

def conditions_gen9purehackmons() -> U32:
  748

def conditions_gen9randombattle() -> U32:
  749

def conditions_gen9randombattleblitz() -> U32:
  750

def conditions_gen9randombattlemayhem() -> U32:
  751

def conditions_gen9randombattlesharedpowerb12p6() -> U32:
  752

def conditions_gen9randomdoublesbattle() -> U32:
  753

def conditions_gen9randomroulette() -> U32:
  754

def conditions_gen9randomtandem() -> U32:
  755

def conditions_gen9relayrace() -> U32:
  756

def conditions_gen9revelationmons() -> U32:
  757

def conditions_gen9ru() -> U32:
  758

def conditions_gen9sharedpower() -> U32:
  759

def conditions_gen9sharingiscaring() -> U32:
  760

def conditions_gen9sketchmons() -> U32:
  761

def conditions_gen9stabmons() -> U32:
  762

def conditions_gen9statmons() -> U32:
  763

def conditions_gen9superstaffbrosultimate() -> U32:
  764

def conditions_gen9teradonation() -> U32:
  765

def conditions_gen9teraoverride() -> U32:
  766

def conditions_gen9thecardgame() -> U32:
  767

def conditions_gen9thelosersgame() -> U32:
  768

def conditions_gen9tiershift() -> U32:
  769

def conditions_gen9trademarked() -> U32:
  770

def conditions_gen9triples() -> U32:
  771

def conditions_gen9typesplit() -> U32:
  772

def conditions_gen9ubers() -> U32:
  773

def conditions_gen9ubersuu() -> U32:
  774

def conditions_gen9unratedrandombattle() -> U32:
  775

def conditions_gen9uu() -> U32:
  776

def conditions_gen9vgc2023regc() -> U32:
  777

def conditions_gen9vgc2023regd() -> U32:
  778

def conditions_gen9vgc2024regg() -> U32:
  779

def conditions_gen9vgc2025regi() -> U32:
  780

def conditions_gen9voltturnmayhem() -> U32:
  781

def conditions_gen9zu() -> U32:
  782

def conditions_glaiverush() -> U32:
  783

def conditions_gmaxcannonade() -> U32:
  784

def conditions_gmaxchistrike() -> U32:
  785

def conditions_gmaxsteelsurge() -> U32:
  786

def conditions_gmaxvinelash() -> U32:
  787

def conditions_gmaxvolcalith() -> U32:
  788

def conditions_gmaxwildfire() -> U32:
  789

def conditions_godlygiftmod() -> U32:
  790

def conditions_grasspledge() -> U32:
  791

def conditions_grassyterrain() -> U32:
  792

def conditions_gravity() -> U32:
  793

def conditions_gravitysleepclause() -> U32:
  794

def conditions_grudge() -> U32:
  795

def conditions_guaranteedsecondarymod() -> U32:
  796

def conditions_hackmonsformelegality() -> U32:
  797

def conditions_hail() -> U32:
  798

def conditions_healblock() -> U32:
  799

def conditions_healingwish() -> U32:
  800

def conditions_healreplacement() -> U32:
  801

def conditions_helpinghand() -> U32:
  802

def conditions_hoennpokedex() -> U32:
  803

def conditions_hppercentagemod() -> U32:
  804

def conditions_iceball() -> U32:
  805

def conditions_illusionlevelmod() -> U32:
  806

def conditions_imprison() -> U32:
  807

def conditions_ingrain() -> U32:
  808

def conditions_inversemod() -> U32:
  809

def conditions_iondeluge() -> U32:
  810

def conditions_isleofarmorpokedex() -> U32:
  811

def conditions_item_abilityshield() -> U32:
  812

def conditions_item_abomasite() -> U32:
  813

def conditions_item_absolite() -> U32:
  814

def conditions_item_absolitez() -> U32:
  815

def conditions_item_absorbbulb() -> U32:
  816

def conditions_item_adamantcrystal() -> U32:
  817

def conditions_item_adamantorb() -> U32:
  818

def conditions_item_adrenalineorb() -> U32:
  819

def conditions_item_aerodactylite() -> U32:
  820

def conditions_item_aggronite() -> U32:
  821

def conditions_item_aguavberry() -> U32:
  822

def conditions_item_airballoon() -> U32:
  823

def conditions_item_alakazite() -> U32:
  824

def conditions_item_aloraichiumz() -> U32:
  825

def conditions_item_altarianite() -> U32:
  826

def conditions_item_ampharosite() -> U32:
  827

def conditions_item_apicotberry() -> U32:
  828

def conditions_item_armorfossil() -> U32:
  829

def conditions_item_aspearberry() -> U32:
  830

def conditions_item_assaultvest() -> U32:
  831

def conditions_item_audinite() -> U32:
  832

def conditions_item_auspiciousarmor() -> U32:
  833

def conditions_item_babiriberry() -> U32:
  834

def conditions_item_banettite() -> U32:
  835

def conditions_item_barbaracite() -> U32:
  836

def conditions_item_baxcalibrite() -> U32:
  837

def conditions_item_beastball() -> U32:
  838

def conditions_item_beedrillite() -> U32:
  839

def conditions_item_belueberry() -> U32:
  840

def conditions_item_berry() -> U32:
  841

def conditions_item_berryjuice() -> U32:
  842

def conditions_item_berrysweet() -> U32:
  843

def conditions_item_berserkgene() -> U32:
  844

def conditions_item_bignugget() -> U32:
  845

def conditions_item_bigroot() -> U32:
  846

def conditions_item_bindingband() -> U32:
  847

def conditions_item_bitterberry() -> U32:
  848

def conditions_item_blackbelt() -> U32:
  849

def conditions_item_blackglasses() -> U32:
  850

def conditions_item_blacksludge() -> U32:
  851

def conditions_item_blastoisinite() -> U32:
  852

def conditions_item_blazikenite() -> U32:
  853

def conditions_item_blueorb() -> U32:
  854

def conditions_item_blukberry() -> U32:
  855

def conditions_item_blunderpolicy() -> U32:
  856

def conditions_item_boosterenergy() -> U32:
  857

def conditions_item_bottlecap() -> U32:
  858

def conditions_item_brightpowder() -> U32:
  859

def conditions_item_buggem() -> U32:
  860

def conditions_item_buginiumz() -> U32:
  861

def conditions_item_bugmemory() -> U32:
  862

def conditions_item_burndrive() -> U32:
  863

def conditions_item_burntberry() -> U32:
  864

def conditions_item_cameruptite() -> U32:
  865

def conditions_item_cellbattery() -> U32:
  866

def conditions_item_chandelurite() -> U32:
  867

def conditions_item_charcoal() -> U32:
  868

def conditions_item_charizarditex() -> U32:
  869

def conditions_item_charizarditey() -> U32:
  870

def conditions_item_chartiberry() -> U32:
  871

def conditions_item_cheriberry() -> U32:
  872

def conditions_item_cherishball() -> U32:
  873

def conditions_item_chesnaughtite() -> U32:
  874

def conditions_item_chestoberry() -> U32:
  875

def conditions_item_chilanberry() -> U32:
  876

def conditions_item_chilldrive() -> U32:
  877

def conditions_item_chimechite() -> U32:
  878

def conditions_item_chippedpot() -> U32:
  879

def conditions_item_choiceband() -> U32:
  880

def conditions_item_choicescarf() -> U32:
  881

def conditions_item_choicespecs() -> U32:
  882

def conditions_item_chopleberry() -> U32:
  883

def conditions_item_clawfossil() -> U32:
  884

def conditions_item_clearamulet() -> U32:
  885

def conditions_item_clefablite() -> U32:
  886

def conditions_item_cloversweet() -> U32:
  887

def conditions_item_cobaberry() -> U32:
  888

def conditions_item_colburberry() -> U32:
  889

def conditions_item_cornerstonemask() -> U32:
  890

def conditions_item_cornnberry() -> U32:
  891

def conditions_item_coverfossil() -> U32:
  892

def conditions_item_covertcloak() -> U32:
  893

def conditions_item_crabominite() -> U32:
  894

def conditions_item_crackedpot() -> U32:
  895

def conditions_item_crucibellite() -> U32:
  896

def conditions_item_custapberry() -> U32:
  897

def conditions_item_damprock() -> U32:
  898

def conditions_item_darkgem() -> U32:
  899

def conditions_item_darkiniumz() -> U32:
  900

def conditions_item_darkmemory() -> U32:
  901

def conditions_item_darkranite() -> U32:
  902

def conditions_item_dawnstone() -> U32:
  903

def conditions_item_decidiumz() -> U32:
  904

def conditions_item_deepseascale() -> U32:
  905

def conditions_item_deepseatooth() -> U32:
  906

def conditions_item_delphoxite() -> U32:
  907

def conditions_item_destinyknot() -> U32:
  908

def conditions_item_diancite() -> U32:
  909

def conditions_item_diveball() -> U32:
  910

def conditions_item_domefossil() -> U32:
  911

def conditions_item_dousedrive() -> U32:
  912

def conditions_item_dracoplate() -> U32:
  913

def conditions_item_dragalgite() -> U32:
  914

def conditions_item_dragonfang() -> U32:
  915

def conditions_item_dragongem() -> U32:
  916

def conditions_item_dragoninite() -> U32:
  917

def conditions_item_dragoniumz() -> U32:
  918

def conditions_item_dragonmemory() -> U32:
  919

def conditions_item_dragonscale() -> U32:
  920

def conditions_item_drampanite() -> U32:
  921

def conditions_item_dreadplate() -> U32:
  922

def conditions_item_dreamball() -> U32:
  923

def conditions_item_dubiousdisc() -> U32:
  924

def conditions_item_durinberry() -> U32:
  925

def conditions_item_duskball() -> U32:
  926

def conditions_item_duskstone() -> U32:
  927

def conditions_item_earthplate() -> U32:
  928

def conditions_item_eelektrossite() -> U32:
  929

def conditions_item_eeviumz() -> U32:
  930

def conditions_item_ejectbutton() -> U32:
  931

def conditions_item_ejectpack() -> U32:
  932

def conditions_item_electirizer() -> U32:
  933

def conditions_item_electricgem() -> U32:
  934

def conditions_item_electricmemory() -> U32:
  935

def conditions_item_electricseed() -> U32:
  936

def conditions_item_electriumz() -> U32:
  937

def conditions_item_emboarite() -> U32:
  938

def conditions_item_enigmaberry() -> U32:
  939

def conditions_item_eviolite() -> U32:
  940

def conditions_item_excadrite() -> U32:
  941

def conditions_item_expertbelt() -> U32:
  942

def conditions_item_fairiumz() -> U32:
  943

def conditions_item_fairyfeather() -> U32:
  944

def conditions_item_fairygem() -> U32:
  945

def conditions_item_fairymemory() -> U32:
  946

def conditions_item_falinksite() -> U32:
  947

def conditions_item_fastball() -> U32:
  948

def conditions_item_feraligite() -> U32:
  949

def conditions_item_fightinggem() -> U32:
  950

def conditions_item_fightingmemory() -> U32:
  951

def conditions_item_fightiniumz() -> U32:
  952

def conditions_item_figyberry() -> U32:
  953

def conditions_item_firegem() -> U32:
  954

def conditions_item_firememory() -> U32:
  955

def conditions_item_firestone() -> U32:
  956

def conditions_item_firiumz() -> U32:
  957

def conditions_item_fistplate() -> U32:
  958

def conditions_item_flameorb() -> U32:
  959

def conditions_item_flameplate() -> U32:
  960

def conditions_item_floatstone() -> U32:
  961

def conditions_item_floettite() -> U32:
  962

def conditions_item_flowersweet() -> U32:
  963

def conditions_item_flyinggem() -> U32:
  964

def conditions_item_flyingmemory() -> U32:
  965

def conditions_item_flyiniumz() -> U32:
  966

def conditions_item_focusband() -> U32:
  967

def conditions_item_focussash() -> U32:
  968

def conditions_item_fossilizedbird() -> U32:
  969

def conditions_item_fossilizeddino() -> U32:
  970

def conditions_item_fossilizeddrake() -> U32:
  971

def conditions_item_fossilizedfish() -> U32:
  972

def conditions_item_friendball() -> U32:
  973

def conditions_item_froslassite() -> U32:
  974

def conditions_item_fullincense() -> U32:
  975

def conditions_item_galaricacuff() -> U32:
  976

def conditions_item_galaricawreath() -> U32:
  977

def conditions_item_galladite() -> U32:
  978

def conditions_item_ganlonberry() -> U32:
  979

def conditions_item_garchompite() -> U32:
  980

def conditions_item_garchompitez() -> U32:
  981

def conditions_item_gardevoirite() -> U32:
  982

def conditions_item_gengarite() -> U32:
  983

def conditions_item_ghostgem() -> U32:
  984

def conditions_item_ghostiumz() -> U32:
  985

def conditions_item_ghostmemory() -> U32:
  986

def conditions_item_glalitite() -> U32:
  987

def conditions_item_glimmoranite() -> U32:
  988

def conditions_item_goldberry() -> U32:
  989

def conditions_item_goldbottlecap() -> U32:
  990

def conditions_item_golisopite() -> U32:
  991

def conditions_item_golurkite() -> U32:
  992

def conditions_item_grassgem() -> U32:
  993

def conditions_item_grassiumz() -> U32:
  994

def conditions_item_grassmemory() -> U32:
  995

def conditions_item_grassyseed() -> U32:
  996

def conditions_item_greatball() -> U32:
  997

def conditions_item_greninjite() -> U32:
  998

def conditions_item_grepaberry() -> U32:
  999

def conditions_item_gripclaw() -> U32:
  1000

def conditions_item_griseouscore() -> U32:
  1001

def conditions_item_griseousorb() -> U32:
  1002

def conditions_item_groundgem() -> U32:
  1003

def conditions_item_groundiumz() -> U32:
  1004

def conditions_item_groundmemory() -> U32:
  1005

def conditions_item_gyaradosite() -> U32:
  1006

def conditions_item_habanberry() -> U32:
  1007

def conditions_item_hardstone() -> U32:
  1008

def conditions_item_hawluchanite() -> U32:
  1009

def conditions_item_healball() -> U32:
  1010

def conditions_item_hearthflamemask() -> U32:
  1011

def conditions_item_heatranite() -> U32:
  1012

def conditions_item_heatrock() -> U32:
  1013

def conditions_item_heavyball() -> U32:
  1014

def conditions_item_heavydutyboots() -> U32:
  1015

def conditions_item_helixfossil() -> U32:
  1016

def conditions_item_heracronite() -> U32:
  1017

def conditions_item_hondewberry() -> U32:
  1018

def conditions_item_houndoominite() -> U32:
  1019

def conditions_item_iapapaberry() -> U32:
  1020

def conditions_item_iceberry() -> U32:
  1021

def conditions_item_icegem() -> U32:
  1022

def conditions_item_icememory() -> U32:
  1023

def conditions_item_icestone() -> U32:
  1024

def conditions_item_icicleplate() -> U32:
  1025

def conditions_item_iciumz() -> U32:
  1026

def conditions_item_icyrock() -> U32:
  1027

def conditions_item_inciniumz() -> U32:
  1028

def conditions_item_insectplate() -> U32:
  1029

def conditions_item_ironball() -> U32:
  1030

def conditions_item_ironplate() -> U32:
  1031

def conditions_item_jabocaberry() -> U32:
  1032

def conditions_item_jawfossil() -> U32:
  1033

def conditions_item_kangaskhanite() -> U32:
  1034

def conditions_item_kasibberry() -> U32:
  1035

def conditions_item_kebiaberry() -> U32:
  1036

def conditions_item_keeberry() -> U32:
  1037

def conditions_item_kelpsyberry() -> U32:
  1038

def conditions_item_kingsrock() -> U32:
  1039

def conditions_item_kommoniumz() -> U32:
  1040

def conditions_item_laggingtail() -> U32:
  1041

def conditions_item_lansatberry() -> U32:
  1042

def conditions_item_latiasite() -> U32:
  1043

def conditions_item_latiosite() -> U32:
  1044

def conditions_item_laxincense() -> U32:
  1045

def conditions_item_leafstone() -> U32:
  1046

def conditions_item_leek() -> U32:
  1047

def conditions_item_leftovers() -> U32:
  1048

def conditions_item_leppaberry() -> U32:
  1049

def conditions_item_levelball() -> U32:
  1050

def conditions_item_liechiberry() -> U32:
  1051

def conditions_item_lifeorb() -> U32:
  1052

def conditions_item_lightball() -> U32:
  1053

def conditions_item_lightclay() -> U32:
  1054

def conditions_item_loadeddice() -> U32:
  1055

def conditions_item_lopunnite() -> U32:
  1056

def conditions_item_loveball() -> U32:
  1057

def conditions_item_lovesweet() -> U32:
  1058

def conditions_item_lucarionite() -> U32:
  1059

def conditions_item_lucarionitez() -> U32:
  1060

def conditions_item_luckypunch() -> U32:
  1061

def conditions_item_lumberry() -> U32:
  1062

def conditions_item_luminousmoss() -> U32:
  1063

def conditions_item_lunaliumz() -> U32:
  1064

def conditions_item_lureball() -> U32:
  1065

def conditions_item_lustrousglobe() -> U32:
  1066

def conditions_item_lustrousorb() -> U32:
  1067

def conditions_item_luxuryball() -> U32:
  1068

def conditions_item_lycaniumz() -> U32:
  1069

def conditions_item_machobrace() -> U32:
  1070

def conditions_item_magearnite() -> U32:
  1071

def conditions_item_magmarizer() -> U32:
  1072

def conditions_item_magnet() -> U32:
  1073

def conditions_item_magoberry() -> U32:
  1074

def conditions_item_magostberry() -> U32:
  1075

def conditions_item_mail() -> U32:
  1076

def conditions_item_malamarite() -> U32:
  1077

def conditions_item_maliciousarmor() -> U32:
  1078

def conditions_item_manectite() -> U32:
  1079

def conditions_item_marangaberry() -> U32:
  1080

def conditions_item_marshadiumz() -> U32:
  1081

def conditions_item_masterball() -> U32:
  1082

def conditions_item_masterpieceteacup() -> U32:
  1083

def conditions_item_mawilite() -> U32:
  1084

def conditions_item_meadowplate() -> U32:
  1085

def conditions_item_medichamite() -> U32:
  1086

def conditions_item_meganiumite() -> U32:
  1087

def conditions_item_mentalherb() -> U32:
  1088

def conditions_item_meowsticite() -> U32:
  1089

def conditions_item_metagrossite() -> U32:
  1090

def conditions_item_metalalloy() -> U32:
  1091

def conditions_item_metalcoat() -> U32:
  1092

def conditions_item_metalpowder() -> U32:
  1093

def conditions_item_metronome() -> U32:
  1094

def conditions_item_mewniumz() -> U32:
  1095

def conditions_item_mewtwonitex() -> U32:
  1096

def conditions_item_mewtwonitey() -> U32:
  1097

def conditions_item_micleberry() -> U32:
  1098

def conditions_item_mimikiumz() -> U32:
  1099

def conditions_item_mindplate() -> U32:
  1100

def conditions_item_mintberry() -> U32:
  1101

def conditions_item_miracleberry() -> U32:
  1102

def conditions_item_miracleseed() -> U32:
  1103

def conditions_item_mirrorherb() -> U32:
  1104

def conditions_item_mistyseed() -> U32:
  1105

def conditions_item_moonball() -> U32:
  1106

def conditions_item_moonstone() -> U32:
  1107

def conditions_item_muscleband() -> U32:
  1108

def conditions_item_mysteryberry() -> U32:
  1109

def conditions_item_mysticwater() -> U32:
  1110

def conditions_item_nanabberry() -> U32:
  1111

def conditions_item_nestball() -> U32:
  1112

def conditions_item_netball() -> U32:
  1113

def conditions_item_nevermeltice() -> U32:
  1114

def conditions_item_nomelberry() -> U32:
  1115

def conditions_item_normalgem() -> U32:
  1116

def conditions_item_normaliumz() -> U32:
  1117

def conditions_item_occaberry() -> U32:
  1118

def conditions_item_oddincense() -> U32:
  1119

def conditions_item_oldamber() -> U32:
  1120

def conditions_item_oranberry() -> U32:
  1121

def conditions_item_ovalstone() -> U32:
  1122

def conditions_item_pamtreberry() -> U32:
  1123

def conditions_item_parkball() -> U32:
  1124

def conditions_item_passhoberry() -> U32:
  1125

def conditions_item_payapaberry() -> U32:
  1126

def conditions_item_pechaberry() -> U32:
  1127

def conditions_item_persimberry() -> U32:
  1128

def conditions_item_petayaberry() -> U32:
  1129

def conditions_item_pidgeotite() -> U32:
  1130

def conditions_item_pikaniumz() -> U32:
  1131

def conditions_item_pikashuniumz() -> U32:
  1132

def conditions_item_pinapberry() -> U32:
  1133

def conditions_item_pinkbow() -> U32:
  1134

def conditions_item_pinsirite() -> U32:
  1135

def conditions_item_pixieplate() -> U32:
  1136

def conditions_item_plumefossil() -> U32:
  1137

def conditions_item_poisonbarb() -> U32:
  1138

def conditions_item_poisongem() -> U32:
  1139

def conditions_item_poisoniumz() -> U32:
  1140

def conditions_item_poisonmemory() -> U32:
  1141

def conditions_item_pokeball() -> U32:
  1142

def conditions_item_polkadotbow() -> U32:
  1143

def conditions_item_pomegberry() -> U32:
  1144

def conditions_item_poweranklet() -> U32:
  1145

def conditions_item_powerband() -> U32:
  1146

def conditions_item_powerbelt() -> U32:
  1147

def conditions_item_powerbracer() -> U32:
  1148

def conditions_item_powerherb() -> U32:
  1149

def conditions_item_powerlens() -> U32:
  1150

def conditions_item_powerweight() -> U32:
  1151

def conditions_item_premierball() -> U32:
  1152

def conditions_item_prettyfeather() -> U32:
  1153

def conditions_item_primariumz() -> U32:
  1154

def conditions_item_prismscale() -> U32:
  1155

def conditions_item_protectivepads() -> U32:
  1156

def conditions_item_protector() -> U32:
  1157

def conditions_item_przcureberry() -> U32:
  1158

def conditions_item_psncureberry() -> U32:
  1159

def conditions_item_psychicgem() -> U32:
  1160

def conditions_item_psychicmemory() -> U32:
  1161

def conditions_item_psychicseed() -> U32:
  1162

def conditions_item_psychiumz() -> U32:
  1163

def conditions_item_punchingglove() -> U32:
  1164

def conditions_item_pyroarite() -> U32:
  1165

def conditions_item_qualotberry() -> U32:
  1166

def conditions_item_quickball() -> U32:
  1167

def conditions_item_quickclaw() -> U32:
  1168

def conditions_item_quickpowder() -> U32:
  1169

def conditions_item_rabutaberry() -> U32:
  1170

def conditions_item_raichunitex() -> U32:
  1171

def conditions_item_raichunitey() -> U32:
  1172

def conditions_item_rarebone() -> U32:
  1173

def conditions_item_rawstberry() -> U32:
  1174

def conditions_item_razorclaw() -> U32:
  1175

def conditions_item_razorfang() -> U32:
  1176

def conditions_item_razzberry() -> U32:
  1177

def conditions_item_reapercloth() -> U32:
  1178

def conditions_item_redcard() -> U32:
  1179

def conditions_item_redorb() -> U32:
  1180

def conditions_item_repeatball() -> U32:
  1181

def conditions_item_ribbonsweet() -> U32:
  1182

def conditions_item_rindoberry() -> U32:
  1183

def conditions_item_ringtarget() -> U32:
  1184

def conditions_item_rockgem() -> U32:
  1185

def conditions_item_rockincense() -> U32:
  1186

def conditions_item_rockiumz() -> U32:
  1187

def conditions_item_rockmemory() -> U32:
  1188

def conditions_item_rockyhelmet() -> U32:
  1189

def conditions_item_roomservice() -> U32:
  1190

def conditions_item_rootfossil() -> U32:
  1191

def conditions_item_roseincense() -> U32:
  1192

def conditions_item_roseliberry() -> U32:
  1193

def conditions_item_rowapberry() -> U32:
  1194

def conditions_item_rustedshield() -> U32:
  1195

def conditions_item_rustedsword() -> U32:
  1196

def conditions_item_sablenite() -> U32:
  1197

def conditions_item_sachet() -> U32:
  1198

def conditions_item_safariball() -> U32:
  1199

def conditions_item_safetygoggles() -> U32:
  1200

def conditions_item_sailfossil() -> U32:
  1201

def conditions_item_salacberry() -> U32:
  1202

def conditions_item_salamencite() -> U32:
  1203

def conditions_item_sceptilite() -> U32:
  1204

def conditions_item_scizorite() -> U32:
  1205

def conditions_item_scolipite() -> U32:
  1206

def conditions_item_scopelens() -> U32:
  1207

def conditions_item_scovillainite() -> U32:
  1208

def conditions_item_scraftinite() -> U32:
  1209

def conditions_item_seaincense() -> U32:
  1210

def conditions_item_sharpbeak() -> U32:
  1211

def conditions_item_sharpedonite() -> U32:
  1212

def conditions_item_shedshell() -> U32:
  1213

def conditions_item_shellbell() -> U32:
  1214

def conditions_item_shinystone() -> U32:
  1215

def conditions_item_shockdrive() -> U32:
  1216

def conditions_item_shucaberry() -> U32:
  1217

def conditions_item_silkscarf() -> U32:
  1218

def conditions_item_silverpowder() -> U32:
  1219

def conditions_item_sitrusberry() -> U32:
  1220

def conditions_item_skarmorite() -> U32:
  1221

def conditions_item_skullfossil() -> U32:
  1222

def conditions_item_skyplate() -> U32:
  1223

def conditions_item_slowbronite() -> U32:
  1224

def conditions_item_smoothrock() -> U32:
  1225

def conditions_item_snorliumz() -> U32:
  1226

def conditions_item_snowball() -> U32:
  1227

def conditions_item_softsand() -> U32:
  1228

def conditions_item_solganiumz() -> U32:
  1229

def conditions_item_souldew() -> U32:
  1230

def conditions_item_spelltag() -> U32:
  1231

def conditions_item_spelonberry() -> U32:
  1232

def conditions_item_splashplate() -> U32:
  1233

def conditions_item_spookyplate() -> U32:
  1234

def conditions_item_sportball() -> U32:
  1235

def conditions_item_staraptite() -> U32:
  1236

def conditions_item_starfberry() -> U32:
  1237

def conditions_item_starminite() -> U32:
  1238

def conditions_item_starsweet() -> U32:
  1239

def conditions_item_steelgem() -> U32:
  1240

def conditions_item_steeliumz() -> U32:
  1241

def conditions_item_steelixite() -> U32:
  1242

def conditions_item_steelmemory() -> U32:
  1243

def conditions_item_stick() -> U32:
  1244

def conditions_item_stickybarb() -> U32:
  1245

def conditions_item_stoneplate() -> U32:
  1246

def conditions_item_strangeball() -> U32:
  1247

def conditions_item_strawberrysweet() -> U32:
  1248

def conditions_item_sunstone() -> U32:
  1249

def conditions_item_swampertite() -> U32:
  1250

def conditions_item_sweetapple() -> U32:
  1251

def conditions_item_syrupyapple() -> U32:
  1252

def conditions_item_tamatoberry() -> U32:
  1253

def conditions_item_tangaberry() -> U32:
  1254

def conditions_item_tapuniumz() -> U32:
  1255

def conditions_item_tartapple() -> U32:
  1256

def conditions_item_tatsugirinite() -> U32:
  1257

def conditions_item_terrainextender() -> U32:
  1258

def conditions_item_thickclub() -> U32:
  1259

def conditions_item_throatspray() -> U32:
  1260

def conditions_item_thunderstone() -> U32:
  1261

def conditions_item_timerball() -> U32:
  1262

def conditions_item_toxicorb() -> U32:
  1263

def conditions_item_toxicplate() -> U32:
  1264

def conditions_item_tr00() -> U32:
  1265

def conditions_item_tr01() -> U32:
  1266

def conditions_item_tr02() -> U32:
  1267

def conditions_item_tr03() -> U32:
  1268

def conditions_item_tr04() -> U32:
  1269

def conditions_item_tr05() -> U32:
  1270

def conditions_item_tr06() -> U32:
  1271

def conditions_item_tr07() -> U32:
  1272

def conditions_item_tr08() -> U32:
  1273

def conditions_item_tr09() -> U32:
  1274

def conditions_item_tr10() -> U32:
  1275

def conditions_item_tr11() -> U32:
  1276

def conditions_item_tr12() -> U32:
  1277

def conditions_item_tr13() -> U32:
  1278

def conditions_item_tr14() -> U32:
  1279

def conditions_item_tr15() -> U32:
  1280

def conditions_item_tr16() -> U32:
  1281

def conditions_item_tr17() -> U32:
  1282

def conditions_item_tr18() -> U32:
  1283

def conditions_item_tr19() -> U32:
  1284

def conditions_item_tr20() -> U32:
  1285

def conditions_item_tr21() -> U32:
  1286

def conditions_item_tr22() -> U32:
  1287

def conditions_item_tr23() -> U32:
  1288

def conditions_item_tr24() -> U32:
  1289

def conditions_item_tr25() -> U32:
  1290

def conditions_item_tr26() -> U32:
  1291

def conditions_item_tr27() -> U32:
  1292

def conditions_item_tr28() -> U32:
  1293

def conditions_item_tr29() -> U32:
  1294

def conditions_item_tr30() -> U32:
  1295

def conditions_item_tr31() -> U32:
  1296

def conditions_item_tr32() -> U32:
  1297

def conditions_item_tr33() -> U32:
  1298

def conditions_item_tr34() -> U32:
  1299

def conditions_item_tr35() -> U32:
  1300

def conditions_item_tr36() -> U32:
  1301

def conditions_item_tr37() -> U32:
  1302

def conditions_item_tr38() -> U32:
  1303

def conditions_item_tr39() -> U32:
  1304

def conditions_item_tr40() -> U32:
  1305

def conditions_item_tr41() -> U32:
  1306

def conditions_item_tr42() -> U32:
  1307

def conditions_item_tr43() -> U32:
  1308

def conditions_item_tr44() -> U32:
  1309

def conditions_item_tr45() -> U32:
  1310

def conditions_item_tr46() -> U32:
  1311

def conditions_item_tr47() -> U32:
  1312

def conditions_item_tr48() -> U32:
  1313

def conditions_item_tr49() -> U32:
  1314

def conditions_item_tr50() -> U32:
  1315

def conditions_item_tr51() -> U32:
  1316

def conditions_item_tr52() -> U32:
  1317

def conditions_item_tr53() -> U32:
  1318

def conditions_item_tr54() -> U32:
  1319

def conditions_item_tr55() -> U32:
  1320

def conditions_item_tr56() -> U32:
  1321

def conditions_item_tr57() -> U32:
  1322

def conditions_item_tr58() -> U32:
  1323

def conditions_item_tr59() -> U32:
  1324

def conditions_item_tr60() -> U32:
  1325

def conditions_item_tr61() -> U32:
  1326

def conditions_item_tr62() -> U32:
  1327

def conditions_item_tr63() -> U32:
  1328

def conditions_item_tr64() -> U32:
  1329

def conditions_item_tr65() -> U32:
  1330

def conditions_item_tr66() -> U32:
  1331

def conditions_item_tr67() -> U32:
  1332

def conditions_item_tr68() -> U32:
  1333

def conditions_item_tr69() -> U32:
  1334

def conditions_item_tr70() -> U32:
  1335

def conditions_item_tr71() -> U32:
  1336

def conditions_item_tr72() -> U32:
  1337

def conditions_item_tr73() -> U32:
  1338

def conditions_item_tr74() -> U32:
  1339

def conditions_item_tr75() -> U32:
  1340

def conditions_item_tr76() -> U32:
  1341

def conditions_item_tr77() -> U32:
  1342

def conditions_item_tr78() -> U32:
  1343

def conditions_item_tr79() -> U32:
  1344

def conditions_item_tr80() -> U32:
  1345

def conditions_item_tr81() -> U32:
  1346

def conditions_item_tr82() -> U32:
  1347

def conditions_item_tr83() -> U32:
  1348

def conditions_item_tr84() -> U32:
  1349

def conditions_item_tr85() -> U32:
  1350

def conditions_item_tr86() -> U32:
  1351

def conditions_item_tr87() -> U32:
  1352

def conditions_item_tr88() -> U32:
  1353

def conditions_item_tr89() -> U32:
  1354

def conditions_item_tr90() -> U32:
  1355

def conditions_item_tr91() -> U32:
  1356

def conditions_item_tr92() -> U32:
  1357

def conditions_item_tr93() -> U32:
  1358

def conditions_item_tr94() -> U32:
  1359

def conditions_item_tr95() -> U32:
  1360

def conditions_item_tr96() -> U32:
  1361

def conditions_item_tr97() -> U32:
  1362

def conditions_item_tr98() -> U32:
  1363

def conditions_item_tr99() -> U32:
  1364

def conditions_item_twistedspoon() -> U32:
  1365

def conditions_item_tyranitarite() -> U32:
  1366

def conditions_item_ultraball() -> U32:
  1367

def conditions_item_ultranecroziumz() -> U32:
  1368

def conditions_item_unremarkableteacup() -> U32:
  1369

def conditions_item_upgrade() -> U32:
  1370

def conditions_item_utilityumbrella() -> U32:
  1371

def conditions_item_venusaurite() -> U32:
  1372

def conditions_item_victreebelite() -> U32:
  1373

def conditions_item_vilevial() -> U32:
  1374

def conditions_item_wacanberry() -> U32:
  1375

def conditions_item_watergem() -> U32:
  1376

def conditions_item_wateriumz() -> U32:
  1377

def conditions_item_watermemory() -> U32:
  1378

def conditions_item_waterstone() -> U32:
  1379

def conditions_item_watmelberry() -> U32:
  1380

def conditions_item_waveincense() -> U32:
  1381

def conditions_item_weaknesspolicy() -> U32:
  1382

def conditions_item_wellspringmask() -> U32:
  1383

def conditions_item_wepearberry() -> U32:
  1384

def conditions_item_whippeddream() -> U32:
  1385

def conditions_item_whiteherb() -> U32:
  1386

def conditions_item_widelens() -> U32:
  1387

def conditions_item_wikiberry() -> U32:
  1388

def conditions_item_wiseglasses() -> U32:
  1389

def conditions_item_yacheberry() -> U32:
  1390

def conditions_item_zapplate() -> U32:
  1391

def conditions_item_zeraorite() -> U32:
  1392

def conditions_item_zoomlens() -> U32:
  1393

def conditions_item_zygardite() -> U32:
  1394

def conditions_itemclause() -> U32:
  1395

def conditions_kalospokedex() -> U32:
  1396

def conditions_kingsshield() -> U32:
  1397

def conditions_kitakamipokedex() -> U32:
  1398

def conditions_laserfocus() -> U32:
  1399

def conditions_leechseed() -> U32:
  1400

def conditions_lgpenormalrules() -> U32:
  1401

def conditions_lightscreen() -> U32:
  1402

def conditions_limitonerestricted() -> U32:
  1403

def conditions_limittworestricted() -> U32:
  1404

def conditions_littlecup() -> U32:
  1405

def conditions_lockedmove() -> U32:
  1406

def conditions_lockon() -> U32:
  1407

def conditions_luckychant() -> U32:
  1408

def conditions_lunardance() -> U32:
  1409

def conditions_magiccoat() -> U32:
  1410

def conditions_magicroom() -> U32:
  1411

def conditions_magnetrise() -> U32:
  1412

def conditions_matblock() -> U32:
  1413

def conditions_maxguard() -> U32:
  1414

def conditions_maxlevel() -> U32:
  1415

def conditions_maxmovecount() -> U32:
  1416

def conditions_maxteamsize() -> U32:
  1417

def conditions_maxtotallevel() -> U32:
  1418

def conditions_mefirst() -> U32:
  1419

def conditions_megarayquazaclause() -> U32:
  1420

def conditions_metronome() -> U32:
  1421

def conditions_micleberry() -> U32:
  1422

def conditions_mimicglitchclause() -> U32:
  1423

def conditions_minimize() -> U32:
  1424

def conditions_minlevel() -> U32:
  1425

def conditions_minsourcegen() -> U32:
  1426

def conditions_minteamsize() -> U32:
  1427

def conditions_miracleeye() -> U32:
  1428

def conditions_mirrorcoat() -> U32:
  1429

def conditions_mist() -> U32:
  1430

def conditions_mistyterrain() -> U32:
  1431

def conditions_mixandmegaoldaggronite() -> U32:
  1432

def conditions_mudsport() -> U32:
  1433

def conditions_mustrecharge() -> U32:
  1434

def conditions_natdexmod() -> U32:
  1435

def conditions_nc1997movelegality() -> U32:
  1436

def conditions_nc2000movelegality() -> U32:
  1437

def conditions_newalolapokedex() -> U32:
  1438

def conditions_newunovapokedex() -> U32:
  1439

def conditions_nfeclause() -> U32:
  1440

def conditions_nicknameclause() -> U32:
  1441

def conditions_nightmare() -> U32:
  1442

def conditions_nofreezemod() -> U32:
  1443

def conditions_noretreat() -> U32:
  1444

def conditions_noswitching() -> U32:
  1445

def conditions_notfullyevolved() -> U32:
  1446

def conditions_obstruct() -> U32:
  1447

def conditions_obtainable() -> U32:
  1448

def conditions_obtainableabilities() -> U32:
  1449

def conditions_obtainableformes() -> U32:
  1450

def conditions_obtainablemisc() -> U32:
  1451

def conditions_obtainablemoves() -> U32:
  1452

def conditions_octolock() -> U32:
  1453

def conditions_ohkoclause() -> U32:
  1454

def conditions_oldalolapokedex() -> U32:
  1455

def conditions_oldunovapokedex() -> U32:
  1456

def conditions_omunobtainablemoves() -> U32:
  1457

def conditions_onebatonpassclause() -> U32:
  1458

def conditions_oneboostpasserclause() -> U32:
  1459

def conditions_onevsone() -> U32:
  1460

def conditions_openteamsheets() -> U32:
  1461

def conditions_overflowstatmod() -> U32:
  1462

def conditions_paldeapokedex() -> U32:
  1463

def conditions_par() -> U32:
  1464

def conditions_partiallytrapped() -> U32:
  1465

def conditions_perishsong() -> U32:
  1466

def conditions_phantomforce() -> U32:
  1467

def conditions_pickedteamsize() -> U32:
  1468

def conditions_pomegglitchclause() -> U32:
  1469

def conditions_potd() -> U32:
  1470

def conditions_powder() -> U32:
  1471

def conditions_powershift() -> U32:
  1472

def conditions_powertrick() -> U32:
  1473

def conditions_primordialsea() -> U32:
  1474

def conditions_proteanpalacemod() -> U32:
  1475

def conditions_protect() -> U32:
  1476

def conditions_protosynthesis() -> U32:
  1477

def conditions_psn() -> U32:
  1478

def conditions_psychicterrain() -> U32:
  1479

def conditions_pursuit() -> U32:
  1480

def conditions_quarkdrive() -> U32:
  1481

def conditions_quickguard() -> U32:
  1482

def conditions_rage() -> U32:
  1483

def conditions_ragepowder() -> U32:
  1484

def conditions_raindance() -> U32:
  1485

def conditions_rebalancelevels() -> U32:
  1486

def conditions_recoil() -> U32:
  1487

def conditions_reevolutionmod() -> U32:
  1488

def conditions_reflect() -> U32:
  1489

def conditions_revelationmonsmod() -> U32:
  1490

def conditions_revivalblessing() -> U32:
  1491

def conditions_rollout() -> U32:
  1492

def conditions_rolloutstorage() -> U32:
  1493

def conditions_roost() -> U32:
  1494

def conditions_safeguard() -> U32:
  1495

def conditions_saltcure() -> U32:
  1496

def conditions_samecolorclause() -> U32:
  1497

def conditions_sameletterclause() -> U32:
  1498

def conditions_sametypeclause() -> U32:
  1499

def conditions_sandstorm() -> U32:
  1500

def conditions_scalemonsmod() -> U32:
  1501

def conditions_shadowforce() -> U32:
  1502

def conditions_shelltrap() -> U32:
  1503

def conditions_silktrap() -> U32:
  1504

def conditions_silvally() -> U32:
  1505

def conditions_sinnohpokedex() -> U32:
  1506

def conditions_sketchmonsmovelegality() -> U32:
  1507

def conditions_sketchpostgen7moves() -> U32:
  1508

def conditions_skydrop() -> U32:
  1509

def conditions_sleepclausemod() -> U32:
  1510

def conditions_sleepmovesclause() -> U32:
  1511

def conditions_slp() -> U32:
  1512

def conditions_smackdown() -> U32:
  1513

def conditions_snatch() -> U32:
  1514

def conditions_snowscape() -> U32:
  1515

def conditions_speciesclause() -> U32:
  1516

def conditions_speciesrevealclause() -> U32:
  1517

def conditions_speedpassclause() -> U32:
  1518

def conditions_spikes() -> U32:
  1519

def conditions_spikyshield() -> U32:
  1520

def conditions_spotlight() -> U32:
  1521

def conditions_stabmonsmovelegality() -> U32:
  1522

def conditions_stadiumitemsclause() -> U32:
  1523

def conditions_stadiumpokecuprentals() -> U32:
  1524

def conditions_stadiumsleepclause() -> U32:
  1525

def conditions_stall() -> U32:
  1526

def conditions_standard() -> U32:
  1527

def conditions_standardag() -> U32:
  1528

def conditions_standarddoubles() -> U32:
  1529

def conditions_standarddraft() -> U32:
  1530

def conditions_standardnatdex() -> U32:
  1531

def conditions_standardnext() -> U32:
  1532

def conditions_standardoms() -> U32:
  1533

def conditions_stealthrock() -> U32:
  1534

def conditions_stickyweb() -> U32:
  1535

def conditions_stockpile() -> U32:
  1536

def conditions_substitute() -> U32:
  1537

def conditions_sunnyday() -> U32:
  1538

def conditions_switchpriorityclausemod() -> U32:
  1539

def conditions_syrupbomb() -> U32:
  1540

def conditions_tailwind() -> U32:
  1541

def conditions_tarshot() -> U32:
  1542

def conditions_taunt() -> U32:
  1543

def conditions_teampreview() -> U32:
  1544

def conditions_teamtypepreview() -> U32:
  1545

def conditions_telekinesis() -> U32:
  1546

def conditions_terastalclause() -> U32:
  1547

def conditions_teratypepreview() -> U32:
  1548

def conditions_throatchop() -> U32:
  1549

def conditions_tiershiftmod() -> U32:
  1550

def conditions_timeoutautochoose() -> U32:
  1551

def conditions_timeraccelerate() -> U32:
  1552

def conditions_timeraddperturn() -> U32:
  1553

def conditions_timergrace() -> U32:
  1554

def conditions_timermaxfirstturn() -> U32:
  1555

def conditions_timermaxperturn() -> U32:
  1556

def conditions_timerstarting() -> U32:
  1557

def conditions_torment() -> U32:
  1558

def conditions_tox() -> U32:
  1559

def conditions_toxicspikes() -> U32:
  1560

def conditions_trapped() -> U32:
  1561

def conditions_trapper() -> U32:
  1562

def conditions_trickroom() -> U32:
  1563

def conditions_truant() -> U32:
  1564

def conditions_twisteddimensionmod() -> U32:
  1565

def conditions_twoturnmove() -> U32:
  1566

def conditions_twovstwo() -> U32:
  1567

def conditions_unburden() -> U32:
  1568

def conditions_uniquepokemoves() -> U32:
  1569

def conditions_uproar() -> U32:
  1570

def conditions_vgctimer() -> U32:
  1571

def conditions_voltturnmayhemmod() -> U32:
  1572

def conditions_waterpledge() -> U32:
  1573

def conditions_watersport() -> U32:
  1574

def conditions_wideguard() -> U32:
  1575

def conditions_wish() -> U32:
  1576

def conditions_wonderroom() -> U32:
  1577

def conditions_yawn() -> U32:
  1578

def conditions_zacian() -> U32:
  1579

def conditions_zamazenta() -> U32:
  1580

def conditions_zenmode() -> U32:
  1581

def conditions_zmoveclause() -> U32:
  1582
