# Generated stable IDs from Showdown 9fb3a5b99f1a0bea17f495c5cc1bfe04fdd19c3e
import Base

def items_abilityshield() -> U32:
  1

def items_abomasite() -> U32:
  2

def items_absolite() -> U32:
  3

def items_absolitez() -> U32:
  4

def items_absorbbulb() -> U32:
  5

def items_adamantcrystal() -> U32:
  6

def items_adamantorb() -> U32:
  7

def items_adrenalineorb() -> U32:
  8

def items_aerodactylite() -> U32:
  9

def items_aggronite() -> U32:
  10

def items_aguavberry() -> U32:
  11

def items_airballoon() -> U32:
  12

def items_alakazite() -> U32:
  13

def items_aloraichiumz() -> U32:
  14

def items_altarianite() -> U32:
  15

def items_ampharosite() -> U32:
  16

def items_apicotberry() -> U32:
  17

def items_armorfossil() -> U32:
  18

def items_aspearberry() -> U32:
  19

def items_assaultvest() -> U32:
  20

def items_audinite() -> U32:
  21

def items_auspiciousarmor() -> U32:
  22

def items_babiriberry() -> U32:
  23

def items_banettite() -> U32:
  24

def items_barbaracite() -> U32:
  25

def items_baxcalibrite() -> U32:
  26

def items_beastball() -> U32:
  27

def items_beedrillite() -> U32:
  28

def items_belueberry() -> U32:
  29

def items_berry() -> U32:
  30

def items_berryjuice() -> U32:
  31

def items_berrysweet() -> U32:
  32

def items_berserkgene() -> U32:
  33

def items_bignugget() -> U32:
  34

def items_bigroot() -> U32:
  35

def items_bindingband() -> U32:
  36

def items_bitterberry() -> U32:
  37

def items_blackbelt() -> U32:
  38

def items_blackglasses() -> U32:
  39

def items_blacksludge() -> U32:
  40

def items_blastoisinite() -> U32:
  41

def items_blazikenite() -> U32:
  42

def items_blueorb() -> U32:
  43

def items_blukberry() -> U32:
  44

def items_blunderpolicy() -> U32:
  45

def items_boosterenergy() -> U32:
  46

def items_bottlecap() -> U32:
  47

def items_brightpowder() -> U32:
  48

def items_buggem() -> U32:
  49

def items_buginiumz() -> U32:
  50

def items_bugmemory() -> U32:
  51

def items_burndrive() -> U32:
  52

def items_burntberry() -> U32:
  53

def items_cameruptite() -> U32:
  54

def items_cellbattery() -> U32:
  55

def items_chandelurite() -> U32:
  56

def items_charcoal() -> U32:
  57

def items_charizarditex() -> U32:
  58

def items_charizarditey() -> U32:
  59

def items_chartiberry() -> U32:
  60

def items_cheriberry() -> U32:
  61

def items_cherishball() -> U32:
  62

def items_chesnaughtite() -> U32:
  63

def items_chestoberry() -> U32:
  64

def items_chilanberry() -> U32:
  65

def items_chilldrive() -> U32:
  66

def items_chimechite() -> U32:
  67

def items_chippedpot() -> U32:
  68

def items_choiceband() -> U32:
  69

def items_choicescarf() -> U32:
  70

def items_choicespecs() -> U32:
  71

def items_chopleberry() -> U32:
  72

def items_clawfossil() -> U32:
  73

def items_clearamulet() -> U32:
  74

def items_clefablite() -> U32:
  75

def items_cloversweet() -> U32:
  76

def items_cobaberry() -> U32:
  77

def items_colburberry() -> U32:
  78

def items_cornerstonemask() -> U32:
  79

def items_cornnberry() -> U32:
  80

def items_coverfossil() -> U32:
  81

def items_covertcloak() -> U32:
  82

def items_crabominite() -> U32:
  83

def items_crackedpot() -> U32:
  84

def items_crucibellite() -> U32:
  85

def items_custapberry() -> U32:
  86

def items_damprock() -> U32:
  87

def items_darkgem() -> U32:
  88

def items_darkiniumz() -> U32:
  89

def items_darkmemory() -> U32:
  90

def items_darkranite() -> U32:
  91

def items_dawnstone() -> U32:
  92

def items_decidiumz() -> U32:
  93

def items_deepseascale() -> U32:
  94

def items_deepseatooth() -> U32:
  95

def items_delphoxite() -> U32:
  96

def items_destinyknot() -> U32:
  97

def items_diancite() -> U32:
  98

def items_diveball() -> U32:
  99

def items_domefossil() -> U32:
  100

def items_dousedrive() -> U32:
  101

def items_dracoplate() -> U32:
  102

def items_dragalgite() -> U32:
  103

def items_dragonfang() -> U32:
  104

def items_dragongem() -> U32:
  105

def items_dragoninite() -> U32:
  106

def items_dragoniumz() -> U32:
  107

def items_dragonmemory() -> U32:
  108

def items_dragonscale() -> U32:
  109

def items_drampanite() -> U32:
  110

def items_dreadplate() -> U32:
  111

def items_dreamball() -> U32:
  112

def items_dubiousdisc() -> U32:
  113

def items_durinberry() -> U32:
  114

def items_duskball() -> U32:
  115

def items_duskstone() -> U32:
  116

def items_earthplate() -> U32:
  117

def items_eelektrossite() -> U32:
  118

def items_eeviumz() -> U32:
  119

def items_ejectbutton() -> U32:
  120

def items_ejectpack() -> U32:
  121

def items_electirizer() -> U32:
  122

def items_electricgem() -> U32:
  123

def items_electricmemory() -> U32:
  124

def items_electricseed() -> U32:
  125

def items_electriumz() -> U32:
  126

def items_emboarite() -> U32:
  127

def items_enigmaberry() -> U32:
  128

def items_eviolite() -> U32:
  129

def items_excadrite() -> U32:
  130

def items_expertbelt() -> U32:
  131

def items_fairiumz() -> U32:
  132

def items_fairyfeather() -> U32:
  133

def items_fairygem() -> U32:
  134

def items_fairymemory() -> U32:
  135

def items_falinksite() -> U32:
  136

def items_fastball() -> U32:
  137

def items_feraligite() -> U32:
  138

def items_fightinggem() -> U32:
  139

def items_fightingmemory() -> U32:
  140

def items_fightiniumz() -> U32:
  141

def items_figyberry() -> U32:
  142

def items_firegem() -> U32:
  143

def items_firememory() -> U32:
  144

def items_firestone() -> U32:
  145

def items_firiumz() -> U32:
  146

def items_fistplate() -> U32:
  147

def items_flameorb() -> U32:
  148

def items_flameplate() -> U32:
  149

def items_floatstone() -> U32:
  150

def items_floettite() -> U32:
  151

def items_flowersweet() -> U32:
  152

def items_flyinggem() -> U32:
  153

def items_flyingmemory() -> U32:
  154

def items_flyiniumz() -> U32:
  155

def items_focusband() -> U32:
  156

def items_focussash() -> U32:
  157

def items_fossilizedbird() -> U32:
  158

def items_fossilizeddino() -> U32:
  159

def items_fossilizeddrake() -> U32:
  160

def items_fossilizedfish() -> U32:
  161

def items_friendball() -> U32:
  162

def items_froslassite() -> U32:
  163

def items_fullincense() -> U32:
  164

def items_galaricacuff() -> U32:
  165

def items_galaricawreath() -> U32:
  166

def items_galladite() -> U32:
  167

def items_ganlonberry() -> U32:
  168

def items_garchompite() -> U32:
  169

def items_garchompitez() -> U32:
  170

def items_gardevoirite() -> U32:
  171

def items_gengarite() -> U32:
  172

def items_ghostgem() -> U32:
  173

def items_ghostiumz() -> U32:
  174

def items_ghostmemory() -> U32:
  175

def items_glalitite() -> U32:
  176

def items_glimmoranite() -> U32:
  177

def items_goldberry() -> U32:
  178

def items_goldbottlecap() -> U32:
  179

def items_golisopite() -> U32:
  180

def items_golurkite() -> U32:
  181

def items_grassgem() -> U32:
  182

def items_grassiumz() -> U32:
  183

def items_grassmemory() -> U32:
  184

def items_grassyseed() -> U32:
  185

def items_greatball() -> U32:
  186

def items_greninjite() -> U32:
  187

def items_grepaberry() -> U32:
  188

def items_gripclaw() -> U32:
  189

def items_griseouscore() -> U32:
  190

def items_griseousorb() -> U32:
  191

def items_groundgem() -> U32:
  192

def items_groundiumz() -> U32:
  193

def items_groundmemory() -> U32:
  194

def items_gyaradosite() -> U32:
  195

def items_habanberry() -> U32:
  196

def items_hardstone() -> U32:
  197

def items_hawluchanite() -> U32:
  198

def items_healball() -> U32:
  199

def items_hearthflamemask() -> U32:
  200

def items_heatranite() -> U32:
  201

def items_heatrock() -> U32:
  202

def items_heavyball() -> U32:
  203

def items_heavydutyboots() -> U32:
  204

def items_helixfossil() -> U32:
  205

def items_heracronite() -> U32:
  206

def items_hondewberry() -> U32:
  207

def items_houndoominite() -> U32:
  208

def items_iapapaberry() -> U32:
  209

def items_iceberry() -> U32:
  210

def items_icegem() -> U32:
  211

def items_icememory() -> U32:
  212

def items_icestone() -> U32:
  213

def items_icicleplate() -> U32:
  214

def items_iciumz() -> U32:
  215

def items_icyrock() -> U32:
  216

def items_inciniumz() -> U32:
  217

def items_insectplate() -> U32:
  218

def items_ironball() -> U32:
  219

def items_ironplate() -> U32:
  220

def items_jabocaberry() -> U32:
  221

def items_jawfossil() -> U32:
  222

def items_kangaskhanite() -> U32:
  223

def items_kasibberry() -> U32:
  224

def items_kebiaberry() -> U32:
  225

def items_keeberry() -> U32:
  226

def items_kelpsyberry() -> U32:
  227

def items_kingsrock() -> U32:
  228

def items_kommoniumz() -> U32:
  229

def items_laggingtail() -> U32:
  230

def items_lansatberry() -> U32:
  231

def items_latiasite() -> U32:
  232

def items_latiosite() -> U32:
  233

def items_laxincense() -> U32:
  234

def items_leafstone() -> U32:
  235

def items_leek() -> U32:
  236

def items_leftovers() -> U32:
  237

def items_leppaberry() -> U32:
  238

def items_levelball() -> U32:
  239

def items_liechiberry() -> U32:
  240

def items_lifeorb() -> U32:
  241

def items_lightball() -> U32:
  242

def items_lightclay() -> U32:
  243

def items_loadeddice() -> U32:
  244

def items_lopunnite() -> U32:
  245

def items_loveball() -> U32:
  246

def items_lovesweet() -> U32:
  247

def items_lucarionite() -> U32:
  248

def items_lucarionitez() -> U32:
  249

def items_luckypunch() -> U32:
  250

def items_lumberry() -> U32:
  251

def items_luminousmoss() -> U32:
  252

def items_lunaliumz() -> U32:
  253

def items_lureball() -> U32:
  254

def items_lustrousglobe() -> U32:
  255

def items_lustrousorb() -> U32:
  256

def items_luxuryball() -> U32:
  257

def items_lycaniumz() -> U32:
  258

def items_machobrace() -> U32:
  259

def items_magearnite() -> U32:
  260

def items_magmarizer() -> U32:
  261

def items_magnet() -> U32:
  262

def items_magoberry() -> U32:
  263

def items_magostberry() -> U32:
  264

def items_mail() -> U32:
  265

def items_malamarite() -> U32:
  266

def items_maliciousarmor() -> U32:
  267

def items_manectite() -> U32:
  268

def items_marangaberry() -> U32:
  269

def items_marshadiumz() -> U32:
  270

def items_masterball() -> U32:
  271

def items_masterpieceteacup() -> U32:
  272

def items_mawilite() -> U32:
  273

def items_meadowplate() -> U32:
  274

def items_medichamite() -> U32:
  275

def items_meganiumite() -> U32:
  276

def items_mentalherb() -> U32:
  277

def items_meowsticite() -> U32:
  278

def items_metagrossite() -> U32:
  279

def items_metalalloy() -> U32:
  280

def items_metalcoat() -> U32:
  281

def items_metalpowder() -> U32:
  282

def items_metronome() -> U32:
  283

def items_mewniumz() -> U32:
  284

def items_mewtwonitex() -> U32:
  285

def items_mewtwonitey() -> U32:
  286

def items_micleberry() -> U32:
  287

def items_mimikiumz() -> U32:
  288

def items_mindplate() -> U32:
  289

def items_mintberry() -> U32:
  290

def items_miracleberry() -> U32:
  291

def items_miracleseed() -> U32:
  292

def items_mirrorherb() -> U32:
  293

def items_mistyseed() -> U32:
  294

def items_moonball() -> U32:
  295

def items_moonstone() -> U32:
  296

def items_muscleband() -> U32:
  297

def items_mysteryberry() -> U32:
  298

def items_mysticwater() -> U32:
  299

def items_nanabberry() -> U32:
  300

def items_nestball() -> U32:
  301

def items_netball() -> U32:
  302

def items_nevermeltice() -> U32:
  303

def items_nomelberry() -> U32:
  304

def items_normalgem() -> U32:
  305

def items_normaliumz() -> U32:
  306

def items_occaberry() -> U32:
  307

def items_oddincense() -> U32:
  308

def items_oldamber() -> U32:
  309

def items_oranberry() -> U32:
  310

def items_ovalstone() -> U32:
  311

def items_pamtreberry() -> U32:
  312

def items_parkball() -> U32:
  313

def items_passhoberry() -> U32:
  314

def items_payapaberry() -> U32:
  315

def items_pechaberry() -> U32:
  316

def items_persimberry() -> U32:
  317

def items_petayaberry() -> U32:
  318

def items_pidgeotite() -> U32:
  319

def items_pikaniumz() -> U32:
  320

def items_pikashuniumz() -> U32:
  321

def items_pinapberry() -> U32:
  322

def items_pinkbow() -> U32:
  323

def items_pinsirite() -> U32:
  324

def items_pixieplate() -> U32:
  325

def items_plumefossil() -> U32:
  326

def items_poisonbarb() -> U32:
  327

def items_poisongem() -> U32:
  328

def items_poisoniumz() -> U32:
  329

def items_poisonmemory() -> U32:
  330

def items_pokeball() -> U32:
  331

def items_polkadotbow() -> U32:
  332

def items_pomegberry() -> U32:
  333

def items_poweranklet() -> U32:
  334

def items_powerband() -> U32:
  335

def items_powerbelt() -> U32:
  336

def items_powerbracer() -> U32:
  337

def items_powerherb() -> U32:
  338

def items_powerlens() -> U32:
  339

def items_powerweight() -> U32:
  340

def items_premierball() -> U32:
  341

def items_prettyfeather() -> U32:
  342

def items_primariumz() -> U32:
  343

def items_prismscale() -> U32:
  344

def items_protectivepads() -> U32:
  345

def items_protector() -> U32:
  346

def items_przcureberry() -> U32:
  347

def items_psncureberry() -> U32:
  348

def items_psychicgem() -> U32:
  349

def items_psychicmemory() -> U32:
  350

def items_psychicseed() -> U32:
  351

def items_psychiumz() -> U32:
  352

def items_punchingglove() -> U32:
  353

def items_pyroarite() -> U32:
  354

def items_qualotberry() -> U32:
  355

def items_quickball() -> U32:
  356

def items_quickclaw() -> U32:
  357

def items_quickpowder() -> U32:
  358

def items_rabutaberry() -> U32:
  359

def items_raichunitex() -> U32:
  360

def items_raichunitey() -> U32:
  361

def items_rarebone() -> U32:
  362

def items_rawstberry() -> U32:
  363

def items_razorclaw() -> U32:
  364

def items_razorfang() -> U32:
  365

def items_razzberry() -> U32:
  366

def items_reapercloth() -> U32:
  367

def items_redcard() -> U32:
  368

def items_redorb() -> U32:
  369

def items_repeatball() -> U32:
  370

def items_ribbonsweet() -> U32:
  371

def items_rindoberry() -> U32:
  372

def items_ringtarget() -> U32:
  373

def items_rockgem() -> U32:
  374

def items_rockincense() -> U32:
  375

def items_rockiumz() -> U32:
  376

def items_rockmemory() -> U32:
  377

def items_rockyhelmet() -> U32:
  378

def items_roomservice() -> U32:
  379

def items_rootfossil() -> U32:
  380

def items_roseincense() -> U32:
  381

def items_roseliberry() -> U32:
  382

def items_rowapberry() -> U32:
  383

def items_rustedshield() -> U32:
  384

def items_rustedsword() -> U32:
  385

def items_sablenite() -> U32:
  386

def items_sachet() -> U32:
  387

def items_safariball() -> U32:
  388

def items_safetygoggles() -> U32:
  389

def items_sailfossil() -> U32:
  390

def items_salacberry() -> U32:
  391

def items_salamencite() -> U32:
  392

def items_sceptilite() -> U32:
  393

def items_scizorite() -> U32:
  394

def items_scolipite() -> U32:
  395

def items_scopelens() -> U32:
  396

def items_scovillainite() -> U32:
  397

def items_scraftinite() -> U32:
  398

def items_seaincense() -> U32:
  399

def items_sharpbeak() -> U32:
  400

def items_sharpedonite() -> U32:
  401

def items_shedshell() -> U32:
  402

def items_shellbell() -> U32:
  403

def items_shinystone() -> U32:
  404

def items_shockdrive() -> U32:
  405

def items_shucaberry() -> U32:
  406

def items_silkscarf() -> U32:
  407

def items_silverpowder() -> U32:
  408

def items_sitrusberry() -> U32:
  409

def items_skarmorite() -> U32:
  410

def items_skullfossil() -> U32:
  411

def items_skyplate() -> U32:
  412

def items_slowbronite() -> U32:
  413

def items_smoothrock() -> U32:
  414

def items_snorliumz() -> U32:
  415

def items_snowball() -> U32:
  416

def items_softsand() -> U32:
  417

def items_solganiumz() -> U32:
  418

def items_souldew() -> U32:
  419

def items_spelltag() -> U32:
  420

def items_spelonberry() -> U32:
  421

def items_splashplate() -> U32:
  422

def items_spookyplate() -> U32:
  423

def items_sportball() -> U32:
  424

def items_staraptite() -> U32:
  425

def items_starfberry() -> U32:
  426

def items_starminite() -> U32:
  427

def items_starsweet() -> U32:
  428

def items_steelgem() -> U32:
  429

def items_steeliumz() -> U32:
  430

def items_steelixite() -> U32:
  431

def items_steelmemory() -> U32:
  432

def items_stick() -> U32:
  433

def items_stickybarb() -> U32:
  434

def items_stoneplate() -> U32:
  435

def items_strangeball() -> U32:
  436

def items_strawberrysweet() -> U32:
  437

def items_sunstone() -> U32:
  438

def items_swampertite() -> U32:
  439

def items_sweetapple() -> U32:
  440

def items_syrupyapple() -> U32:
  441

def items_tamatoberry() -> U32:
  442

def items_tangaberry() -> U32:
  443

def items_tapuniumz() -> U32:
  444

def items_tartapple() -> U32:
  445

def items_tatsugirinite() -> U32:
  446

def items_terrainextender() -> U32:
  447

def items_thickclub() -> U32:
  448

def items_throatspray() -> U32:
  449

def items_thunderstone() -> U32:
  450

def items_timerball() -> U32:
  451

def items_toxicorb() -> U32:
  452

def items_toxicplate() -> U32:
  453

def items_tr00() -> U32:
  454

def items_tr01() -> U32:
  455

def items_tr02() -> U32:
  456

def items_tr03() -> U32:
  457

def items_tr04() -> U32:
  458

def items_tr05() -> U32:
  459

def items_tr06() -> U32:
  460

def items_tr07() -> U32:
  461

def items_tr08() -> U32:
  462

def items_tr09() -> U32:
  463

def items_tr10() -> U32:
  464

def items_tr11() -> U32:
  465

def items_tr12() -> U32:
  466

def items_tr13() -> U32:
  467

def items_tr14() -> U32:
  468

def items_tr15() -> U32:
  469

def items_tr16() -> U32:
  470

def items_tr17() -> U32:
  471

def items_tr18() -> U32:
  472

def items_tr19() -> U32:
  473

def items_tr20() -> U32:
  474

def items_tr21() -> U32:
  475

def items_tr22() -> U32:
  476

def items_tr23() -> U32:
  477

def items_tr24() -> U32:
  478

def items_tr25() -> U32:
  479

def items_tr26() -> U32:
  480

def items_tr27() -> U32:
  481

def items_tr28() -> U32:
  482

def items_tr29() -> U32:
  483

def items_tr30() -> U32:
  484

def items_tr31() -> U32:
  485

def items_tr32() -> U32:
  486

def items_tr33() -> U32:
  487

def items_tr34() -> U32:
  488

def items_tr35() -> U32:
  489

def items_tr36() -> U32:
  490

def items_tr37() -> U32:
  491

def items_tr38() -> U32:
  492

def items_tr39() -> U32:
  493

def items_tr40() -> U32:
  494

def items_tr41() -> U32:
  495

def items_tr42() -> U32:
  496

def items_tr43() -> U32:
  497

def items_tr44() -> U32:
  498

def items_tr45() -> U32:
  499

def items_tr46() -> U32:
  500

def items_tr47() -> U32:
  501

def items_tr48() -> U32:
  502

def items_tr49() -> U32:
  503

def items_tr50() -> U32:
  504

def items_tr51() -> U32:
  505

def items_tr52() -> U32:
  506

def items_tr53() -> U32:
  507

def items_tr54() -> U32:
  508

def items_tr55() -> U32:
  509

def items_tr56() -> U32:
  510

def items_tr57() -> U32:
  511

def items_tr58() -> U32:
  512

def items_tr59() -> U32:
  513

def items_tr60() -> U32:
  514

def items_tr61() -> U32:
  515

def items_tr62() -> U32:
  516

def items_tr63() -> U32:
  517

def items_tr64() -> U32:
  518

def items_tr65() -> U32:
  519

def items_tr66() -> U32:
  520

def items_tr67() -> U32:
  521

def items_tr68() -> U32:
  522

def items_tr69() -> U32:
  523

def items_tr70() -> U32:
  524

def items_tr71() -> U32:
  525

def items_tr72() -> U32:
  526

def items_tr73() -> U32:
  527

def items_tr74() -> U32:
  528

def items_tr75() -> U32:
  529

def items_tr76() -> U32:
  530

def items_tr77() -> U32:
  531

def items_tr78() -> U32:
  532

def items_tr79() -> U32:
  533

def items_tr80() -> U32:
  534

def items_tr81() -> U32:
  535

def items_tr82() -> U32:
  536

def items_tr83() -> U32:
  537

def items_tr84() -> U32:
  538

def items_tr85() -> U32:
  539

def items_tr86() -> U32:
  540

def items_tr87() -> U32:
  541

def items_tr88() -> U32:
  542

def items_tr89() -> U32:
  543

def items_tr90() -> U32:
  544

def items_tr91() -> U32:
  545

def items_tr92() -> U32:
  546

def items_tr93() -> U32:
  547

def items_tr94() -> U32:
  548

def items_tr95() -> U32:
  549

def items_tr96() -> U32:
  550

def items_tr97() -> U32:
  551

def items_tr98() -> U32:
  552

def items_tr99() -> U32:
  553

def items_twistedspoon() -> U32:
  554

def items_tyranitarite() -> U32:
  555

def items_ultraball() -> U32:
  556

def items_ultranecroziumz() -> U32:
  557

def items_unremarkableteacup() -> U32:
  558

def items_upgrade() -> U32:
  559

def items_utilityumbrella() -> U32:
  560

def items_venusaurite() -> U32:
  561

def items_victreebelite() -> U32:
  562

def items_vilevial() -> U32:
  563

def items_wacanberry() -> U32:
  564

def items_watergem() -> U32:
  565

def items_wateriumz() -> U32:
  566

def items_watermemory() -> U32:
  567

def items_waterstone() -> U32:
  568

def items_watmelberry() -> U32:
  569

def items_waveincense() -> U32:
  570

def items_weaknesspolicy() -> U32:
  571

def items_wellspringmask() -> U32:
  572

def items_wepearberry() -> U32:
  573

def items_whippeddream() -> U32:
  574

def items_whiteherb() -> U32:
  575

def items_widelens() -> U32:
  576

def items_wikiberry() -> U32:
  577

def items_wiseglasses() -> U32:
  578

def items_yacheberry() -> U32:
  579

def items_zapplate() -> U32:
  580

def items_zeraorite() -> U32:
  581

def items_zoomlens() -> U32:
  582

def items_zygardite() -> U32:
  583
