# Generated stable IDs from Showdown 9fb3a5b99f1a0bea17f495c5cc1bfe04fdd19c3e
import Base

def moves_10000000voltthunderbolt() -> U32:
  1

def moves_absorb() -> U32:
  2

def moves_accelerock() -> U32:
  3

def moves_acid() -> U32:
  4

def moves_acidarmor() -> U32:
  5

def moves_aciddownpour() -> U32:
  6

def moves_acidspray() -> U32:
  7

def moves_acrobatics() -> U32:
  8

def moves_acupressure() -> U32:
  9

def moves_aerialace() -> U32:
  10

def moves_aeroblast() -> U32:
  11

def moves_afteryou() -> U32:
  12

def moves_agility() -> U32:
  13

def moves_aircutter() -> U32:
  14

def moves_airslash() -> U32:
  15

def moves_alloutpummeling() -> U32:
  16

def moves_alluringvoice() -> U32:
  17

def moves_allyswitch() -> U32:
  18

def moves_amnesia() -> U32:
  19

def moves_anchorshot() -> U32:
  20

def moves_ancientpower() -> U32:
  21

def moves_appleacid() -> U32:
  22

def moves_aquacutter() -> U32:
  23

def moves_aquajet() -> U32:
  24

def moves_aquaring() -> U32:
  25

def moves_aquastep() -> U32:
  26

def moves_aquatail() -> U32:
  27

def moves_armorcannon() -> U32:
  28

def moves_armthrust() -> U32:
  29

def moves_aromatherapy() -> U32:
  30

def moves_aromaticmist() -> U32:
  31

def moves_assist() -> U32:
  32

def moves_assurance() -> U32:
  33

def moves_astonish() -> U32:
  34

def moves_astralbarrage() -> U32:
  35

def moves_attackorder() -> U32:
  36

def moves_attract() -> U32:
  37

def moves_aurasphere() -> U32:
  38

def moves_aurawheel() -> U32:
  39

def moves_aurorabeam() -> U32:
  40

def moves_auroraveil() -> U32:
  41

def moves_autotomize() -> U32:
  42

def moves_avalanche() -> U32:
  43

def moves_axekick() -> U32:
  44

def moves_babydolleyes() -> U32:
  45

def moves_baddybad() -> U32:
  46

def moves_banefulbunker() -> U32:
  47

def moves_barbbarrage() -> U32:
  48

def moves_barrage() -> U32:
  49

def moves_barrier() -> U32:
  50

def moves_batonpass() -> U32:
  51

def moves_beakblast() -> U32:
  52

def moves_beatup() -> U32:
  53

def moves_behemothbash() -> U32:
  54

def moves_behemothblade() -> U32:
  55

def moves_belch() -> U32:
  56

def moves_bellydrum() -> U32:
  57

def moves_bestow() -> U32:
  58

def moves_bide() -> U32:
  59

def moves_bind() -> U32:
  60

def moves_bite() -> U32:
  61

def moves_bitterblade() -> U32:
  62

def moves_bittermalice() -> U32:
  63

def moves_blackholeeclipse() -> U32:
  64

def moves_blastburn() -> U32:
  65

def moves_blazekick() -> U32:
  66

def moves_blazingtorque() -> U32:
  67

def moves_bleakwindstorm() -> U32:
  68

def moves_blizzard() -> U32:
  69

def moves_block() -> U32:
  70

def moves_bloodmoon() -> U32:
  71

def moves_bloomdoom() -> U32:
  72

def moves_blueflare() -> U32:
  73

def moves_bodypress() -> U32:
  74

def moves_bodyslam() -> U32:
  75

def moves_boltbeak() -> U32:
  76

def moves_boltstrike() -> U32:
  77

def moves_boneclub() -> U32:
  78

def moves_bonemerang() -> U32:
  79

def moves_bonerush() -> U32:
  80

def moves_boomburst() -> U32:
  81

def moves_bounce() -> U32:
  82

def moves_bouncybubble() -> U32:
  83

def moves_branchpoke() -> U32:
  84

def moves_bravebird() -> U32:
  85

def moves_breakingswipe() -> U32:
  86

def moves_breakneckblitz() -> U32:
  87

def moves_brickbreak() -> U32:
  88

def moves_brine() -> U32:
  89

def moves_brutalswing() -> U32:
  90

def moves_bubble() -> U32:
  91

def moves_bubblebeam() -> U32:
  92

def moves_bugbite() -> U32:
  93

def moves_bugbuzz() -> U32:
  94

def moves_bulkup() -> U32:
  95

def moves_bulldoze() -> U32:
  96

def moves_bulletpunch() -> U32:
  97

def moves_bulletseed() -> U32:
  98

def moves_burningbulwark() -> U32:
  99

def moves_burningjealousy() -> U32:
  100

def moves_burnup() -> U32:
  101

def moves_buzzybuzz() -> U32:
  102

def moves_calmmind() -> U32:
  103

def moves_camouflage() -> U32:
  104

def moves_captivate() -> U32:
  105

def moves_catastropika() -> U32:
  106

def moves_ceaselessedge() -> U32:
  107

def moves_celebrate() -> U32:
  108

def moves_charge() -> U32:
  109

def moves_chargebeam() -> U32:
  110

def moves_charm() -> U32:
  111

def moves_chatter() -> U32:
  112

def moves_chillingwater() -> U32:
  113

def moves_chillyreception() -> U32:
  114

def moves_chipaway() -> U32:
  115

def moves_chloroblast() -> U32:
  116

def moves_circlethrow() -> U32:
  117

def moves_clamp() -> U32:
  118

def moves_clangingscales() -> U32:
  119

def moves_clangoroussoul() -> U32:
  120

def moves_clangoroussoulblaze() -> U32:
  121

def moves_clearsmog() -> U32:
  122

def moves_closecombat() -> U32:
  123

def moves_coaching() -> U32:
  124

def moves_coil() -> U32:
  125

def moves_collisioncourse() -> U32:
  126

def moves_combattorque() -> U32:
  127

def moves_cometpunch() -> U32:
  128

def moves_comeuppance() -> U32:
  129

def moves_confide() -> U32:
  130

def moves_confuseray() -> U32:
  131

def moves_confusion() -> U32:
  132

def moves_constrict() -> U32:
  133

def moves_continentalcrush() -> U32:
  134

def moves_conversion() -> U32:
  135

def moves_conversion2() -> U32:
  136

def moves_copycat() -> U32:
  137

def moves_coreenforcer() -> U32:
  138

def moves_corkscrewcrash() -> U32:
  139

def moves_corrosivegas() -> U32:
  140

def moves_cosmicpower() -> U32:
  141

def moves_cottonguard() -> U32:
  142

def moves_cottonspore() -> U32:
  143

def moves_counter() -> U32:
  144

def moves_courtchange() -> U32:
  145

def moves_covet() -> U32:
  146

def moves_crabhammer() -> U32:
  147

def moves_craftyshield() -> U32:
  148

def moves_crosschop() -> U32:
  149

def moves_crosspoison() -> U32:
  150

def moves_crunch() -> U32:
  151

def moves_crushclaw() -> U32:
  152

def moves_crushgrip() -> U32:
  153

def moves_curse() -> U32:
  154

def moves_cut() -> U32:
  155

def moves_darkestlariat() -> U32:
  156

def moves_darkpulse() -> U32:
  157

def moves_darkvoid() -> U32:
  158

def moves_dazzlinggleam() -> U32:
  159

def moves_decorate() -> U32:
  160

def moves_defendorder() -> U32:
  161

def moves_defensecurl() -> U32:
  162

def moves_defog() -> U32:
  163

def moves_destinybond() -> U32:
  164

def moves_detect() -> U32:
  165

def moves_devastatingdrake() -> U32:
  166

def moves_diamondstorm() -> U32:
  167

def moves_dig() -> U32:
  168

def moves_direclaw() -> U32:
  169

def moves_disable() -> U32:
  170

def moves_disarmingvoice() -> U32:
  171

def moves_discharge() -> U32:
  172

def moves_dive() -> U32:
  173

def moves_dizzypunch() -> U32:
  174

def moves_doodle() -> U32:
  175

def moves_doomdesire() -> U32:
  176

def moves_doubleedge() -> U32:
  177

def moves_doublehit() -> U32:
  178

def moves_doubleironbash() -> U32:
  179

def moves_doublekick() -> U32:
  180

def moves_doubleshock() -> U32:
  181

def moves_doubleslap() -> U32:
  182

def moves_doubleteam() -> U32:
  183

def moves_dracometeor() -> U32:
  184

def moves_dragonascent() -> U32:
  185

def moves_dragonbreath() -> U32:
  186

def moves_dragoncheer() -> U32:
  187

def moves_dragonclaw() -> U32:
  188

def moves_dragondance() -> U32:
  189

def moves_dragondarts() -> U32:
  190

def moves_dragonenergy() -> U32:
  191

def moves_dragonhammer() -> U32:
  192

def moves_dragonpulse() -> U32:
  193

def moves_dragonrage() -> U32:
  194

def moves_dragonrush() -> U32:
  195

def moves_dragontail() -> U32:
  196

def moves_drainingkiss() -> U32:
  197

def moves_drainpunch() -> U32:
  198

def moves_dreameater() -> U32:
  199

def moves_drillpeck() -> U32:
  200

def moves_drillrun() -> U32:
  201

def moves_drumbeating() -> U32:
  202

def moves_dualchop() -> U32:
  203

def moves_dualwingbeat() -> U32:
  204

def moves_dynamaxcannon() -> U32:
  205

def moves_dynamicpunch() -> U32:
  206

def moves_earthpower() -> U32:
  207

def moves_earthquake() -> U32:
  208

def moves_echoedvoice() -> U32:
  209

def moves_eerieimpulse() -> U32:
  210

def moves_eeriespell() -> U32:
  211

def moves_eggbomb() -> U32:
  212

def moves_electricterrain() -> U32:
  213

def moves_electrify() -> U32:
  214

def moves_electroball() -> U32:
  215

def moves_electrodrift() -> U32:
  216

def moves_electroshot() -> U32:
  217

def moves_electroweb() -> U32:
  218

def moves_embargo() -> U32:
  219

def moves_ember() -> U32:
  220

def moves_encore() -> U32:
  221

def moves_endeavor() -> U32:
  222

def moves_endure() -> U32:
  223

def moves_energyball() -> U32:
  224

def moves_entrainment() -> U32:
  225

def moves_eruption() -> U32:
  226

def moves_esperwing() -> U32:
  227

def moves_eternabeam() -> U32:
  228

def moves_expandingforce() -> U32:
  229

def moves_explosion() -> U32:
  230

def moves_extrasensory() -> U32:
  231

def moves_extremeevoboost() -> U32:
  232

def moves_extremespeed() -> U32:
  233

def moves_facade() -> U32:
  234

def moves_fairylock() -> U32:
  235

def moves_fairywind() -> U32:
  236

def moves_fakeout() -> U32:
  237

def moves_faketears() -> U32:
  238

def moves_falsesurrender() -> U32:
  239

def moves_falseswipe() -> U32:
  240

def moves_featherdance() -> U32:
  241

def moves_feint() -> U32:
  242

def moves_feintattack() -> U32:
  243

def moves_fellstinger() -> U32:
  244

def moves_ficklebeam() -> U32:
  245

def moves_fierydance() -> U32:
  246

def moves_fierywrath() -> U32:
  247

def moves_filletaway() -> U32:
  248

def moves_finalgambit() -> U32:
  249

def moves_fireblast() -> U32:
  250

def moves_firefang() -> U32:
  251

def moves_firelash() -> U32:
  252

def moves_firepledge() -> U32:
  253

def moves_firepunch() -> U32:
  254

def moves_firespin() -> U32:
  255

def moves_firstimpression() -> U32:
  256

def moves_fishiousrend() -> U32:
  257

def moves_fissure() -> U32:
  258

def moves_flail() -> U32:
  259

def moves_flameburst() -> U32:
  260

def moves_flamecharge() -> U32:
  261

def moves_flamethrower() -> U32:
  262

def moves_flamewheel() -> U32:
  263

def moves_flareblitz() -> U32:
  264

def moves_flash() -> U32:
  265

def moves_flashcannon() -> U32:
  266

def moves_flatter() -> U32:
  267

def moves_fleurcannon() -> U32:
  268

def moves_fling() -> U32:
  269

def moves_flipturn() -> U32:
  270

def moves_floatyfall() -> U32:
  271

def moves_floralhealing() -> U32:
  272

def moves_flowershield() -> U32:
  273

def moves_flowertrick() -> U32:
  274

def moves_fly() -> U32:
  275

def moves_flyingpress() -> U32:
  276

def moves_focusblast() -> U32:
  277

def moves_focusenergy() -> U32:
  278

def moves_focuspunch() -> U32:
  279

def moves_followme() -> U32:
  280

def moves_forcepalm() -> U32:
  281

def moves_foresight() -> U32:
  282

def moves_forestscurse() -> U32:
  283

def moves_foulplay() -> U32:
  284

def moves_freezedry() -> U32:
  285

def moves_freezeshock() -> U32:
  286

def moves_freezingglare() -> U32:
  287

def moves_freezyfrost() -> U32:
  288

def moves_frenzyplant() -> U32:
  289

def moves_frostbreath() -> U32:
  290

def moves_frustration() -> U32:
  291

def moves_furyattack() -> U32:
  292

def moves_furycutter() -> U32:
  293

def moves_furyswipes() -> U32:
  294

def moves_fusionbolt() -> U32:
  295

def moves_fusionflare() -> U32:
  296

def moves_futuresight() -> U32:
  297

def moves_gastroacid() -> U32:
  298

def moves_geargrind() -> U32:
  299

def moves_gearup() -> U32:
  300

def moves_genesissupernova() -> U32:
  301

def moves_geomancy() -> U32:
  302

def moves_gigadrain() -> U32:
  303

def moves_gigaimpact() -> U32:
  304

def moves_gigatonhammer() -> U32:
  305

def moves_gigavolthavoc() -> U32:
  306

def moves_glaciallance() -> U32:
  307

def moves_glaciate() -> U32:
  308

def moves_glaiverush() -> U32:
  309

def moves_glare() -> U32:
  310

def moves_glitzyglow() -> U32:
  311

def moves_gmaxbefuddle() -> U32:
  312

def moves_gmaxcannonade() -> U32:
  313

def moves_gmaxcentiferno() -> U32:
  314

def moves_gmaxchistrike() -> U32:
  315

def moves_gmaxcuddle() -> U32:
  316

def moves_gmaxdepletion() -> U32:
  317

def moves_gmaxdrumsolo() -> U32:
  318

def moves_gmaxfinale() -> U32:
  319

def moves_gmaxfireball() -> U32:
  320

def moves_gmaxfoamburst() -> U32:
  321

def moves_gmaxgoldrush() -> U32:
  322

def moves_gmaxgravitas() -> U32:
  323

def moves_gmaxhydrosnipe() -> U32:
  324

def moves_gmaxmalodor() -> U32:
  325

def moves_gmaxmeltdown() -> U32:
  326

def moves_gmaxoneblow() -> U32:
  327

def moves_gmaxrapidflow() -> U32:
  328

def moves_gmaxreplenish() -> U32:
  329

def moves_gmaxresonance() -> U32:
  330

def moves_gmaxsandblast() -> U32:
  331

def moves_gmaxsmite() -> U32:
  332

def moves_gmaxsnooze() -> U32:
  333

def moves_gmaxsteelsurge() -> U32:
  334

def moves_gmaxstonesurge() -> U32:
  335

def moves_gmaxstunshock() -> U32:
  336

def moves_gmaxsweetness() -> U32:
  337

def moves_gmaxtartness() -> U32:
  338

def moves_gmaxterror() -> U32:
  339

def moves_gmaxvinelash() -> U32:
  340

def moves_gmaxvolcalith() -> U32:
  341

def moves_gmaxvoltcrash() -> U32:
  342

def moves_gmaxwildfire() -> U32:
  343

def moves_gmaxwindrage() -> U32:
  344

def moves_grassknot() -> U32:
  345

def moves_grasspledge() -> U32:
  346

def moves_grasswhistle() -> U32:
  347

def moves_grassyglide() -> U32:
  348

def moves_grassyterrain() -> U32:
  349

def moves_gravapple() -> U32:
  350

def moves_gravity() -> U32:
  351

def moves_growl() -> U32:
  352

def moves_growth() -> U32:
  353

def moves_grudge() -> U32:
  354

def moves_guardianofalola() -> U32:
  355

def moves_guardsplit() -> U32:
  356

def moves_guardswap() -> U32:
  357

def moves_guillotine() -> U32:
  358

def moves_gunkshot() -> U32:
  359

def moves_gust() -> U32:
  360

def moves_gyroball() -> U32:
  361

def moves_hail() -> U32:
  362

def moves_hammerarm() -> U32:
  363

def moves_happyhour() -> U32:
  364

def moves_harden() -> U32:
  365

def moves_hardpress() -> U32:
  366

def moves_haze() -> U32:
  367

def moves_headbutt() -> U32:
  368

def moves_headcharge() -> U32:
  369

def moves_headlongrush() -> U32:
  370

def moves_headsmash() -> U32:
  371

def moves_healbell() -> U32:
  372

def moves_healblock() -> U32:
  373

def moves_healingwish() -> U32:
  374

def moves_healorder() -> U32:
  375

def moves_healpulse() -> U32:
  376

def moves_heartstamp() -> U32:
  377

def moves_heartswap() -> U32:
  378

def moves_heatcrash() -> U32:
  379

def moves_heatwave() -> U32:
  380

def moves_heavyslam() -> U32:
  381

def moves_helpinghand() -> U32:
  382

def moves_hex() -> U32:
  383

def moves_hiddenpower() -> U32:
  384

def moves_highhorsepower() -> U32:
  385

def moves_highjumpkick() -> U32:
  386

def moves_holdback() -> U32:
  387

def moves_holdhands() -> U32:
  388

def moves_honeclaws() -> U32:
  389

def moves_hornattack() -> U32:
  390

def moves_horndrill() -> U32:
  391

def moves_hornleech() -> U32:
  392

def moves_howl() -> U32:
  393

def moves_hurricane() -> U32:
  394

def moves_hydrocannon() -> U32:
  395

def moves_hydropump() -> U32:
  396

def moves_hydrosteam() -> U32:
  397

def moves_hydrovortex() -> U32:
  398

def moves_hyperbeam() -> U32:
  399

def moves_hyperdrill() -> U32:
  400

def moves_hyperfang() -> U32:
  401

def moves_hyperspacefury() -> U32:
  402

def moves_hyperspacehole() -> U32:
  403

def moves_hypervoice() -> U32:
  404

def moves_hypnosis() -> U32:
  405

def moves_iceball() -> U32:
  406

def moves_icebeam() -> U32:
  407

def moves_iceburn() -> U32:
  408

def moves_icefang() -> U32:
  409

def moves_icehammer() -> U32:
  410

def moves_icepunch() -> U32:
  411

def moves_iceshard() -> U32:
  412

def moves_icespinner() -> U32:
  413

def moves_iciclecrash() -> U32:
  414

def moves_iciclespear() -> U32:
  415

def moves_icywind() -> U32:
  416

def moves_imprison() -> U32:
  417

def moves_incinerate() -> U32:
  418

def moves_infernalparade() -> U32:
  419

def moves_inferno() -> U32:
  420

def moves_infernooverdrive() -> U32:
  421

def moves_infestation() -> U32:
  422

def moves_ingrain() -> U32:
  423

def moves_instruct() -> U32:
  424

def moves_iondeluge() -> U32:
  425

def moves_irondefense() -> U32:
  426

def moves_ironhead() -> U32:
  427

def moves_irontail() -> U32:
  428

def moves_ivycudgel() -> U32:
  429

def moves_jawlock() -> U32:
  430

def moves_jetpunch() -> U32:
  431

def moves_judgment() -> U32:
  432

def moves_jumpkick() -> U32:
  433

def moves_junglehealing() -> U32:
  434

def moves_karatechop() -> U32:
  435

def moves_kinesis() -> U32:
  436

def moves_kingsshield() -> U32:
  437

def moves_knockoff() -> U32:
  438

def moves_kowtowcleave() -> U32:
  439

def moves_landswrath() -> U32:
  440

def moves_laserfocus() -> U32:
  441

def moves_lashout() -> U32:
  442

def moves_lastresort() -> U32:
  443

def moves_lastrespects() -> U32:
  444

def moves_lavaplume() -> U32:
  445

def moves_leafage() -> U32:
  446

def moves_leafblade() -> U32:
  447

def moves_leafstorm() -> U32:
  448

def moves_leaftornado() -> U32:
  449

def moves_leechlife() -> U32:
  450

def moves_leechseed() -> U32:
  451

def moves_leer() -> U32:
  452

def moves_letssnuggleforever() -> U32:
  453

def moves_lick() -> U32:
  454

def moves_lifedew() -> U32:
  455

def moves_lightofruin() -> U32:
  456

def moves_lightscreen() -> U32:
  457

def moves_lightthatburnsthesky() -> U32:
  458

def moves_liquidation() -> U32:
  459

def moves_lockon() -> U32:
  460

def moves_lovelykiss() -> U32:
  461

def moves_lowkick() -> U32:
  462

def moves_lowsweep() -> U32:
  463

def moves_luckychant() -> U32:
  464

def moves_luminacrash() -> U32:
  465

def moves_lunarblessing() -> U32:
  466

def moves_lunardance() -> U32:
  467

def moves_lunge() -> U32:
  468

def moves_lusterpurge() -> U32:
  469

def moves_machpunch() -> U32:
  470

def moves_magicalleaf() -> U32:
  471

def moves_magicaltorque() -> U32:
  472

def moves_magiccoat() -> U32:
  473

def moves_magicpowder() -> U32:
  474

def moves_magicroom() -> U32:
  475

def moves_magmastorm() -> U32:
  476

def moves_magnetbomb() -> U32:
  477

def moves_magneticflux() -> U32:
  478

def moves_magnetrise() -> U32:
  479

def moves_magnitude() -> U32:
  480

def moves_makeitrain() -> U32:
  481

def moves_maliciousmoonsault() -> U32:
  482

def moves_malignantchain() -> U32:
  483

def moves_matblock() -> U32:
  484

def moves_matchagotcha() -> U32:
  485

def moves_maxairstream() -> U32:
  486

def moves_maxdarkness() -> U32:
  487

def moves_maxflare() -> U32:
  488

def moves_maxflutterby() -> U32:
  489

def moves_maxgeyser() -> U32:
  490

def moves_maxguard() -> U32:
  491

def moves_maxhailstorm() -> U32:
  492

def moves_maxknuckle() -> U32:
  493

def moves_maxlightning() -> U32:
  494

def moves_maxmindstorm() -> U32:
  495

def moves_maxooze() -> U32:
  496

def moves_maxovergrowth() -> U32:
  497

def moves_maxphantasm() -> U32:
  498

def moves_maxquake() -> U32:
  499

def moves_maxrockfall() -> U32:
  500

def moves_maxstarfall() -> U32:
  501

def moves_maxsteelspike() -> U32:
  502

def moves_maxstrike() -> U32:
  503

def moves_maxwyrmwind() -> U32:
  504

def moves_meanlook() -> U32:
  505

def moves_meditate() -> U32:
  506

def moves_mefirst() -> U32:
  507

def moves_megadrain() -> U32:
  508

def moves_megahorn() -> U32:
  509

def moves_megakick() -> U32:
  510

def moves_megapunch() -> U32:
  511

def moves_memento() -> U32:
  512

def moves_menacingmoonrazemaelstrom() -> U32:
  513

def moves_metalburst() -> U32:
  514

def moves_metalclaw() -> U32:
  515

def moves_metalsound() -> U32:
  516

def moves_meteorassault() -> U32:
  517

def moves_meteorbeam() -> U32:
  518

def moves_meteormash() -> U32:
  519

def moves_metronome() -> U32:
  520

def moves_mightycleave() -> U32:
  521

def moves_milkdrink() -> U32:
  522

def moves_mimic() -> U32:
  523

def moves_mindblown() -> U32:
  524

def moves_mindreader() -> U32:
  525

def moves_minimize() -> U32:
  526

def moves_miracleeye() -> U32:
  527

def moves_mirrorcoat() -> U32:
  528

def moves_mirrormove() -> U32:
  529

def moves_mirrorshot() -> U32:
  530

def moves_mist() -> U32:
  531

def moves_mistball() -> U32:
  532

def moves_mistyexplosion() -> U32:
  533

def moves_mistyterrain() -> U32:
  534

def moves_moonblast() -> U32:
  535

def moves_moongeistbeam() -> U32:
  536

def moves_moonlight() -> U32:
  537

def moves_morningsun() -> U32:
  538

def moves_mortalspin() -> U32:
  539

def moves_mountaingale() -> U32:
  540

def moves_mudbomb() -> U32:
  541

def moves_muddywater() -> U32:
  542

def moves_mudshot() -> U32:
  543

def moves_mudslap() -> U32:
  544

def moves_mudsport() -> U32:
  545

def moves_multiattack() -> U32:
  546

def moves_mysticalfire() -> U32:
  547

def moves_mysticalpower() -> U32:
  548

def moves_nastyplot() -> U32:
  549

def moves_naturalgift() -> U32:
  550

def moves_naturepower() -> U32:
  551

def moves_naturesmadness() -> U32:
  552

def moves_needlearm() -> U32:
  553

def moves_neverendingnightmare() -> U32:
  554

def moves_nightdaze() -> U32:
  555

def moves_nightmare() -> U32:
  556

def moves_nightshade() -> U32:
  557

def moves_nightslash() -> U32:
  558

def moves_nihillight() -> U32:
  559

def moves_nobleroar() -> U32:
  560

def moves_noretreat() -> U32:
  561

def moves_noxioustorque() -> U32:
  562

def moves_nuzzle() -> U32:
  563

def moves_oblivionwing() -> U32:
  564

def moves_obstruct() -> U32:
  565

def moves_oceanicoperetta() -> U32:
  566

def moves_octazooka() -> U32:
  567

def moves_octolock() -> U32:
  568

def moves_odorsleuth() -> U32:
  569

def moves_ominouswind() -> U32:
  570

def moves_orderup() -> U32:
  571

def moves_originpulse() -> U32:
  572

def moves_outrage() -> U32:
  573

def moves_overdrive() -> U32:
  574

def moves_overheat() -> U32:
  575

def moves_painsplit() -> U32:
  576

def moves_paleowave() -> U32:
  577

def moves_paraboliccharge() -> U32:
  578

def moves_partingshot() -> U32:
  579

def moves_payback() -> U32:
  580

def moves_payday() -> U32:
  581

def moves_peck() -> U32:
  582

def moves_perishsong() -> U32:
  583

def moves_petalblizzard() -> U32:
  584

def moves_petaldance() -> U32:
  585

def moves_phantomforce() -> U32:
  586

def moves_photongeyser() -> U32:
  587

def moves_pikapapow() -> U32:
  588

def moves_pinmissile() -> U32:
  589

def moves_plasmafists() -> U32:
  590

def moves_playnice() -> U32:
  591

def moves_playrough() -> U32:
  592

def moves_pluck() -> U32:
  593

def moves_poisonfang() -> U32:
  594

def moves_poisongas() -> U32:
  595

def moves_poisonjab() -> U32:
  596

def moves_poisonpowder() -> U32:
  597

def moves_poisonsting() -> U32:
  598

def moves_poisontail() -> U32:
  599

def moves_polarflare() -> U32:
  600

def moves_pollenpuff() -> U32:
  601

def moves_poltergeist() -> U32:
  602

def moves_populationbomb() -> U32:
  603

def moves_pounce() -> U32:
  604

def moves_pound() -> U32:
  605

def moves_powder() -> U32:
  606

def moves_powdersnow() -> U32:
  607

def moves_powergem() -> U32:
  608

def moves_powershift() -> U32:
  609

def moves_powersplit() -> U32:
  610

def moves_powerswap() -> U32:
  611

def moves_powertrick() -> U32:
  612

def moves_powertrip() -> U32:
  613

def moves_poweruppunch() -> U32:
  614

def moves_powerwhip() -> U32:
  615

def moves_precipiceblades() -> U32:
  616

def moves_present() -> U32:
  617

def moves_prismaticlaser() -> U32:
  618

def moves_protect() -> U32:
  619

def moves_psybeam() -> U32:
  620

def moves_psyblade() -> U32:
  621

def moves_psychic() -> U32:
  622

def moves_psychicfangs() -> U32:
  623

def moves_psychicnoise() -> U32:
  624

def moves_psychicterrain() -> U32:
  625

def moves_psychoboost() -> U32:
  626

def moves_psychocut() -> U32:
  627

def moves_psychoshift() -> U32:
  628

def moves_psychup() -> U32:
  629

def moves_psyshieldbash() -> U32:
  630

def moves_psyshock() -> U32:
  631

def moves_psystrike() -> U32:
  632

def moves_psywave() -> U32:
  633

def moves_pulverizingpancake() -> U32:
  634

def moves_punishment() -> U32:
  635

def moves_purify() -> U32:
  636

def moves_pursuit() -> U32:
  637

def moves_pyroball() -> U32:
  638

def moves_quash() -> U32:
  639

def moves_quickattack() -> U32:
  640

def moves_quickguard() -> U32:
  641

def moves_quiverdance() -> U32:
  642

def moves_rage() -> U32:
  643

def moves_ragefist() -> U32:
  644

def moves_ragepowder() -> U32:
  645

def moves_ragingbull() -> U32:
  646

def moves_ragingfury() -> U32:
  647

def moves_raindance() -> U32:
  648

def moves_rapidspin() -> U32:
  649

def moves_razorleaf() -> U32:
  650

def moves_razorshell() -> U32:
  651

def moves_razorwind() -> U32:
  652

def moves_recover() -> U32:
  653

def moves_recycle() -> U32:
  654

def moves_reflect() -> U32:
  655

def moves_reflecttype() -> U32:
  656

def moves_refresh() -> U32:
  657

def moves_relicsong() -> U32:
  658

def moves_rest() -> U32:
  659

def moves_retaliate() -> U32:
  660

def moves_return() -> U32:
  661

def moves_revelationdance() -> U32:
  662

def moves_revenge() -> U32:
  663

def moves_reversal() -> U32:
  664

def moves_revivalblessing() -> U32:
  665

def moves_risingvoltage() -> U32:
  666

def moves_roar() -> U32:
  667

def moves_roaroftime() -> U32:
  668

def moves_rockblast() -> U32:
  669

def moves_rockclimb() -> U32:
  670

def moves_rockpolish() -> U32:
  671

def moves_rockslide() -> U32:
  672

def moves_rocksmash() -> U32:
  673

def moves_rockthrow() -> U32:
  674

def moves_rocktomb() -> U32:
  675

def moves_rockwrecker() -> U32:
  676

def moves_roleplay() -> U32:
  677

def moves_rollingkick() -> U32:
  678

def moves_rollout() -> U32:
  679

def moves_roost() -> U32:
  680

def moves_rototiller() -> U32:
  681

def moves_round() -> U32:
  682

def moves_ruination() -> U32:
  683

def moves_sacredfire() -> U32:
  684

def moves_sacredsword() -> U32:
  685

def moves_safeguard() -> U32:
  686

def moves_saltcure() -> U32:
  687

def moves_sandattack() -> U32:
  688

def moves_sandsearstorm() -> U32:
  689

def moves_sandstorm() -> U32:
  690

def moves_sandtomb() -> U32:
  691

def moves_sappyseed() -> U32:
  692

def moves_savagespinout() -> U32:
  693

def moves_scald() -> U32:
  694

def moves_scaleshot() -> U32:
  695

def moves_scaryface() -> U32:
  696

def moves_scorchingsands() -> U32:
  697

def moves_scratch() -> U32:
  698

def moves_screech() -> U32:
  699

def moves_searingshot() -> U32:
  700

def moves_searingsunrazesmash() -> U32:
  701

def moves_secretpower() -> U32:
  702

def moves_secretsword() -> U32:
  703

def moves_seedbomb() -> U32:
  704

def moves_seedflare() -> U32:
  705

def moves_seismictoss() -> U32:
  706

def moves_selfdestruct() -> U32:
  707

def moves_shadowball() -> U32:
  708

def moves_shadowbone() -> U32:
  709

def moves_shadowclaw() -> U32:
  710

def moves_shadowforce() -> U32:
  711

def moves_shadowpunch() -> U32:
  712

def moves_shadowsneak() -> U32:
  713

def moves_shadowstrike() -> U32:
  714

def moves_sharpen() -> U32:
  715

def moves_shatteredpsyche() -> U32:
  716

def moves_shedtail() -> U32:
  717

def moves_sheercold() -> U32:
  718

def moves_shellsidearm() -> U32:
  719

def moves_shellsmash() -> U32:
  720

def moves_shelltrap() -> U32:
  721

def moves_shelter() -> U32:
  722

def moves_shiftgear() -> U32:
  723

def moves_shockwave() -> U32:
  724

def moves_shoreup() -> U32:
  725

def moves_signalbeam() -> U32:
  726

def moves_silktrap() -> U32:
  727

def moves_silverwind() -> U32:
  728

def moves_simplebeam() -> U32:
  729

def moves_sing() -> U32:
  730

def moves_sinisterarrowraid() -> U32:
  731

def moves_sizzlyslide() -> U32:
  732

def moves_sketch() -> U32:
  733

def moves_skillswap() -> U32:
  734

def moves_skittersmack() -> U32:
  735

def moves_skullbash() -> U32:
  736

def moves_skyattack() -> U32:
  737

def moves_skydrop() -> U32:
  738

def moves_skyuppercut() -> U32:
  739

def moves_slackoff() -> U32:
  740

def moves_slam() -> U32:
  741

def moves_slash() -> U32:
  742

def moves_sleeppowder() -> U32:
  743

def moves_sleeptalk() -> U32:
  744

def moves_sludge() -> U32:
  745

def moves_sludgebomb() -> U32:
  746

def moves_sludgewave() -> U32:
  747

def moves_smackdown() -> U32:
  748

def moves_smartstrike() -> U32:
  749

def moves_smellingsalts() -> U32:
  750

def moves_smog() -> U32:
  751

def moves_smokescreen() -> U32:
  752

def moves_snaptrap() -> U32:
  753

def moves_snarl() -> U32:
  754

def moves_snatch() -> U32:
  755

def moves_snipeshot() -> U32:
  756

def moves_snore() -> U32:
  757

def moves_snowscape() -> U32:
  758

def moves_soak() -> U32:
  759

def moves_softboiled() -> U32:
  760

def moves_solarbeam() -> U32:
  761

def moves_solarblade() -> U32:
  762

def moves_sonicboom() -> U32:
  763

def moves_soulstealing7starstrike() -> U32:
  764

def moves_spacialrend() -> U32:
  765

def moves_spark() -> U32:
  766

def moves_sparklingaria() -> U32:
  767

def moves_sparklyswirl() -> U32:
  768

def moves_spectralthief() -> U32:
  769

def moves_speedswap() -> U32:
  770

def moves_spicyextract() -> U32:
  771

def moves_spiderweb() -> U32:
  772

def moves_spikecannon() -> U32:
  773

def moves_spikes() -> U32:
  774

def moves_spikyshield() -> U32:
  775

def moves_spinout() -> U32:
  776

def moves_spiritbreak() -> U32:
  777

def moves_spiritshackle() -> U32:
  778

def moves_spite() -> U32:
  779

def moves_spitup() -> U32:
  780

def moves_splash() -> U32:
  781

def moves_splinteredstormshards() -> U32:
  782

def moves_splishysplash() -> U32:
  783

def moves_spore() -> U32:
  784

def moves_spotlight() -> U32:
  785

def moves_springtidestorm() -> U32:
  786

def moves_stealthrock() -> U32:
  787

def moves_steameruption() -> U32:
  788

def moves_steamroller() -> U32:
  789

def moves_steelbeam() -> U32:
  790

def moves_steelroller() -> U32:
  791

def moves_steelwing() -> U32:
  792

def moves_stickyweb() -> U32:
  793

def moves_stockpile() -> U32:
  794

def moves_stokedsparksurfer() -> U32:
  795

def moves_stomp() -> U32:
  796

def moves_stompingtantrum() -> U32:
  797

def moves_stoneaxe() -> U32:
  798

def moves_stoneedge() -> U32:
  799

def moves_storedpower() -> U32:
  800

def moves_stormthrow() -> U32:
  801

def moves_strangesteam() -> U32:
  802

def moves_strength() -> U32:
  803

def moves_strengthsap() -> U32:
  804

def moves_stringshot() -> U32:
  805

def moves_struggle() -> U32:
  806

def moves_strugglebug() -> U32:
  807

def moves_stuffcheeks() -> U32:
  808

def moves_stunspore() -> U32:
  809

def moves_submission() -> U32:
  810

def moves_substitute() -> U32:
  811

def moves_subzeroslammer() -> U32:
  812

def moves_suckerpunch() -> U32:
  813

def moves_sunnyday() -> U32:
  814

def moves_sunsteelstrike() -> U32:
  815

def moves_supercellslam() -> U32:
  816

def moves_superfang() -> U32:
  817

def moves_superpower() -> U32:
  818

def moves_supersonic() -> U32:
  819

def moves_supersonicskystrike() -> U32:
  820

def moves_surf() -> U32:
  821

def moves_surgingstrikes() -> U32:
  822

def moves_swagger() -> U32:
  823

def moves_swallow() -> U32:
  824

def moves_sweetkiss() -> U32:
  825

def moves_sweetscent() -> U32:
  826

def moves_swift() -> U32:
  827

def moves_switcheroo() -> U32:
  828

def moves_swordsdance() -> U32:
  829

def moves_synchronoise() -> U32:
  830

def moves_synthesis() -> U32:
  831

def moves_syrupbomb() -> U32:
  832

def moves_tachyoncutter() -> U32:
  833

def moves_tackle() -> U32:
  834

def moves_tailglow() -> U32:
  835

def moves_tailslap() -> U32:
  836

def moves_tailwhip() -> U32:
  837

def moves_tailwind() -> U32:
  838

def moves_takedown() -> U32:
  839

def moves_takeheart() -> U32:
  840

def moves_tarshot() -> U32:
  841

def moves_taunt() -> U32:
  842

def moves_tearfullook() -> U32:
  843

def moves_teatime() -> U32:
  844

def moves_technoblast() -> U32:
  845

def moves_tectonicrage() -> U32:
  846

def moves_teeterdance() -> U32:
  847

def moves_telekinesis() -> U32:
  848

def moves_teleport() -> U32:
  849

def moves_temperflare() -> U32:
  850

def moves_terablast() -> U32:
  851

def moves_terastarstorm() -> U32:
  852

def moves_terrainpulse() -> U32:
  853

def moves_thief() -> U32:
  854

def moves_thousandarrows() -> U32:
  855

def moves_thousandwaves() -> U32:
  856

def moves_thrash() -> U32:
  857

def moves_throatchop() -> U32:
  858

def moves_thunder() -> U32:
  859

def moves_thunderbolt() -> U32:
  860

def moves_thundercage() -> U32:
  861

def moves_thunderclap() -> U32:
  862

def moves_thunderfang() -> U32:
  863

def moves_thunderouskick() -> U32:
  864

def moves_thunderpunch() -> U32:
  865

def moves_thundershock() -> U32:
  866

def moves_thunderwave() -> U32:
  867

def moves_tickle() -> U32:
  868

def moves_tidyup() -> U32:
  869

def moves_topsyturvy() -> U32:
  870

def moves_torchsong() -> U32:
  871

def moves_torment() -> U32:
  872

def moves_toxic() -> U32:
  873

def moves_toxicspikes() -> U32:
  874

def moves_toxicthread() -> U32:
  875

def moves_trailblaze() -> U32:
  876

def moves_transform() -> U32:
  877

def moves_triattack() -> U32:
  878

def moves_trick() -> U32:
  879

def moves_trickortreat() -> U32:
  880

def moves_trickroom() -> U32:
  881

def moves_triplearrows() -> U32:
  882

def moves_tripleaxel() -> U32:
  883

def moves_tripledive() -> U32:
  884

def moves_triplekick() -> U32:
  885

def moves_tropkick() -> U32:
  886

def moves_trumpcard() -> U32:
  887

def moves_twinbeam() -> U32:
  888

def moves_twineedle() -> U32:
  889

def moves_twinkletackle() -> U32:
  890

def moves_twister() -> U32:
  891

def moves_upperhand() -> U32:
  892

def moves_uproar() -> U32:
  893

def moves_uturn() -> U32:
  894

def moves_vacuumwave() -> U32:
  895

def moves_vcreate() -> U32:
  896

def moves_veeveevolley() -> U32:
  897

def moves_venomdrench() -> U32:
  898

def moves_venoshock() -> U32:
  899

def moves_victorydance() -> U32:
  900

def moves_vinewhip() -> U32:
  901

def moves_visegrip() -> U32:
  902

def moves_vitalthrow() -> U32:
  903

def moves_voltswitch() -> U32:
  904

def moves_volttackle() -> U32:
  905

def moves_wakeupslap() -> U32:
  906

def moves_waterfall() -> U32:
  907

def moves_watergun() -> U32:
  908

def moves_waterpledge() -> U32:
  909

def moves_waterpulse() -> U32:
  910

def moves_watershuriken() -> U32:
  911

def moves_watersport() -> U32:
  912

def moves_waterspout() -> U32:
  913

def moves_wavecrash() -> U32:
  914

def moves_weatherball() -> U32:
  915

def moves_whirlpool() -> U32:
  916

def moves_whirlwind() -> U32:
  917

def moves_wickedblow() -> U32:
  918

def moves_wickedtorque() -> U32:
  919

def moves_wideguard() -> U32:
  920

def moves_wildboltstorm() -> U32:
  921

def moves_wildcharge() -> U32:
  922

def moves_willowisp() -> U32:
  923

def moves_wingattack() -> U32:
  924

def moves_wish() -> U32:
  925

def moves_withdraw() -> U32:
  926

def moves_wonderroom() -> U32:
  927

def moves_woodhammer() -> U32:
  928

def moves_workup() -> U32:
  929

def moves_worryseed() -> U32:
  930

def moves_wrap() -> U32:
  931

def moves_wringout() -> U32:
  932

def moves_xscissor() -> U32:
  933

def moves_yawn() -> U32:
  934

def moves_zapcannon() -> U32:
  935

def moves_zenheadbutt() -> U32:
  936

def moves_zingzap() -> U32:
  937

def moves_zippyzap() -> U32:
  938
