# Generated stable IDs from Showdown 9fb3a5b99f1a0bea17f495c5cc1bfe04fdd19c3e
import Base

def roles_avpivot() -> U32:
  1

def roles_bulkyattacker() -> U32:
  2

def roles_bulkysetup() -> U32:
  3

def roles_bulkysupport() -> U32:
  4

def roles_fastattacker() -> U32:
  5

def roles_fastbulkysetup() -> U32:
  6

def roles_fastsupport() -> U32:
  7

def roles_setupsweeper() -> U32:
  8

def roles_terablastuser() -> U32:
  9

def roles_wallbreaker() -> U32:
  10
