# Generated stable IDs from Showdown 9fb3a5b99f1a0bea17f495c5cc1bfe04fdd19c3e
import Base

def species_ababo() -> U32:
  1

def species_abomasnow() -> U32:
  2

def species_abomasnowmega() -> U32:
  3

def species_abra() -> U32:
  4

def species_absol() -> U32:
  5

def species_absolmega() -> U32:
  6

def species_absolmegaz() -> U32:
  7

def species_accelgor() -> U32:
  8

def species_aegislash() -> U32:
  9

def species_aegislashblade() -> U32:
  10

def species_aerodactyl() -> U32:
  11

def species_aerodactylmega() -> U32:
  12

def species_aggron() -> U32:
  13

def species_aggronmega() -> U32:
  14

def species_aipom() -> U32:
  15

def species_alakazam() -> U32:
  16

def species_alakazammega() -> U32:
  17

def species_alcremie() -> U32:
  18

def species_alcremiecaramelswirl() -> U32:
  19

def species_alcremiegmax() -> U32:
  20

def species_alcremielemoncream() -> U32:
  21

def species_alcremiematchacream() -> U32:
  22

def species_alcremiemintcream() -> U32:
  23

def species_alcremierainbowswirl() -> U32:
  24

def species_alcremierubycream() -> U32:
  25

def species_alcremierubyswirl() -> U32:
  26

def species_alcremiesaltedcream() -> U32:
  27

def species_alomomola() -> U32:
  28

def species_altaria() -> U32:
  29

def species_altariamega() -> U32:
  30

def species_amaura() -> U32:
  31

def species_ambipom() -> U32:
  32

def species_amoonguss() -> U32:
  33

def species_ampharos() -> U32:
  34

def species_ampharosmega() -> U32:
  35

def species_annihilape() -> U32:
  36

def species_anorith() -> U32:
  37

def species_appletun() -> U32:
  38

def species_appletungmax() -> U32:
  39

def species_applin() -> U32:
  40

def species_araquanid() -> U32:
  41

def species_araquanidtotem() -> U32:
  42

def species_arbok() -> U32:
  43

def species_arboliva() -> U32:
  44

def species_arcanine() -> U32:
  45

def species_arcaninehisui() -> U32:
  46

def species_arceus() -> U32:
  47

def species_arceusbug() -> U32:
  48

def species_arceusdark() -> U32:
  49

def species_arceusdragon() -> U32:
  50

def species_arceuselectric() -> U32:
  51

def species_arceusfairy() -> U32:
  52

def species_arceusfighting() -> U32:
  53

def species_arceusfire() -> U32:
  54

def species_arceusflying() -> U32:
  55

def species_arceusghost() -> U32:
  56

def species_arceusgrass() -> U32:
  57

def species_arceusground() -> U32:
  58

def species_arceusice() -> U32:
  59

def species_arceuspoison() -> U32:
  60

def species_arceuspsychic() -> U32:
  61

def species_arceusrock() -> U32:
  62

def species_arceussteel() -> U32:
  63

def species_arceuswater() -> U32:
  64

def species_archaludon() -> U32:
  65

def species_archen() -> U32:
  66

def species_archeops() -> U32:
  67

def species_arctibax() -> U32:
  68

def species_arctovish() -> U32:
  69

def species_arctozolt() -> U32:
  70

def species_argalis() -> U32:
  71

def species_arghonaut() -> U32:
  72

def species_ariados() -> U32:
  73

def species_armaldo() -> U32:
  74

def species_armarouge() -> U32:
  75

def species_aromatisse() -> U32:
  76

def species_aron() -> U32:
  77

def species_arrokuda() -> U32:
  78

def species_articuno() -> U32:
  79

def species_articunogalar() -> U32:
  80

def species_astrolotl() -> U32:
  81

def species_audino() -> U32:
  82

def species_audinomega() -> U32:
  83

def species_aurorus() -> U32:
  84

def species_aurumoth() -> U32:
  85

def species_avalugg() -> U32:
  86

def species_avalugghisui() -> U32:
  87

def species_axew() -> U32:
  88

def species_azelf() -> U32:
  89

def species_azumarill() -> U32:
  90

def species_azurill() -> U32:
  91

def species_bagon() -> U32:
  92

def species_baltoy() -> U32:
  93

def species_banette() -> U32:
  94

def species_banettemega() -> U32:
  95

def species_barbaracle() -> U32:
  96

def species_barbaraclemega() -> U32:
  97

def species_barboach() -> U32:
  98

def species_barraskewda() -> U32:
  99

def species_basculegion() -> U32:
  100

def species_basculegionf() -> U32:
  101

def species_basculin() -> U32:
  102

def species_basculinbluestriped() -> U32:
  103

def species_basculinwhitestriped() -> U32:
  104

def species_bastiodon() -> U32:
  105

def species_baxcalibur() -> U32:
  106

def species_baxcaliburmega() -> U32:
  107

def species_bayleef() -> U32:
  108

def species_beartic() -> U32:
  109

def species_beautifly() -> U32:
  110

def species_beedrill() -> U32:
  111

def species_beedrillmega() -> U32:
  112

def species_beheeyem() -> U32:
  113

def species_beldum() -> U32:
  114

def species_bellibolt() -> U32:
  115

def species_bellossom() -> U32:
  116

def species_bellsprout() -> U32:
  117

def species_bergmite() -> U32:
  118

def species_bewear() -> U32:
  119

def species_bibarel() -> U32:
  120

def species_bidoof() -> U32:
  121

def species_binacle() -> U32:
  122

def species_bisharp() -> U32:
  123

def species_blacephalon() -> U32:
  124

def species_blastoise() -> U32:
  125

def species_blastoisegmax() -> U32:
  126

def species_blastoisemega() -> U32:
  127

def species_blaziken() -> U32:
  128

def species_blazikenmega() -> U32:
  129

def species_blipbug() -> U32:
  130

def species_blissey() -> U32:
  131

def species_blitzle() -> U32:
  132

def species_boldore() -> U32:
  133

def species_boltund() -> U32:
  134

def species_bombirdier() -> U32:
  135

def species_bonsly() -> U32:
  136

def species_bouffalant() -> U32:
  137

def species_bounsweet() -> U32:
  138

def species_braixen() -> U32:
  139

def species_brambleghast() -> U32:
  140

def species_bramblin() -> U32:
  141

def species_brattler() -> U32:
  142

def species_braviary() -> U32:
  143

def species_braviaryhisui() -> U32:
  144

def species_breezi() -> U32:
  145

def species_breloom() -> U32:
  146

def species_brionne() -> U32:
  147

def species_bronzong() -> U32:
  148

def species_bronzor() -> U32:
  149

def species_brutebonnet() -> U32:
  150

def species_bruxish() -> U32:
  151

def species_budew() -> U32:
  152

def species_buizel() -> U32:
  153

def species_bulbasaur() -> U32:
  154

def species_buneary() -> U32:
  155

def species_bunnelby() -> U32:
  156

def species_burmy() -> U32:
  157

def species_burmysandy() -> U32:
  158

def species_burmytrash() -> U32:
  159

def species_butterfree() -> U32:
  160

def species_butterfreegmax() -> U32:
  161

def species_buzzwole() -> U32:
  162

def species_cacnea() -> U32:
  163

def species_cacturne() -> U32:
  164

def species_caimanoe() -> U32:
  165

def species_calyrex() -> U32:
  166

def species_calyrexice() -> U32:
  167

def species_calyrexshadow() -> U32:
  168

def species_camerupt() -> U32:
  169

def species_cameruptmega() -> U32:
  170

def species_capsakid() -> U32:
  171

def species_carbink() -> U32:
  172

def species_caribolt() -> U32:
  173

def species_carkol() -> U32:
  174

def species_carnivine() -> U32:
  175

def species_carracosta() -> U32:
  176

def species_carvanha() -> U32:
  177

def species_cascoon() -> U32:
  178

def species_castform() -> U32:
  179

def species_castformrainy() -> U32:
  180

def species_castformsnowy() -> U32:
  181

def species_castformsunny() -> U32:
  182

def species_caterpie() -> U32:
  183

def species_cawdet() -> U32:
  184

def species_cawmodore() -> U32:
  185

def species_celebi() -> U32:
  186

def species_celesteela() -> U32:
  187

def species_centiskorch() -> U32:
  188

def species_centiskorchgmax() -> U32:
  189

def species_ceruledge() -> U32:
  190

def species_cetitan() -> U32:
  191

def species_cetoddle() -> U32:
  192

def species_chandelure() -> U32:
  193

def species_chandeluremega() -> U32:
  194

def species_chansey() -> U32:
  195

def species_charcadet() -> U32:
  196

def species_charizard() -> U32:
  197

def species_charizardgmax() -> U32:
  198

def species_charizardmegax() -> U32:
  199

def species_charizardmegay() -> U32:
  200

def species_charjabug() -> U32:
  201

def species_charmander() -> U32:
  202

def species_charmeleon() -> U32:
  203

def species_chatot() -> U32:
  204

def species_cherrim() -> U32:
  205

def species_cherrimsunshine() -> U32:
  206

def species_cherubi() -> U32:
  207

def species_chesnaught() -> U32:
  208

def species_chesnaughtmega() -> U32:
  209

def species_chespin() -> U32:
  210

def species_chewtle() -> U32:
  211

def species_chienpao() -> U32:
  212

def species_chikorita() -> U32:
  213

def species_chimchar() -> U32:
  214

def species_chimecho() -> U32:
  215

def species_chimechomega() -> U32:
  216

def species_chinchou() -> U32:
  217

def species_chingling() -> U32:
  218

def species_chiyu() -> U32:
  219

def species_chromera() -> U32:
  220

def species_chuggalong() -> U32:
  221

def species_chuggon() -> U32:
  222

def species_cinccino() -> U32:
  223

def species_cinderace() -> U32:
  224

def species_cinderacegmax() -> U32:
  225

def species_clamperl() -> U32:
  226

def species_clauncher() -> U32:
  227

def species_clawitzer() -> U32:
  228

def species_claydol() -> U32:
  229

def species_clefable() -> U32:
  230

def species_clefablemega() -> U32:
  231

def species_clefairy() -> U32:
  232

def species_cleffa() -> U32:
  233

def species_clobbopus() -> U32:
  234

def species_clodsire() -> U32:
  235

def species_cloyster() -> U32:
  236

def species_coalossal() -> U32:
  237

def species_coalossalgmax() -> U32:
  238

def species_cobalion() -> U32:
  239

def species_cofagrigus() -> U32:
  240

def species_colossoil() -> U32:
  241

def species_combee() -> U32:
  242

def species_combusken() -> U32:
  243

def species_comfey() -> U32:
  244

def species_conkeldurr() -> U32:
  245

def species_copperajah() -> U32:
  246

def species_copperajahgmax() -> U32:
  247

def species_coribalis() -> U32:
  248

def species_corphish() -> U32:
  249

def species_corsola() -> U32:
  250

def species_corsolagalar() -> U32:
  251

def species_corviknight() -> U32:
  252

def species_corviknightgmax() -> U32:
  253

def species_corvisquire() -> U32:
  254

def species_cosmoem() -> U32:
  255

def species_cosmog() -> U32:
  256

def species_cottonee() -> U32:
  257

def species_crabominable() -> U32:
  258

def species_crabominablemega() -> U32:
  259

def species_crabrawler() -> U32:
  260

def species_cradily() -> U32:
  261

def species_cramorant() -> U32:
  262

def species_cramorantgorging() -> U32:
  263

def species_cramorantgulping() -> U32:
  264

def species_cranidos() -> U32:
  265

def species_crawdaunt() -> U32:
  266

def species_cresceidon() -> U32:
  267

def species_cresselia() -> U32:
  268

def species_croagunk() -> U32:
  269

def species_crobat() -> U32:
  270

def species_crocalor() -> U32:
  271

def species_croconaw() -> U32:
  272

def species_crucibelle() -> U32:
  273

def species_crucibellemega() -> U32:
  274

def species_crustle() -> U32:
  275

def species_cryogonal() -> U32:
  276

def species_cubchoo() -> U32:
  277

def species_cubone() -> U32:
  278

def species_cufant() -> U32:
  279

def species_cupra() -> U32:
  280

def species_cursola() -> U32:
  281

def species_cutiefly() -> U32:
  282

def species_cyclizar() -> U32:
  283

def species_cyclohm() -> U32:
  284

def species_cyndaquil() -> U32:
  285

def species_dachsbun() -> U32:
  286

def species_darkrai() -> U32:
  287

def species_darkraimega() -> U32:
  288

def species_darmanitan() -> U32:
  289

def species_darmanitangalar() -> U32:
  290

def species_darmanitangalarzen() -> U32:
  291

def species_darmanitanzen() -> U32:
  292

def species_dartrix() -> U32:
  293

def species_darumaka() -> U32:
  294

def species_darumakagalar() -> U32:
  295

def species_decidueye() -> U32:
  296

def species_decidueyehisui() -> U32:
  297

def species_dedenne() -> U32:
  298

def species_deerling() -> U32:
  299

def species_deerlingautumn() -> U32:
  300

def species_deerlingsummer() -> U32:
  301

def species_deerlingwinter() -> U32:
  302

def species_deino() -> U32:
  303

def species_delcatty() -> U32:
  304

def species_delibird() -> U32:
  305

def species_delphox() -> U32:
  306

def species_delphoxmega() -> U32:
  307

def species_deoxys() -> U32:
  308

def species_deoxysattack() -> U32:
  309

def species_deoxysdefense() -> U32:
  310

def species_deoxysspeed() -> U32:
  311

def species_dewgong() -> U32:
  312

def species_dewott() -> U32:
  313

def species_dewpider() -> U32:
  314

def species_dhelmise() -> U32:
  315

def species_dialga() -> U32:
  316

def species_dialgaorigin() -> U32:
  317

def species_diancie() -> U32:
  318

def species_dianciemega() -> U32:
  319

def species_diggersby() -> U32:
  320

def species_diglett() -> U32:
  321

def species_diglettalola() -> U32:
  322

def species_dipplin() -> U32:
  323

def species_ditto() -> U32:
  324

def species_dodrio() -> U32:
  325

def species_doduo() -> U32:
  326

def species_dolliv() -> U32:
  327

def species_dondozo() -> U32:
  328

def species_donphan() -> U32:
  329

def species_dorsoil() -> U32:
  330

def species_dottler() -> U32:
  331

def species_doublade() -> U32:
  332

def species_dracovish() -> U32:
  333

def species_dracozolt() -> U32:
  334

def species_dragalge() -> U32:
  335

def species_dragalgemega() -> U32:
  336

def species_dragapult() -> U32:
  337

def species_draggalong() -> U32:
  338

def species_dragonair() -> U32:
  339

def species_dragonite() -> U32:
  340

def species_dragonitemega() -> U32:
  341

def species_drakloak() -> U32:
  342

def species_drampa() -> U32:
  343

def species_drampamega() -> U32:
  344

def species_drapion() -> U32:
  345

def species_dratini() -> U32:
  346

def species_drednaw() -> U32:
  347

def species_drednawgmax() -> U32:
  348

def species_dreepy() -> U32:
  349

def species_drifblim() -> U32:
  350

def species_drifloon() -> U32:
  351

def species_drilbur() -> U32:
  352

def species_drizzile() -> U32:
  353

def species_drowzee() -> U32:
  354

def species_druddigon() -> U32:
  355

def species_dubwool() -> U32:
  356

def species_ducklett() -> U32:
  357

def species_dudunsparce() -> U32:
  358

def species_dudunsparcethreesegment() -> U32:
  359

def species_dugtrio() -> U32:
  360

def species_dugtrioalola() -> U32:
  361

def species_dunsparce() -> U32:
  362

def species_duohm() -> U32:
  363

def species_duosion() -> U32:
  364

def species_duraludon() -> U32:
  365

def species_duraludongmax() -> U32:
  366

def species_durant() -> U32:
  367

def species_dusclops() -> U32:
  368

def species_dusknoir() -> U32:
  369

def species_duskull() -> U32:
  370

def species_dustox() -> U32:
  371

def species_dwebble() -> U32:
  372

def species_eelektrik() -> U32:
  373

def species_eelektross() -> U32:
  374

def species_eelektrossmega() -> U32:
  375

def species_eevee() -> U32:
  376

def species_eeveegmax() -> U32:
  377

def species_eeveestarter() -> U32:
  378

def species_eiscue() -> U32:
  379

def species_eiscuenoice() -> U32:
  380

def species_ekans() -> U32:
  381

def species_eldegoss() -> U32:
  382

def species_electabuzz() -> U32:
  383

def species_electivire() -> U32:
  384

def species_electrelk() -> U32:
  385

def species_electrike() -> U32:
  386

def species_electrode() -> U32:
  387

def species_electrodehisui() -> U32:
  388

def species_elekid() -> U32:
  389

def species_elgyem() -> U32:
  390

def species_embirch() -> U32:
  391

def species_emboar() -> U32:
  392

def species_emboarmega() -> U32:
  393

def species_emolga() -> U32:
  394

def species_empoleon() -> U32:
  395

def species_enamorus() -> U32:
  396

def species_enamorustherian() -> U32:
  397

def species_entei() -> U32:
  398

def species_equilibra() -> U32:
  399

def species_escavalier() -> U32:
  400

def species_espathra() -> U32:
  401

def species_espeon() -> U32:
  402

def species_espurr() -> U32:
  403

def species_eternatus() -> U32:
  404

def species_eternatuseternamax() -> U32:
  405

def species_excadrill() -> U32:
  406

def species_excadrillmega() -> U32:
  407

def species_exeggcute() -> U32:
  408

def species_exeggutor() -> U32:
  409

def species_exeggutoralola() -> U32:
  410

def species_exploud() -> U32:
  411

def species_falinks() -> U32:
  412

def species_falinksmega() -> U32:
  413

def species_farfetchd() -> U32:
  414

def species_farfetchdgalar() -> U32:
  415

def species_farigiraf() -> U32:
  416

def species_fawnifer() -> U32:
  417

def species_fearow() -> U32:
  418

def species_feebas() -> U32:
  419

def species_fennekin() -> U32:
  420

def species_feraligatr() -> U32:
  421

def species_feraligatrmega() -> U32:
  422

def species_ferroseed() -> U32:
  423

def species_ferrothorn() -> U32:
  424

def species_fezandipiti() -> U32:
  425

def species_fidgit() -> U32:
  426

def species_fidough() -> U32:
  427

def species_finizen() -> U32:
  428

def species_finneon() -> U32:
  429

def species_flaaffy() -> U32:
  430

def species_flabebe() -> U32:
  431

def species_flabebeblue() -> U32:
  432

def species_flabebeorange() -> U32:
  433

def species_flabebewhite() -> U32:
  434

def species_flabebeyellow() -> U32:
  435

def species_flamigo() -> U32:
  436

def species_flapple() -> U32:
  437

def species_flapplegmax() -> U32:
  438

def species_flarelm() -> U32:
  439

def species_flareon() -> U32:
  440

def species_fletchinder() -> U32:
  441

def species_fletchling() -> U32:
  442

def species_flittle() -> U32:
  443

def species_floatoy() -> U32:
  444

def species_floatzel() -> U32:
  445

def species_floette() -> U32:
  446

def species_floetteblue() -> U32:
  447

def species_floetteeternal() -> U32:
  448

def species_floettemega() -> U32:
  449

def species_floetteorange() -> U32:
  450

def species_floettewhite() -> U32:
  451

def species_floetteyellow() -> U32:
  452

def species_floragato() -> U32:
  453

def species_florges() -> U32:
  454

def species_florgesblue() -> U32:
  455

def species_florgesorange() -> U32:
  456

def species_florgeswhite() -> U32:
  457

def species_florgesyellow() -> U32:
  458

def species_flox() -> U32:
  459

def species_fluttermane() -> U32:
  460

def species_flygon() -> U32:
  461

def species_fomantis() -> U32:
  462

def species_foongus() -> U32:
  463

def species_forretress() -> U32:
  464

def species_fraxure() -> U32:
  465

def species_frigibax() -> U32:
  466

def species_frillish() -> U32:
  467

def species_froakie() -> U32:
  468

def species_frogadier() -> U32:
  469

def species_froslass() -> U32:
  470

def species_froslassmega() -> U32:
  471

def species_frosmoth() -> U32:
  472

def species_fuecoco() -> U32:
  473

def species_furfrou() -> U32:
  474

def species_furfroudandy() -> U32:
  475

def species_furfroudebutante() -> U32:
  476

def species_furfroudiamond() -> U32:
  477

def species_furfrouheart() -> U32:
  478

def species_furfroukabuki() -> U32:
  479

def species_furfroulareine() -> U32:
  480

def species_furfroumatron() -> U32:
  481

def species_furfroupharaoh() -> U32:
  482

def species_furfroustar() -> U32:
  483

def species_furret() -> U32:
  484

def species_gabite() -> U32:
  485

def species_gallade() -> U32:
  486

def species_gallademega() -> U32:
  487

def species_galvantula() -> U32:
  488

def species_garbodor() -> U32:
  489

def species_garbodorgmax() -> U32:
  490

def species_garchomp() -> U32:
  491

def species_garchompmega() -> U32:
  492

def species_garchompmegaz() -> U32:
  493

def species_gardevoir() -> U32:
  494

def species_gardevoirmega() -> U32:
  495

def species_garganacl() -> U32:
  496

def species_gastly() -> U32:
  497

def species_gastrodon() -> U32:
  498

def species_gastrodoneast() -> U32:
  499

def species_genesect() -> U32:
  500

def species_genesectburn() -> U32:
  501

def species_genesectchill() -> U32:
  502

def species_genesectdouse() -> U32:
  503

def species_genesectshock() -> U32:
  504

def species_gengar() -> U32:
  505

def species_gengargmax() -> U32:
  506

def species_gengarmega() -> U32:
  507

def species_geodude() -> U32:
  508

def species_geodudealola() -> U32:
  509

def species_gholdengo() -> U32:
  510

def species_gible() -> U32:
  511

def species_gigalith() -> U32:
  512

def species_gimmighoul() -> U32:
  513

def species_gimmighoulroaming() -> U32:
  514

def species_girafarig() -> U32:
  515

def species_giratina() -> U32:
  516

def species_giratinaorigin() -> U32:
  517

def species_glaceon() -> U32:
  518

def species_glalie() -> U32:
  519

def species_glaliemega() -> U32:
  520

def species_glameow() -> U32:
  521

def species_glastrier() -> U32:
  522

def species_gligar() -> U32:
  523

def species_glimmet() -> U32:
  524

def species_glimmora() -> U32:
  525

def species_glimmoramega() -> U32:
  526

def species_gliscor() -> U32:
  527

def species_gloom() -> U32:
  528

def species_gogoat() -> U32:
  529

def species_golbat() -> U32:
  530

def species_goldeen() -> U32:
  531

def species_golduck() -> U32:
  532

def species_golem() -> U32:
  533

def species_golemalola() -> U32:
  534

def species_golett() -> U32:
  535

def species_golisopod() -> U32:
  536

def species_golisopodmega() -> U32:
  537

def species_golurk() -> U32:
  538

def species_golurkmega() -> U32:
  539

def species_goodra() -> U32:
  540

def species_goodrahisui() -> U32:
  541

def species_goomy() -> U32:
  542

def species_gorebyss() -> U32:
  543

def species_gossifleur() -> U32:
  544

def species_gothita() -> U32:
  545

def species_gothitelle() -> U32:
  546

def species_gothorita() -> U32:
  547

def species_gougingfire() -> U32:
  548

def species_gourgeist() -> U32:
  549

def species_gourgeistlarge() -> U32:
  550

def species_gourgeistsmall() -> U32:
  551

def species_gourgeistsuper() -> U32:
  552

def species_grafaiai() -> U32:
  553

def species_granbull() -> U32:
  554

def species_grapploct() -> U32:
  555

def species_graveler() -> U32:
  556

def species_graveleralola() -> U32:
  557

def species_greattusk() -> U32:
  558

def species_greavard() -> U32:
  559

def species_greedent() -> U32:
  560

def species_greninja() -> U32:
  561

def species_greninjaash() -> U32:
  562

def species_greninjabond() -> U32:
  563

def species_greninjamega() -> U32:
  564

def species_grimer() -> U32:
  565

def species_grimeralola() -> U32:
  566

def species_grimmsnarl() -> U32:
  567

def species_grimmsnarlgmax() -> U32:
  568

def species_grookey() -> U32:
  569

def species_grotle() -> U32:
  570

def species_groudon() -> U32:
  571

def species_groudonprimal() -> U32:
  572

def species_grovyle() -> U32:
  573

def species_growlithe() -> U32:
  574

def species_growlithehisui() -> U32:
  575

def species_grubbin() -> U32:
  576

def species_grumpig() -> U32:
  577

def species_gulpin() -> U32:
  578

def species_gumshoos() -> U32:
  579

def species_gumshoostotem() -> U32:
  580

def species_gurdurr() -> U32:
  581

def species_guzzlord() -> U32:
  582

def species_gyarados() -> U32:
  583

def species_gyaradosmega() -> U32:
  584

def species_hakamoo() -> U32:
  585

def species_happiny() -> U32:
  586

def species_hariyama() -> U32:
  587

def species_hatenna() -> U32:
  588

def species_hatterene() -> U32:
  589

def species_hatterenegmax() -> U32:
  590

def species_hattrem() -> U32:
  591

def species_haunter() -> U32:
  592

def species_hawlucha() -> U32:
  593

def species_hawluchamega() -> U32:
  594

def species_haxorus() -> U32:
  595

def species_heatmor() -> U32:
  596

def species_heatran() -> U32:
  597

def species_heatranmega() -> U32:
  598

def species_heliolisk() -> U32:
  599

def species_helioptile() -> U32:
  600

def species_hemogoblin() -> U32:
  601

def species_heracross() -> U32:
  602

def species_heracrossmega() -> U32:
  603

def species_herdier() -> U32:
  604

def species_hippopotas() -> U32:
  605

def species_hippowdon() -> U32:
  606

def species_hitmonchan() -> U32:
  607

def species_hitmonlee() -> U32:
  608

def species_hitmontop() -> U32:
  609

def species_honchkrow() -> U32:
  610

def species_honedge() -> U32:
  611

def species_hooh() -> U32:
  612

def species_hoopa() -> U32:
  613

def species_hoopaunbound() -> U32:
  614

def species_hoothoot() -> U32:
  615

def species_hoppip() -> U32:
  616

def species_horsea() -> U32:
  617

def species_houndoom() -> U32:
  618

def species_houndoommega() -> U32:
  619

def species_houndour() -> U32:
  620

def species_houndstone() -> U32:
  621

def species_huntail() -> U32:
  622

def species_hydrapple() -> U32:
  623

def species_hydreigon() -> U32:
  624

def species_hypno() -> U32:
  625

def species_igglybuff() -> U32:
  626

def species_illumise() -> U32:
  627

def species_impidimp() -> U32:
  628

def species_incineroar() -> U32:
  629

def species_indeedee() -> U32:
  630

def species_indeedeef() -> U32:
  631

def species_infernape() -> U32:
  632

def species_inkay() -> U32:
  633

def species_inteleon() -> U32:
  634

def species_inteleongmax() -> U32:
  635

def species_ironboulder() -> U32:
  636

def species_ironbundle() -> U32:
  637

def species_ironcrown() -> U32:
  638

def species_ironhands() -> U32:
  639

def species_ironjugulis() -> U32:
  640

def species_ironleaves() -> U32:
  641

def species_ironmoth() -> U32:
  642

def species_ironthorns() -> U32:
  643

def species_irontreads() -> U32:
  644

def species_ironvaliant() -> U32:
  645

def species_ivysaur() -> U32:
  646

def species_jangmoo() -> U32:
  647

def species_jellicent() -> U32:
  648

def species_jigglypuff() -> U32:
  649

def species_jirachi() -> U32:
  650

def species_jolteon() -> U32:
  651

def species_joltik() -> U32:
  652

def species_jumbao() -> U32:
  653

def species_jumpluff() -> U32:
  654

def species_justyke() -> U32:
  655

def species_jynx() -> U32:
  656

def species_kabuto() -> U32:
  657

def species_kabutops() -> U32:
  658

def species_kadabra() -> U32:
  659

def species_kakuna() -> U32:
  660

def species_kangaskhan() -> U32:
  661

def species_kangaskhanmega() -> U32:
  662

def species_karrablast() -> U32:
  663

def species_kartana() -> U32:
  664

def species_kecleon() -> U32:
  665

def species_keldeo() -> U32:
  666

def species_keldeoresolute() -> U32:
  667

def species_kerfluffle() -> U32:
  668

def species_kilowattrel() -> U32:
  669

def species_kingambit() -> U32:
  670

def species_kingdra() -> U32:
  671

def species_kingler() -> U32:
  672

def species_kinglergmax() -> U32:
  673

def species_kirlia() -> U32:
  674

def species_kitsunoh() -> U32:
  675

def species_klang() -> U32:
  676

def species_klawf() -> U32:
  677

def species_kleavor() -> U32:
  678

def species_klefki() -> U32:
  679

def species_klink() -> U32:
  680

def species_klinklang() -> U32:
  681

def species_koffing() -> U32:
  682

def species_komala() -> U32:
  683

def species_kommoo() -> U32:
  684

def species_kommoototem() -> U32:
  685

def species_koraidon() -> U32:
  686

def species_krabby() -> U32:
  687

def species_kricketot() -> U32:
  688

def species_kricketune() -> U32:
  689

def species_krilowatt() -> U32:
  690

def species_krokorok() -> U32:
  691

def species_krookodile() -> U32:
  692

def species_kubfu() -> U32:
  693

def species_kyogre() -> U32:
  694

def species_kyogreprimal() -> U32:
  695

def species_kyurem() -> U32:
  696

def species_kyuremblack() -> U32:
  697

def species_kyuremwhite() -> U32:
  698

def species_lairon() -> U32:
  699

def species_lampent() -> U32:
  700

def species_landorus() -> U32:
  701

def species_landorustherian() -> U32:
  702

def species_lanturn() -> U32:
  703

def species_lapras() -> U32:
  704

def species_laprasgmax() -> U32:
  705

def species_larvesta() -> U32:
  706

def species_larvitar() -> U32:
  707

def species_latias() -> U32:
  708

def species_latiasmega() -> U32:
  709

def species_latios() -> U32:
  710

def species_latiosmega() -> U32:
  711

def species_leafeon() -> U32:
  712

def species_leavanny() -> U32:
  713

def species_lechonk() -> U32:
  714

def species_ledian() -> U32:
  715

def species_ledyba() -> U32:
  716

def species_lickilicky() -> U32:
  717

def species_lickitung() -> U32:
  718

def species_liepard() -> U32:
  719

def species_lileep() -> U32:
  720

def species_lilligant() -> U32:
  721

def species_lilliganthisui() -> U32:
  722

def species_lillipup() -> U32:
  723

def species_linoone() -> U32:
  724

def species_linoonegalar() -> U32:
  725

def species_litleo() -> U32:
  726

def species_litten() -> U32:
  727

def species_litwick() -> U32:
  728

def species_lokix() -> U32:
  729

def species_lombre() -> U32:
  730

def species_lopunny() -> U32:
  731

def species_lopunnymega() -> U32:
  732

def species_lotad() -> U32:
  733

def species_loudred() -> U32:
  734

def species_lucario() -> U32:
  735

def species_lucariomega() -> U32:
  736

def species_lucariomegaz() -> U32:
  737

def species_ludicolo() -> U32:
  738

def species_lugia() -> U32:
  739

def species_lumineon() -> U32:
  740

def species_lunala() -> U32:
  741

def species_lunatone() -> U32:
  742

def species_lurantis() -> U32:
  743

def species_lurantistotem() -> U32:
  744

def species_luvdisc() -> U32:
  745

def species_luxio() -> U32:
  746

def species_luxray() -> U32:
  747

def species_lycanroc() -> U32:
  748

def species_lycanrocdusk() -> U32:
  749

def species_lycanrocmidnight() -> U32:
  750

def species_mabosstiff() -> U32:
  751

def species_machamp() -> U32:
  752

def species_machampgmax() -> U32:
  753

def species_machoke() -> U32:
  754

def species_machop() -> U32:
  755

def species_magby() -> U32:
  756

def species_magcargo() -> U32:
  757

def species_magearna() -> U32:
  758

def species_magearnamega() -> U32:
  759

def species_magearnaoriginal() -> U32:
  760

def species_magearnaoriginalmega() -> U32:
  761

def species_magikarp() -> U32:
  762

def species_magmar() -> U32:
  763

def species_magmortar() -> U32:
  764

def species_magnemite() -> U32:
  765

def species_magneton() -> U32:
  766

def species_magnezone() -> U32:
  767

def species_makuhita() -> U32:
  768

def species_malaconda() -> U32:
  769

def species_malamar() -> U32:
  770

def species_malamarmega() -> U32:
  771

def species_mamoswine() -> U32:
  772

def species_manaphy() -> U32:
  773

def species_mandibuzz() -> U32:
  774

def species_manectric() -> U32:
  775

def species_manectricmega() -> U32:
  776

def species_mankey() -> U32:
  777

def species_mantine() -> U32:
  778

def species_mantyke() -> U32:
  779

def species_maractus() -> U32:
  780

def species_mareanie() -> U32:
  781

def species_mareep() -> U32:
  782

def species_marill() -> U32:
  783

def species_marowak() -> U32:
  784

def species_marowakalola() -> U32:
  785

def species_marowakalolatotem() -> U32:
  786

def species_marshadow() -> U32:
  787

def species_marshtomp() -> U32:
  788

def species_maschiff() -> U32:
  789

def species_masquerain() -> U32:
  790

def species_maushold() -> U32:
  791

def species_mausholdfour() -> U32:
  792

def species_mawile() -> U32:
  793

def species_mawilemega() -> U32:
  794

def species_medicham() -> U32:
  795

def species_medichammega() -> U32:
  796

def species_meditite() -> U32:
  797

def species_meganium() -> U32:
  798

def species_meganiummega() -> U32:
  799

def species_melmetal() -> U32:
  800

def species_melmetalgmax() -> U32:
  801

def species_meloetta() -> U32:
  802

def species_meloettapirouette() -> U32:
  803

def species_meltan() -> U32:
  804

def species_meowscarada() -> U32:
  805

def species_meowstic() -> U32:
  806

def species_meowsticf() -> U32:
  807

def species_meowsticfmega() -> U32:
  808

def species_meowsticmmega() -> U32:
  809

def species_meowth() -> U32:
  810

def species_meowthalola() -> U32:
  811

def species_meowthgalar() -> U32:
  812

def species_meowthgmax() -> U32:
  813

def species_mesprit() -> U32:
  814

def species_metagross() -> U32:
  815

def species_metagrossmega() -> U32:
  816

def species_metang() -> U32:
  817

def species_metapod() -> U32:
  818

def species_mew() -> U32:
  819

def species_mewtwo() -> U32:
  820

def species_mewtwomegax() -> U32:
  821

def species_mewtwomegay() -> U32:
  822

def species_miasmaw() -> U32:
  823

def species_miasmite() -> U32:
  824

def species_mienfoo() -> U32:
  825

def species_mienshao() -> U32:
  826

def species_mightyena() -> U32:
  827

def species_milcery() -> U32:
  828

def species_milotic() -> U32:
  829

def species_miltank() -> U32:
  830

def species_mimejr() -> U32:
  831

def species_mimikyu() -> U32:
  832

def species_mimikyubusted() -> U32:
  833

def species_mimikyubustedtotem() -> U32:
  834

def species_mimikyutotem() -> U32:
  835

def species_minccino() -> U32:
  836

def species_minior() -> U32:
  837

def species_miniorblue() -> U32:
  838

def species_miniorgreen() -> U32:
  839

def species_miniorindigo() -> U32:
  840

def species_miniormeteor() -> U32:
  841

def species_miniororange() -> U32:
  842

def species_miniorviolet() -> U32:
  843

def species_minioryellow() -> U32:
  844

def species_minun() -> U32:
  845

def species_miraidon() -> U32:
  846

def species_misdreavus() -> U32:
  847

def species_mismagius() -> U32:
  848

def species_mollux() -> U32:
  849

def species_moltres() -> U32:
  850

def species_moltresgalar() -> U32:
  851

def species_monferno() -> U32:
  852

def species_monohm() -> U32:
  853

def species_morelull() -> U32:
  854

def species_morgrem() -> U32:
  855

def species_morpeko() -> U32:
  856

def species_morpekohangry() -> U32:
  857

def species_mothim() -> U32:
  858

def species_mrmime() -> U32:
  859

def species_mrmimegalar() -> U32:
  860

def species_mrrime() -> U32:
  861

def species_mudbray() -> U32:
  862

def species_mudkip() -> U32:
  863

def species_mudsdale() -> U32:
  864

def species_muk() -> U32:
  865

def species_mukalola() -> U32:
  866

def species_mumbao() -> U32:
  867

def species_munchlax() -> U32:
  868

def species_munkidori() -> U32:
  869

def species_munna() -> U32:
  870

def species_murkrow() -> U32:
  871

def species_musharna() -> U32:
  872

def species_nacli() -> U32:
  873

def species_naclstack() -> U32:
  874

def species_naganadel() -> U32:
  875

def species_natu() -> U32:
  876

def species_naviathan() -> U32:
  877

def species_necrozma() -> U32:
  878

def species_necrozmadawnwings() -> U32:
  879

def species_necrozmaduskmane() -> U32:
  880

def species_necrozmaultra() -> U32:
  881

def species_necturine() -> U32:
  882

def species_necturna() -> U32:
  883

def species_nickit() -> U32:
  884

def species_nidoking() -> U32:
  885

def species_nidoqueen() -> U32:
  886

def species_nidoranf() -> U32:
  887

def species_nidoranm() -> U32:
  888

def species_nidorina() -> U32:
  889

def species_nidorino() -> U32:
  890

def species_nihilego() -> U32:
  891

def species_nincada() -> U32:
  892

def species_ninetales() -> U32:
  893

def species_ninetalesalola() -> U32:
  894

def species_ninjask() -> U32:
  895

def species_noctowl() -> U32:
  896

def species_nohface() -> U32:
  897

def species_noibat() -> U32:
  898

def species_noivern() -> U32:
  899

def species_nosepass() -> U32:
  900

def species_numel() -> U32:
  901

def species_nuzleaf() -> U32:
  902

def species_nymble() -> U32:
  903

def species_obliteryx() -> U32:
  904

def species_obstagoon() -> U32:
  905

def species_octillery() -> U32:
  906

def species_oddish() -> U32:
  907

def species_ogerpon() -> U32:
  908

def species_ogerponcornerstone() -> U32:
  909

def species_ogerponcornerstonetera() -> U32:
  910

def species_ogerponhearthflame() -> U32:
  911

def species_ogerponhearthflametera() -> U32:
  912

def species_ogerpontealtera() -> U32:
  913

def species_ogerponwellspring() -> U32:
  914

def species_ogerponwellspringtera() -> U32:
  915

def species_oinkologne() -> U32:
  916

def species_oinkolognef() -> U32:
  917

def species_okidogi() -> U32:
  918

def species_omanyte() -> U32:
  919

def species_omastar() -> U32:
  920

def species_onix() -> U32:
  921

def species_oranguru() -> U32:
  922

def species_orbeetle() -> U32:
  923

def species_orbeetlegmax() -> U32:
  924

def species_oricorio() -> U32:
  925

def species_oricoriopau() -> U32:
  926

def species_oricoriopompom() -> U32:
  927

def species_oricoriosensu() -> U32:
  928

def species_orthworm() -> U32:
  929

def species_oshawott() -> U32:
  930

def species_overqwil() -> U32:
  931

def species_pachirisu() -> U32:
  932

def species_pajantom() -> U32:
  933

def species_palafin() -> U32:
  934

def species_palafinhero() -> U32:
  935

def species_palkia() -> U32:
  936

def species_palkiaorigin() -> U32:
  937

def species_palossand() -> U32:
  938

def species_palpitoad() -> U32:
  939

def species_pancham() -> U32:
  940

def species_pangoro() -> U32:
  941

def species_panpour() -> U32:
  942

def species_pansage() -> U32:
  943

def species_pansear() -> U32:
  944

def species_paras() -> U32:
  945

def species_parasect() -> U32:
  946

def species_passimian() -> U32:
  947

def species_patrat() -> U32:
  948

def species_pawmi() -> U32:
  949

def species_pawmo() -> U32:
  950

def species_pawmot() -> U32:
  951

def species_pawniard() -> U32:
  952

def species_pecharunt() -> U32:
  953

def species_pelipper() -> U32:
  954

def species_perrserker() -> U32:
  955

def species_persian() -> U32:
  956

def species_persianalola() -> U32:
  957

def species_petilil() -> U32:
  958

def species_phanpy() -> U32:
  959

def species_phantump() -> U32:
  960

def species_pheromosa() -> U32:
  961

def species_phione() -> U32:
  962

def species_pichu() -> U32:
  963

def species_pichuspikyeared() -> U32:
  964

def species_pidgeot() -> U32:
  965

def species_pidgeotmega() -> U32:
  966

def species_pidgeotto() -> U32:
  967

def species_pidgey() -> U32:
  968

def species_pidove() -> U32:
  969

def species_pignite() -> U32:
  970

def species_pikachu() -> U32:
  971

def species_pikachualola() -> U32:
  972

def species_pikachubelle() -> U32:
  973

def species_pikachucosplay() -> U32:
  974

def species_pikachugmax() -> U32:
  975

def species_pikachuhoenn() -> U32:
  976

def species_pikachukalos() -> U32:
  977

def species_pikachulibre() -> U32:
  978

def species_pikachuoriginal() -> U32:
  979

def species_pikachupartner() -> U32:
  980

def species_pikachuphd() -> U32:
  981

def species_pikachupopstar() -> U32:
  982

def species_pikachurockstar() -> U32:
  983

def species_pikachusinnoh() -> U32:
  984

def species_pikachustarter() -> U32:
  985

def species_pikachuunova() -> U32:
  986

def species_pikachuworld() -> U32:
  987

def species_pikipek() -> U32:
  988

def species_piloswine() -> U32:
  989

def species_pincurchin() -> U32:
  990

def species_pineco() -> U32:
  991

def species_pinsir() -> U32:
  992

def species_pinsirmega() -> U32:
  993

def species_piplup() -> U32:
  994

def species_plasmanta() -> U32:
  995

def species_pluffle() -> U32:
  996

def species_plusle() -> U32:
  997

def species_poipole() -> U32:
  998

def species_pokestarblackbelt() -> U32:
  999

def species_pokestarblackbeltprop() -> U32:
  1000

def species_pokestarblackdoor() -> U32:
  1001

def species_pokestarblackdoorprop() -> U32:
  1002

def species_pokestarbrycenman() -> U32:
  1003

def species_pokestarbrycenmanprop() -> U32:
  1004

def species_pokestarf00() -> U32:
  1005

def species_pokestarf002() -> U32:
  1006

def species_pokestarf002prop() -> U32:
  1007

def species_pokestarf00prop() -> U32:
  1008

def species_pokestargiant() -> U32:
  1009

def species_pokestargiant2() -> U32:
  1010

def species_pokestargiantpropo1() -> U32:
  1011

def species_pokestargiantpropo2() -> U32:
  1012

def species_pokestarhumanoid() -> U32:
  1013

def species_pokestarhumanoidprop() -> U32:
  1014

def species_pokestarmonster() -> U32:
  1015

def species_pokestarmonsterprop() -> U32:
  1016

def species_pokestarmt() -> U32:
  1017

def species_pokestarmt2() -> U32:
  1018

def species_pokestarmt2prop() -> U32:
  1019

def species_pokestarmtprop() -> U32:
  1020

def species_pokestarsmeargle() -> U32:
  1021

def species_pokestarspirit() -> U32:
  1022

def species_pokestarspiritprop() -> U32:
  1023

def species_pokestartransport() -> U32:
  1024

def species_pokestartransportprop() -> U32:
  1025

def species_pokestarufo() -> U32:
  1026

def species_pokestarufo2() -> U32:
  1027

def species_pokestarufopropu1() -> U32:
  1028

def species_pokestarufopropu2() -> U32:
  1029

def species_pokestarwhitedoor() -> U32:
  1030

def species_pokestarwhitedoorprop() -> U32:
  1031

def species_politoed() -> U32:
  1032

def species_poliwag() -> U32:
  1033

def species_poliwhirl() -> U32:
  1034

def species_poliwrath() -> U32:
  1035

def species_poltchageist() -> U32:
  1036

def species_poltchageistartisan() -> U32:
  1037

def species_polteageist() -> U32:
  1038

def species_polteageistantique() -> U32:
  1039

def species_ponyta() -> U32:
  1040

def species_ponytagalar() -> U32:
  1041

def species_poochyena() -> U32:
  1042

def species_popplio() -> U32:
  1043

def species_porygon() -> U32:
  1044

def species_porygon2() -> U32:
  1045

def species_porygonz() -> U32:
  1046

def species_primarina() -> U32:
  1047

def species_primeape() -> U32:
  1048

def species_prinplup() -> U32:
  1049

def species_privatyke() -> U32:
  1050

def species_probopass() -> U32:
  1051

def species_protowatt() -> U32:
  1052

def species_psyduck() -> U32:
  1053

def species_pumpkaboo() -> U32:
  1054

def species_pumpkaboolarge() -> U32:
  1055

def species_pumpkaboosmall() -> U32:
  1056

def species_pumpkaboosuper() -> U32:
  1057

def species_pupitar() -> U32:
  1058

def species_purrloin() -> U32:
  1059

def species_purugly() -> U32:
  1060

def species_pyroak() -> U32:
  1061

def species_pyroar() -> U32:
  1062

def species_pyroarmega() -> U32:
  1063

def species_pyukumuku() -> U32:
  1064

def species_quagsire() -> U32:
  1065

def species_quaquaval() -> U32:
  1066

def species_quaxly() -> U32:
  1067

def species_quaxwell() -> U32:
  1068

def species_quilava() -> U32:
  1069

def species_quilladin() -> U32:
  1070

def species_qwilfish() -> U32:
  1071

def species_qwilfishhisui() -> U32:
  1072

def species_raboot() -> U32:
  1073

def species_rabsca() -> U32:
  1074

def species_ragingbolt() -> U32:
  1075

def species_raichu() -> U32:
  1076

def species_raichualola() -> U32:
  1077

def species_raichumegax() -> U32:
  1078

def species_raichumegay() -> U32:
  1079

def species_raikou() -> U32:
  1080

def species_ralts() -> U32:
  1081

def species_ramnarok() -> U32:
  1082

def species_ramnarokradiant() -> U32:
  1083

def species_rampardos() -> U32:
  1084

def species_rapidash() -> U32:
  1085

def species_rapidashgalar() -> U32:
  1086

def species_raticate() -> U32:
  1087

def species_raticatealola() -> U32:
  1088

def species_raticatealolatotem() -> U32:
  1089

def species_rattata() -> U32:
  1090

def species_rattataalola() -> U32:
  1091

def species_rayquaza() -> U32:
  1092

def species_rayquazamega() -> U32:
  1093

def species_rebble() -> U32:
  1094

def species_regice() -> U32:
  1095

def species_regidrago() -> U32:
  1096

def species_regieleki() -> U32:
  1097

def species_regigigas() -> U32:
  1098

def species_regirock() -> U32:
  1099

def species_registeel() -> U32:
  1100

def species_relicanth() -> U32:
  1101

def species_rellor() -> U32:
  1102

def species_remoraid() -> U32:
  1103

def species_reshiram() -> U32:
  1104

def species_reuniclus() -> U32:
  1105

def species_revavroom() -> U32:
  1106

def species_revenankh() -> U32:
  1107

def species_rhydon() -> U32:
  1108

def species_rhyhorn() -> U32:
  1109

def species_rhyperior() -> U32:
  1110

def species_ribombee() -> U32:
  1111

def species_ribombeetotem() -> U32:
  1112

def species_rillaboom() -> U32:
  1113

def species_rillaboomgmax() -> U32:
  1114

def species_riolu() -> U32:
  1115

def species_roaringmoon() -> U32:
  1116

def species_rockruff() -> U32:
  1117

def species_rockruffdusk() -> U32:
  1118

def species_roggenrola() -> U32:
  1119

def species_rolycoly() -> U32:
  1120

def species_rookidee() -> U32:
  1121

def species_roselia() -> U32:
  1122

def species_roserade() -> U32:
  1123

def species_rotom() -> U32:
  1124

def species_rotomfan() -> U32:
  1125

def species_rotomfrost() -> U32:
  1126

def species_rotomheat() -> U32:
  1127

def species_rotommow() -> U32:
  1128

def species_rotomwash() -> U32:
  1129

def species_rowlet() -> U32:
  1130

def species_rufflet() -> U32:
  1131

def species_runerigus() -> U32:
  1132

def species_sableye() -> U32:
  1133

def species_sableyemega() -> U32:
  1134

def species_saharaja() -> U32:
  1135

def species_saharascal() -> U32:
  1136

def species_salamence() -> U32:
  1137

def species_salamencemega() -> U32:
  1138

def species_salandit() -> U32:
  1139

def species_salazzle() -> U32:
  1140

def species_salazzletotem() -> U32:
  1141

def species_samurott() -> U32:
  1142

def species_samurotthisui() -> U32:
  1143

def species_sandaconda() -> U32:
  1144

def species_sandacondagmax() -> U32:
  1145

def species_sandile() -> U32:
  1146

def species_sandshrew() -> U32:
  1147

def species_sandshrewalola() -> U32:
  1148

def species_sandslash() -> U32:
  1149

def species_sandslashalola() -> U32:
  1150

def species_sandygast() -> U32:
  1151

def species_sandyshocks() -> U32:
  1152

def species_sawk() -> U32:
  1153

def species_sawsbuck() -> U32:
  1154

def species_sawsbuckautumn() -> U32:
  1155

def species_sawsbucksummer() -> U32:
  1156

def species_sawsbuckwinter() -> U32:
  1157

def species_scatterbug() -> U32:
  1158

def species_scattervein() -> U32:
  1159

def species_sceptile() -> U32:
  1160

def species_sceptilemega() -> U32:
  1161

def species_scizor() -> U32:
  1162

def species_scizormega() -> U32:
  1163

def species_scolipede() -> U32:
  1164

def species_scolipedemega() -> U32:
  1165

def species_scorbunny() -> U32:
  1166

def species_scovillain() -> U32:
  1167

def species_scovillainmega() -> U32:
  1168

def species_scrafty() -> U32:
  1169

def species_scraftymega() -> U32:
  1170

def species_scraggy() -> U32:
  1171

def species_scraptor() -> U32:
  1172

def species_scratchet() -> U32:
  1173

def species_screamtail() -> U32:
  1174

def species_scyther() -> U32:
  1175

def species_seadra() -> U32:
  1176

def species_seaking() -> U32:
  1177

def species_sealeo() -> U32:
  1178

def species_seedot() -> U32:
  1179

def species_seel() -> U32:
  1180

def species_seismitoad() -> U32:
  1181

def species_sentret() -> U32:
  1182

def species_serperior() -> U32:
  1183

def species_servine() -> U32:
  1184

def species_seviper() -> U32:
  1185

def species_sewaddle() -> U32:
  1186

def species_sharpedo() -> U32:
  1187

def species_sharpedomega() -> U32:
  1188

def species_shaymin() -> U32:
  1189

def species_shayminsky() -> U32:
  1190

def species_shedinja() -> U32:
  1191

def species_shelgon() -> U32:
  1192

def species_shellder() -> U32:
  1193

def species_shellos() -> U32:
  1194

def species_shelloseast() -> U32:
  1195

def species_shelmet() -> U32:
  1196

def species_shieldon() -> U32:
  1197

def species_shiftry() -> U32:
  1198

def species_shiinotic() -> U32:
  1199

def species_shinx() -> U32:
  1200

def species_shox() -> U32:
  1201

def species_shroodle() -> U32:
  1202

def species_shroomish() -> U32:
  1203

def species_shuckle() -> U32:
  1204

def species_shuppet() -> U32:
  1205

def species_sigilyph() -> U32:
  1206

def species_silcoon() -> U32:
  1207

def species_silicobra() -> U32:
  1208

def species_silvally() -> U32:
  1209

def species_silvallybug() -> U32:
  1210

def species_silvallydark() -> U32:
  1211

def species_silvallydragon() -> U32:
  1212

def species_silvallyelectric() -> U32:
  1213

def species_silvallyfairy() -> U32:
  1214

def species_silvallyfighting() -> U32:
  1215

def species_silvallyfire() -> U32:
  1216

def species_silvallyflying() -> U32:
  1217

def species_silvallyghost() -> U32:
  1218

def species_silvallygrass() -> U32:
  1219

def species_silvallyground() -> U32:
  1220

def species_silvallyice() -> U32:
  1221

def species_silvallypoison() -> U32:
  1222

def species_silvallypsychic() -> U32:
  1223

def species_silvallyrock() -> U32:
  1224

def species_silvallysteel() -> U32:
  1225

def species_silvallywater() -> U32:
  1226

def species_simipour() -> U32:
  1227

def species_simisage() -> U32:
  1228

def species_simisear() -> U32:
  1229

def species_sinistcha() -> U32:
  1230

def species_sinistchamasterpiece() -> U32:
  1231

def species_sinistea() -> U32:
  1232

def species_sinisteaantique() -> U32:
  1233

def species_sirfetchd() -> U32:
  1234

def species_sizzlipede() -> U32:
  1235

def species_skarmory() -> U32:
  1236

def species_skarmorymega() -> U32:
  1237

def species_skeledirge() -> U32:
  1238

def species_skiddo() -> U32:
  1239

def species_skiploom() -> U32:
  1240

def species_skitty() -> U32:
  1241

def species_skorupi() -> U32:
  1242

def species_skrelp() -> U32:
  1243

def species_skuntank() -> U32:
  1244

def species_skwovet() -> U32:
  1245

def species_slaking() -> U32:
  1246

def species_slakoth() -> U32:
  1247

def species_sliggoo() -> U32:
  1248

def species_sliggoohisui() -> U32:
  1249

def species_slitherwing() -> U32:
  1250

def species_slowbro() -> U32:
  1251

def species_slowbrogalar() -> U32:
  1252

def species_slowbromega() -> U32:
  1253

def species_slowking() -> U32:
  1254

def species_slowkinggalar() -> U32:
  1255

def species_slowpoke() -> U32:
  1256

def species_slowpokegalar() -> U32:
  1257

def species_slugma() -> U32:
  1258

def species_slurpuff() -> U32:
  1259

def species_smeargle() -> U32:
  1260

def species_smogecko() -> U32:
  1261

def species_smoguana() -> U32:
  1262

def species_smokomodo() -> U32:
  1263

def species_smoliv() -> U32:
  1264

def species_smoochum() -> U32:
  1265

def species_snaelstrom() -> U32:
  1266

def species_sneasel() -> U32:
  1267

def species_sneaselhisui() -> U32:
  1268

def species_sneasler() -> U32:
  1269

def species_snivy() -> U32:
  1270

def species_snom() -> U32:
  1271

def species_snorlax() -> U32:
  1272

def species_snorlaxgmax() -> U32:
  1273

def species_snorunt() -> U32:
  1274

def species_snover() -> U32:
  1275

def species_snubbull() -> U32:
  1276

def species_snugglow() -> U32:
  1277

def species_sobble() -> U32:
  1278

def species_solgaleo() -> U32:
  1279

def species_solosis() -> U32:
  1280

def species_solotl() -> U32:
  1281

def species_solrock() -> U32:
  1282

def species_spearow() -> U32:
  1283

def species_spectrier() -> U32:
  1284

def species_spewpa() -> U32:
  1285

def species_spheal() -> U32:
  1286

def species_spidops() -> U32:
  1287

def species_spinarak() -> U32:
  1288

def species_spinda() -> U32:
  1289

def species_spiritomb() -> U32:
  1290

def species_spoink() -> U32:
  1291

def species_sprigatito() -> U32:
  1292

def species_spritzee() -> U32:
  1293

def species_squawkabilly() -> U32:
  1294

def species_squawkabillyblue() -> U32:
  1295

def species_squawkabillywhite() -> U32:
  1296

def species_squawkabillyyellow() -> U32:
  1297

def species_squirtle() -> U32:
  1298

def species_stakataka() -> U32:
  1299

def species_stantler() -> U32:
  1300

def species_staraptor() -> U32:
  1301

def species_staraptormega() -> U32:
  1302

def species_staravia() -> U32:
  1303

def species_starly() -> U32:
  1304

def species_starmie() -> U32:
  1305

def species_starmiemega() -> U32:
  1306

def species_staryu() -> U32:
  1307

def species_steelix() -> U32:
  1308

def species_steelixmega() -> U32:
  1309

def species_steenee() -> U32:
  1310

def species_stonjourner() -> U32:
  1311

def species_stoutland() -> U32:
  1312

def species_stratagem() -> U32:
  1313

def species_stufful() -> U32:
  1314

def species_stunfisk() -> U32:
  1315

def species_stunfiskgalar() -> U32:
  1316

def species_stunky() -> U32:
  1317

def species_sudowoodo() -> U32:
  1318

def species_suicune() -> U32:
  1319

def species_sunflora() -> U32:
  1320

def species_sunkern() -> U32:
  1321

def species_surskit() -> U32:
  1322

def species_swablu() -> U32:
  1323

def species_swadloon() -> U32:
  1324

def species_swalot() -> U32:
  1325

def species_swampert() -> U32:
  1326

def species_swampertmega() -> U32:
  1327

def species_swanna() -> U32:
  1328

def species_swellow() -> U32:
  1329

def species_swinub() -> U32:
  1330

def species_swirlix() -> U32:
  1331

def species_swirlpool() -> U32:
  1332

def species_swoobat() -> U32:
  1333

def species_syclant() -> U32:
  1334

def species_syclar() -> U32:
  1335

def species_sylveon() -> U32:
  1336

def species_tactite() -> U32:
  1337

def species_tadbulb() -> U32:
  1338

def species_taillow() -> U32:
  1339

def species_talonflame() -> U32:
  1340

def species_tandemaus() -> U32:
  1341

def species_tangela() -> U32:
  1342

def species_tangrowth() -> U32:
  1343

def species_tapubulu() -> U32:
  1344

def species_tapufini() -> U32:
  1345

def species_tapukoko() -> U32:
  1346

def species_tapulele() -> U32:
  1347

def species_tarountula() -> U32:
  1348

def species_tatsugiri() -> U32:
  1349

def species_tatsugiricurlymega() -> U32:
  1350

def species_tatsugiridroopy() -> U32:
  1351

def species_tatsugiridroopymega() -> U32:
  1352

def species_tatsugiristretchy() -> U32:
  1353

def species_tatsugiristretchymega() -> U32:
  1354

def species_tauros() -> U32:
  1355

def species_taurospaldeaaqua() -> U32:
  1356

def species_taurospaldeablaze() -> U32:
  1357

def species_taurospaldeacombat() -> U32:
  1358

def species_teddiursa() -> U32:
  1359

def species_tentacool() -> U32:
  1360

def species_tentacruel() -> U32:
  1361

def species_tepig() -> U32:
  1362

def species_terapagos() -> U32:
  1363

def species_terapagosstellar() -> U32:
  1364

def species_terapagosterastal() -> U32:
  1365

def species_terrakion() -> U32:
  1366

def species_thievul() -> U32:
  1367

def species_throh() -> U32:
  1368

def species_thundurus() -> U32:
  1369

def species_thundurustherian() -> U32:
  1370

def species_thwackey() -> U32:
  1371

def species_timburr() -> U32:
  1372

def species_tinglu() -> U32:
  1373

def species_tinkatink() -> U32:
  1374

def species_tinkaton() -> U32:
  1375

def species_tinkatuff() -> U32:
  1376

def species_tirtouga() -> U32:
  1377

def species_toedscool() -> U32:
  1378

def species_toedscruel() -> U32:
  1379

def species_togedemaru() -> U32:
  1380

def species_togedemarutotem() -> U32:
  1381

def species_togekiss() -> U32:
  1382

def species_togepi() -> U32:
  1383

def species_togetic() -> U32:
  1384

def species_tomohawk() -> U32:
  1385

def species_torchic() -> U32:
  1386

def species_torkoal() -> U32:
  1387

def species_tornadus() -> U32:
  1388

def species_tornadustherian() -> U32:
  1389

def species_torracat() -> U32:
  1390

def species_torterra() -> U32:
  1391

def species_totodile() -> U32:
  1392

def species_toucannon() -> U32:
  1393

def species_toxapex() -> U32:
  1394

def species_toxel() -> U32:
  1395

def species_toxicroak() -> U32:
  1396

def species_toxtricity() -> U32:
  1397

def species_toxtricitygmax() -> U32:
  1398

def species_toxtricitylowkey() -> U32:
  1399

def species_toxtricitylowkeygmax() -> U32:
  1400

def species_tranquill() -> U32:
  1401

def species_trapinch() -> U32:
  1402

def species_treecko() -> U32:
  1403

def species_trevenant() -> U32:
  1404

def species_tropius() -> U32:
  1405

def species_trubbish() -> U32:
  1406

def species_trumbeak() -> U32:
  1407

def species_tsareena() -> U32:
  1408

def species_turtonator() -> U32:
  1409

def species_turtwig() -> U32:
  1410

def species_tympole() -> U32:
  1411

def species_tynamo() -> U32:
  1412

def species_typenull() -> U32:
  1413

def species_typhlosion() -> U32:
  1414

def species_typhlosionhisui() -> U32:
  1415

def species_tyranitar() -> U32:
  1416

def species_tyranitarmega() -> U32:
  1417

def species_tyrantrum() -> U32:
  1418

def species_tyrogue() -> U32:
  1419

def species_tyrunt() -> U32:
  1420

def species_umbreon() -> U32:
  1421

def species_unfezant() -> U32:
  1422

def species_unown() -> U32:
  1423

def species_unownb() -> U32:
  1424

def species_unownc() -> U32:
  1425

def species_unownd() -> U32:
  1426

def species_unowne() -> U32:
  1427

def species_unownexclamation() -> U32:
  1428

def species_unownf() -> U32:
  1429

def species_unowng() -> U32:
  1430

def species_unownh() -> U32:
  1431

def species_unowni() -> U32:
  1432

def species_unownj() -> U32:
  1433

def species_unownk() -> U32:
  1434

def species_unownl() -> U32:
  1435

def species_unownm() -> U32:
  1436

def species_unownn() -> U32:
  1437

def species_unowno() -> U32:
  1438

def species_unownp() -> U32:
  1439

def species_unownq() -> U32:
  1440

def species_unownquestion() -> U32:
  1441

def species_unownr() -> U32:
  1442

def species_unowns() -> U32:
  1443

def species_unownt() -> U32:
  1444

def species_unownu() -> U32:
  1445

def species_unownv() -> U32:
  1446

def species_unownw() -> U32:
  1447

def species_unownx() -> U32:
  1448

def species_unowny() -> U32:
  1449

def species_unownz() -> U32:
  1450

def species_ursaluna() -> U32:
  1451

def species_ursalunabloodmoon() -> U32:
  1452

def species_ursaring() -> U32:
  1453

def species_urshifu() -> U32:
  1454

def species_urshifugmax() -> U32:
  1455

def species_urshifurapidstrike() -> U32:
  1456

def species_urshifurapidstrikegmax() -> U32:
  1457

def species_uxie() -> U32:
  1458

def species_vanillish() -> U32:
  1459

def species_vanillite() -> U32:
  1460

def species_vanilluxe() -> U32:
  1461

def species_vaporeon() -> U32:
  1462

def species_varoom() -> U32:
  1463

def species_veluza() -> U32:
  1464

def species_venipede() -> U32:
  1465

def species_venomicon() -> U32:
  1466

def species_venomiconepilogue() -> U32:
  1467

def species_venomoth() -> U32:
  1468

def species_venonat() -> U32:
  1469

def species_venusaur() -> U32:
  1470

def species_venusaurgmax() -> U32:
  1471

def species_venusaurmega() -> U32:
  1472

def species_vespiquen() -> U32:
  1473

def species_vibrava() -> U32:
  1474

def species_victini() -> U32:
  1475

def species_victreebel() -> U32:
  1476

def species_victreebelmega() -> U32:
  1477

def species_vigoroth() -> U32:
  1478

def species_vikavolt() -> U32:
  1479

def species_vikavolttotem() -> U32:
  1480

def species_vileplume() -> U32:
  1481

def species_virizion() -> U32:
  1482

def species_vivillon() -> U32:
  1483

def species_vivillonarchipelago() -> U32:
  1484

def species_vivilloncontinental() -> U32:
  1485

def species_vivillonelegant() -> U32:
  1486

def species_vivillonfancy() -> U32:
  1487

def species_vivillongarden() -> U32:
  1488

def species_vivillonhighplains() -> U32:
  1489

def species_vivillonicysnow() -> U32:
  1490

def species_vivillonjungle() -> U32:
  1491

def species_vivillonmarine() -> U32:
  1492

def species_vivillonmodern() -> U32:
  1493

def species_vivillonmonsoon() -> U32:
  1494

def species_vivillonocean() -> U32:
  1495

def species_vivillonpokeball() -> U32:
  1496

def species_vivillonpolar() -> U32:
  1497

def species_vivillonriver() -> U32:
  1498

def species_vivillonsandstorm() -> U32:
  1499

def species_vivillonsavanna() -> U32:
  1500

def species_vivillonsun() -> U32:
  1501

def species_vivillontundra() -> U32:
  1502

def species_volbeat() -> U32:
  1503

def species_volcanion() -> U32:
  1504

def species_volcarona() -> U32:
  1505

def species_volkraken() -> U32:
  1506

def species_volkritter() -> U32:
  1507

def species_voltorb() -> U32:
  1508

def species_voltorbhisui() -> U32:
  1509

def species_voodoll() -> U32:
  1510

def species_voodoom() -> U32:
  1511

def species_vullaby() -> U32:
  1512

def species_vulpix() -> U32:
  1513

def species_vulpixalola() -> U32:
  1514

def species_wailmer() -> U32:
  1515

def species_wailord() -> U32:
  1516

def species_walkingwake() -> U32:
  1517

def species_walrein() -> U32:
  1518

def species_wartortle() -> U32:
  1519

def species_watchog() -> U32:
  1520

def species_wattrel() -> U32:
  1521

def species_weavile() -> U32:
  1522

def species_weedle() -> U32:
  1523

def species_weepinbell() -> U32:
  1524

def species_weezing() -> U32:
  1525

def species_weezinggalar() -> U32:
  1526

def species_whimsicott() -> U32:
  1527

def species_whirlipede() -> U32:
  1528

def species_whiscash() -> U32:
  1529

def species_whismur() -> U32:
  1530

def species_wigglytuff() -> U32:
  1531

def species_wiglett() -> U32:
  1532

def species_wimpod() -> U32:
  1533

def species_wingull() -> U32:
  1534

def species_wishiwashi() -> U32:
  1535

def species_wishiwashischool() -> U32:
  1536

def species_wobbuffet() -> U32:
  1537

def species_wochien() -> U32:
  1538

def species_woobat() -> U32:
  1539

def species_wooloo() -> U32:
  1540

def species_wooper() -> U32:
  1541

def species_wooperpaldea() -> U32:
  1542

def species_wormadam() -> U32:
  1543

def species_wormadamsandy() -> U32:
  1544

def species_wormadamtrash() -> U32:
  1545

def species_wugtrio() -> U32:
  1546

def species_wurmple() -> U32:
  1547

def species_wynaut() -> U32:
  1548

def species_wyrdeer() -> U32:
  1549

def species_xatu() -> U32:
  1550

def species_xerneas() -> U32:
  1551

def species_xerneasneutral() -> U32:
  1552

def species_xurkitree() -> U32:
  1553

def species_yamask() -> U32:
  1554

def species_yamaskgalar() -> U32:
  1555

def species_yamper() -> U32:
  1556

def species_yanma() -> U32:
  1557

def species_yanmega() -> U32:
  1558

def species_yungoos() -> U32:
  1559

def species_yveltal() -> U32:
  1560

def species_zacian() -> U32:
  1561

def species_zaciancrowned() -> U32:
  1562

def species_zamazenta() -> U32:
  1563

def species_zamazentacrowned() -> U32:
  1564

def species_zangoose() -> U32:
  1565

def species_zapdos() -> U32:
  1566

def species_zapdosgalar() -> U32:
  1567

def species_zarude() -> U32:
  1568

def species_zarudedada() -> U32:
  1569

def species_zebstrika() -> U32:
  1570

def species_zekrom() -> U32:
  1571

def species_zeraora() -> U32:
  1572

def species_zeraoramega() -> U32:
  1573

def species_zigzagoon() -> U32:
  1574

def species_zigzagoongalar() -> U32:
  1575

def species_zoroark() -> U32:
  1576

def species_zoroarkhisui() -> U32:
  1577

def species_zorua() -> U32:
  1578

def species_zoruahisui() -> U32:
  1579

def species_zubat() -> U32:
  1580

def species_zweilous() -> U32:
  1581

def species_zygarde() -> U32:
  1582

def species_zygarde10() -> U32:
  1583

def species_zygardecomplete() -> U32:
  1584

def species_zygardemega() -> U32:
  1585
