# Generated stable IDs from Showdown 9fb3a5b99f1a0bea17f495c5cc1bfe04fdd19c3e
import Base

def targets_adjacentally() -> U32:
  1

def targets_adjacentallyorself() -> U32:
  2

def targets_adjacentfoe() -> U32:
  3

def targets_all() -> U32:
  4

def targets_alladjacent() -> U32:
  5

def targets_alladjacentfoes() -> U32:
  6

def targets_allies() -> U32:
  7

def targets_allyside() -> U32:
  8

def targets_allyteam() -> U32:
  9

def targets_any() -> U32:
  10

def targets_foeside() -> U32:
  11

def targets_normal() -> U32:
  12

def targets_randomnormal() -> U32:
  13

def targets_scripted() -> U32:
  14

def targets_self() -> U32:
  15
