# Generated stable IDs from Showdown 9fb3a5b99f1a0bea17f495c5cc1bfe04fdd19c3e
import Base

def types_bug() -> U32:
  1

def types_dark() -> U32:
  2

def types_dragon() -> U32:
  3

def types_electric() -> U32:
  4

def types_fairy() -> U32:
  5

def types_fighting() -> U32:
  6

def types_fire() -> U32:
  7

def types_flying() -> U32:
  8

def types_ghost() -> U32:
  9

def types_grass() -> U32:
  10

def types_ground() -> U32:
  11

def types_ice() -> U32:
  12

def types_normal() -> U32:
  13

def types_poison() -> U32:
  14

def types_psychic() -> U32:
  15

def types_rock() -> U32:
  16

def types_steel() -> U32:
  17

def types_stellar() -> U32:
  18

def types_water() -> U32:
  19
