'use strict';
const fs=require('fs'),assert=require('assert'),crypto=require('crypto'),path=require('path');
if(process.env.WEBNAV_BUILD_CONFINED!=='1')throw Error('Use guarded build.cjs');
const {Game,maskFor,choice,OBS,ACTIONS,ABI,pin,sizes}=require('./worker_core.cjs');
const {oracle}=require('./reference.cjs');
const {RandomPlayerAI}=require(oracle+'/dist/sim/tools/random-player-ai');
Date.now=()=>1791194400000;
class Bot extends RandomPlayerAI{
  choose(c){this.selected=c;}
  pick(req){this.selected=null;this.receiveRequest(req);
    if(this.selected?.startsWith('move ')&&req.active?.[0]?.canTerastallize&&this.prng.random()<0.1)this.selected+=' terastallize';
    return this.selected;
  }
}
function seed(n,s){return [n&65535,(n*47111+s)&65535,(n*32117+s*17)&65535,(65535-n+s)&65535].join(',');}
const baseline=JSON.parse(fs.readFileSync('build/pokemon_gen9/js-probe/node-profile.json'));
let turns=0,decisions=0,retries=0;
for(let n=0;n<128;n++){
  const game=new Game(n,{seed:seed(n,1),p1:{name:'one',seed:seed(n,2)},p2:{name:'two',seed:seed(n,3)}});
  const bots=[new Bot(null,{seed:seed(n,4),move:0.95}),new Bot(null,{seed:seed(n,5),move:0.95})];
  // The actor sees its own six and only the opponent's opening reveal.
  assert.equal(game.views[0].p1.team.length,6);assert(game.views[0].p2.team.length<=1);
  const first=game.observe(0);
  // Private modifications alone cannot alter an already published actor view.
  const foe=game.b.sides[1].pokemon[5],old=foe.item;foe.item='leftovers';
  assert.deepStrictEqual(game.observe(0),first);foe.item=old;
  while(!game.b.ended){
    assert(game.steps<10000);
    const actions=game.requests.map((r,s)=>{
      if(game.masks[s][0])return 0;
      const c=bots[s].pick(r);const a=Array.from({length:ACTIONS},(_,i)=>i).find(i=>choice(i)===c);
      assert(a!==undefined&&game.masks[s][a],JSON.stringify({c,r,mask:[...game.masks[s]]}));return a;
    });
    game.step(actions);
    for(let s=0;s<2;s++){const obs=game.observe(s);assert.equal(obs.length,OBS);
      if(!obs.every(Number.isFinite))assert.fail(JSON.stringify({seed:n,seat:s,turn:game.b.turn,
        bad:[...obs.keys()].filter(i=>!Number.isFinite(obs[i])),request:game.requests[s]}));}
  }
  const log=crypto.createHash('sha256').update(game.b.log.join('\n')).digest('hex');
  assert.equal(log,baseline.games[n].sha256,'Full original log at seed '+n);
  assert.equal(game.decisions,baseline.games[n].decisions);turns+=game.b.turn;decisions+=game.decisions;retries+=game.retries;
  game.close();
  if((n+1)%32===0)console.log('Matched '+(n+1)+' complete original games');
}
const disguised=new Game(555,{p1:{name:'one',team:[{species:'Mew',moves:['psychic'],ability:'Synchronize'}]},
  p2:{name:'two',team:[{species:'Zoroark',level:80,moves:['darkpulse'],ability:'Illusion'},
    {species:'Blissey',level:90,moves:['seismictoss'],ability:'Natural Cure'}]}});
assert.equal(disguised.views[0].p2.active[0].speciesForme,'Blissey');
assert.equal(disguised.views[0].p2.active[0].level,90);
assert(!disguised.views[0].p2.team.some(p=>p.speciesForme==='Zoroark'));
disguised.close();
// Public action edge cases independent of simulator internals.
assert.deepStrictEqual([...maskFor({wait:true})],[1,...Array(14).fill(0)]);
const rev={forceSwitch:[true],side:{pokemon:[{active:true,reviving:true,condition:'0 fnt'},
  {active:false,condition:'0 fnt'},{active:false,condition:'100/100'}]}};
assert.equal(maskFor(rev)[10],1);assert.equal(maskFor(rev)[11],0);
assert.equal(maskFor({active:[{moves:[{id:'struggle'}]}],side:{pokemon:[]}})[1],1);
fs.writeFileSync('ocean/pokemon_gen9/worker_layout.h',`#pragma once\n/* ABI ${ABI}; generated by the independent source-game worker test. */\n#define PG9_WORKER_ABI ${ABI}\n#define PG9_OBS ${OBS}\n#define PG9_ACTIONS ${ACTIONS}\n`);
fs.mkdirSync('build/pokemon_gen9/worker',{recursive:true});
const result={revision:pin,abi:ABI,observations:OBS,actions:ACTIONS,games:128,turns,decisions,retries,sizes,
  checks:'exact complete original logs, public requests/masks, finite observations, private-state independence, unknown opponent bench, wait/Struggle/revival'};
fs.writeFileSync('build/pokemon_gen9/worker/validation.json',JSON.stringify(result,null,2)+'\n');
console.log(JSON.stringify(result,null,2));
