"""Measured runtime contract for the new F geometry and its two scoped clips."""
import hashlib,json,shutil
from pathlib import Path
import numpy as np
from gltf_math import GLB
r=Path(__file__).resolve().parent;p=r/'package';source=r.parent/'upper_body_gear_rebuild/stage_f';reference=r/'reference_static_crouch'
sha=lambda f:hashlib.sha256(Path(f).read_bytes()).hexdigest()
save=lambda name,data:(p/name).write_text(json.dumps(data,indent=2)+'\n')
flat=lambda M:np.asarray(M).T.ravel().tolist()
g=GLB(p/'swat_upper_gear_remake_f_v1.glb');doc=g.doc;skin=doc['skins'][0];joints=skin['joints'];names={n['name']:i for i,n in enumerate(doc['nodes'])};slots={n:i for i,n in enumerate(joints)};ibm=g.acc(skin['inverseBindMatrices']).reshape(-1,4,4).transpose(0,2,1);C=np.array([[1,0,0,0],[0,0,-1,0],[0,1,0,0],[0,0,0,1.]])
sh=sha(p/'swat_upper_gear_remake_f_v1.glb');native=json.loads((source/'STAGE_F_SOURCE.json').read_text());audit=json.loads((r/'independent_validation/SOURCE_CONTRACT_AUDIT.json').read_text());z=np.load(r/'work/native_static.npz');bn=list(z['bone_names']);bi={n:i for i,n in enumerate(bn)};meta=json.loads((r/'work/native_static.json').read_text());body_i=meta['mesh_names'].index('SWAT_Wearer');body_node=names['SWAT_Wearer'];body_mesh=doc['nodes'][body_node]['mesh']
jointmap=[{'skin_joint_slot':s,'node':n,'name':doc['nodes'][n]['name'],'parent_node':g.parents.get(n),'parent_joint_slot':slots.get(g.parents.get(n)),'inverse_bind_column_major':flat(ibm[s]),'default_TRS':{k:v for k,v in doc['nodes'][n].items()if k in ['translation','rotation','scale']},'source_inherit_scale':'NONE'if doc['nodes'][n]['name']in native['gear_bones']else'FULL','is_new_carrier':doc['nodes'][n]['name']in native['gear_bones']}for s,n in enumerate(joints)]
Wstatic=g.world_at(doc['animations'][0],[0])[0]
bindings={'schema':'swat-upper-gear-f-bindings/1','asset_version':'upper-gear-remake-f-v1','glb_sha256':sh,'units':'metres','matrix_layout':'column-major arrays; column vectors; rightmost transform first','source_to_gltf':'Blender(x,y,z)→glTF(x,z,−y)','engine_reference_axes':'+Xforward,+Yup,+Zright','scene_root':{'name':'SWAT_Mixamo_Rig','node':names['SWAT_Mixamo_Rig'],'default_world_column_major':flat(Wstatic[names['SWAT_Mixamo_Rig']])},'joint_map':jointmap,'new_carrier_contract':'Two new deforming elbow carriers are parented to matching upper arms. Blender inherit-scale NONE is baked into ordinary glTF local TRS for every key; all six vector channels are required. Source has20 scalar carrier curves. No live solver/driver/constraint is required.','original70_contract':'Names, parents, rest definitions and neutral source channels are exact to N. Resolve by name and actual skin.joints; old node/slot indices are not preserved.','drop_in_compatible_with_old_geometry_bank':False,'semantic_nodes':{n:{'node':names[n],'skin_joint_slot':slots.get(names[n])}for n in ['mixamorig:Hips','mixamorig:Head','mixamorig:LeftHand','mixamorig:RightHand','Gear_Elbow_L','Gear_Elbow_R','Prop_Rifle','Prop_Magazine_A','Prop_Magazine_B']},'static_source_bone_frames_basis_converted_column_major':{n:flat(C.T@z['world'][0,bi[n]]@C)for n in ['mixamorig:Head','Prop_Rifle','Gear_Elbow_L','Gear_Elbow_R']},'source_frame_warning':'Basis-converted native bone frames differ from actual glTF node frames. For skinning use actual Wnode×IBM, and for attachments use Wnode×IBM×B.'}
save('bindings.json',bindings)
clips=[]
for i,a in enumerate(doc['animations']):
 times=sorted({float(t)for s in a['samplers']for t in g.acc(s['input']).ravel()});clips.append({'animation_index':i,'animation_name':a['name'],'clip_id':['upper_gear_f_natural_hold_static','upper_gear_f_bounded_carry_proof_3s'][i],'source_sha256':a['extras']['source_sha256'],'authored_duration_s':None if i==0 else 3,'stored_span_s':times[-1]-times[0],'interpolation':'STEP'if i==0 else'LINEAR','key_times_s':times,'TRS_channels':len(a['channels']),'native_scalar_curves':720,'native_scalar_keys':720 if i==0 else 130320,'new_carrier_scalar_curves':20,'new_carrier_vector_channels':6,'looping_approved':False,'intended_use':'Single natural hold, sample t0 and hold without dividing by zero span'if i==0 else'Original60Hz bounded0–4degree raise and return, retain inclusive endpoint; no C1 or gameplay loop approval','events':[],'visibility':'All nine character meshes and both magazines enabled; no visibility/ownership animation','persistent_state':'No inventory/ammo/chamber/pouch IDs or gameplay commits authored; clip selection/holding must not reset runtime state'})
save('clips_and_state.json',{'glb_sha256':sh,'clips':clips,'excluded_source_action':'ADS Intent / Anatomical Gear F','exclusion_reason':'Stored raised gear-clearance diagnostic lacks shared shoulder support; not a fitted ADS deliverable','runtime_and_ADS_approved':False})

# Mesh/material inventory and exact retained-native correspondence.
meshes=[]
for ni,node in enumerate(doc['nodes']):
 if 'mesh'not in node:continue
 rows=[]
 for pi,pr in enumerate(doc['meshes'][node['mesh']]['primitives']):
  at=pr['attributes'];weights=np.concatenate([g.acc(at[k])for k in sorted(at)if k.startswith('WEIGHTS_')],axis=1);material=doc['materials'][pr['material']];mname=material['name'];uv=g.acc(at['TEXCOORD_0'])if'TEXCOORD_0'in at else None
  rows.append({'primitive':pi,'vertices':len(weights),'triangles':len(g.acc(pr['indices']))//3,'material_index':pr['material'],'material_name':mname,'original_character_texture_set':'Ch15_1001'if mname=='Ch15_body.001'else'Ch15_1002'if mname=='Ch15_body1.001'else None,'max_influences':int((weights>0).sum(1).max()),'vertices_above_four':int(((weights>0).sum(1)>4).sum()),'UV':'TEXCOORD_0'if uv is not None else None,'UV_range':[uv.min(0).tolist(),uv.max(0).tolist()]if uv is not None else None,'tangent_attribute_present':'TANGENT'in at})
 meshes.append({'node':ni,'mesh':node['mesh'],'name':node['name'],'skin':node['skin'],'primitives':rows})
save('geometry_material_changes.json',{'glb_sha256':sh,'old_body_vertices':24850,'retained_body_vertices':22645,'removed_vertices':2205,'removed_polygons':2144,'removed_triangles':3962,'removed_component_ids':native['removed_component_ids'],'new_parts':[{'name':x['name'],'bone':x['bone'],'native_vertices':x['vertices'],'native_polygons':x['polygons'],'weights':'single rigid influence1.0'}for x in native['new_objects']],'mesh_inventory':meshes,'material_definitions':doc['materials'],'textures_embedded':len(doc.get('images',[])),'material_scope':'Six original-source plain Principled materials; no linked images in selected scenes. New polymer/padding PBR roughness0.78 comes from shader nodes, not datablock roughness0.4. Original9-map character textures remain a separate compatible UV source, not embedded/lost here. New planar gear UVs are untextured and not an old atlas mapping.','normal_scope':'Retained N→compacted F custom normal change≤0.034677degrees. Fresh F→GLB normalized/encoded normals have a separate measured small deviation; see independent binary report. Neither comparison is called bit-identical.','old_bank_compatible':False,'original_rifle_magazine_sleeve_geometry':'Exact unchanged source geometry/weights/UV/materials; see source audit','native_ID_mapping':'native_vertex_and_polygon_map.json maps original retained wearer IDs; glTF seam-split vertex mapping is supplied independently by parity review'})
save('native_vertex_and_polygon_map.json',{'source_N_sha256':native['source_sha256'],'static_F_sha256':native['sha256'],'native_vertex_map':native['native_vertex_map'],'optical_original_native_ids':{'left':23263,'right':23516},'optical_compacted_F_ids':native['optical_vertex_map'],'native_polygon_mapping_source':'Original native_polygon_id attribute in the sealed SWAT_Wearer mesh; independent source audit verifies exact retained polygons/UVs/material slots.'})

# Calibrated physical rifle and optical proxy retain original bind-mesh coordinates.
oldfit=json.loads((reference/'measured_preview_fit.json').read_text());refs=json.loads((reference/'independent_validation/reference_landmarks.json').read_text());B=np.array(oldfit['weapon_bridge']['rigid_stockpad_engine_frame_to_bind_mesh_gltf_column_major']).reshape(4,4).T;rn=names['Prop_Rifle'];rs=slots[rn];J=ibm[rs]@B
optic=refs['optical']['data'];OB=C.T@np.array(optic['optical_frame_in_source_bind_mesh']);hn=names['mixamorig:Head'];hs=slots[hn];OJ=ibm[hs]@OB;landmarks={x['id']:x['position_export_engine']for x in refs['rifle']['data']['landmarks']}
optmap={}
for side,vi in native['optical_vertex_map'].items():
 gp=(C.T@np.r_[z[f'p{body_i}'][vi],1])[:3];matches=[]
 for pi,pr in enumerate(doc['meshes'][body_mesh]['primitives']):
  at=pr['attributes'];positions=g.acc(at['POSITION'])
  for v in np.flatnonzero(np.linalg.norm(positions-gp,axis=1)<1e-7):
   w=np.zeros(72)
   for suffix in sorted(int(k.split('_')[1])for k in at if k.startswith('WEIGHTS_')):np.add.at(w,g.acc(at[f'JOINTS_{suffix}'])[v].astype(int),g.acc(at[f'WEIGHTS_{suffix}'])[v])
   assert w[hs]==1 and np.count_nonzero(w)==1;matches.append({'primitive':pi,'vertex':int(v),'bind_mesh_point':positions[v].tolist(),'head_weight':1.})
 assert matches;optmap[side]={'original_native_vertex':optic['landmarks'][side]['center_vertex_id'],'F_native_vertex':vi,'gltf_matches':matches}
attachment={'glb_sha256':sh,'matrix_layout':'column-major4×4, column vectors','formula':'model_from_attachment(t)=Wnode(t)×IBM[resolved_slot]×B_bind_mesh=Wnode(t)×J_joint_local; J=IBM×B. Apply external actor/preview placement once.','rigid_rifle':{'asset_sha256':refs['rifle']['data']['asset_sha256'],'node':rn,'skin_slot':rs,'inverse_bind':flat(ibm[rs]),'B_bind_mesh':flat(B),'J_joint_local':flat(J),'physical_landmarks_rigid_engine_xyz_m':landmarks,'legacy_helpers':'RifleSocket/Muzzle retained but not calibrated physical endpoints'},'optical_proxy':{'name':optic['name'],'classification':optic['classification'],'node':hn,'skin_slot':hs,'inverse_bind':flat(ibm[hs]),'B_bind_mesh':flat(OB),'J_joint_local':flat(OJ),'body_node':body_node,'body_mesh':body_mesh,'vertex_mapping':optmap,'axes':'+Xoutward,+Yup,+Zcharacter-right','scope':'Virtual midpoint of actual lens-surface vertices; no anatomy, eye relief, IPD, camera origin or optical nodal-point claim'}}
save('physical_and_optical_bindings.json',attachment)
measure=[]
for ci,a in enumerate(doc['animations']):
 cap=np.load(r/('work/native_static.npz'if ci==0 else'work/native_movement.npz'));ts=cap['times'];W=g.world_at(a,ts);R=W[:,rn]@ibm[rs]@B;O=W[:,hn]@ibm[hs]@OB;rear=(R@np.r_[landmarks['rear_sight'],1])[:,:3];front=(R@np.r_[landmarks['front_sight'],1])[:,:3];d=front-rear;d/=np.linalg.norm(d,axis=1)[:,None];offset=O[:,:3,3]-rear;perp=np.linalg.norm(offset-np.sum(offset*d,axis=1)[:,None]*d,axis=1)
 values={'visor_surface_y_m':O[:,1,3],'physical_stock_y_m':R[:,1,3],'physical_muzzle_y_m':(R@np.r_[landmarks['muzzle'],1])[:,1],'physical_rifle_elevation_deg':np.rad2deg(np.arcsin(R[:,1,0]/np.linalg.norm(R[:,:3,0],axis=1))),'visor_surface_perpendicular_to_sightline_m':perp}
 measure.append({'animation_index':ci,'animation_name':a['name'],'samples':len(ts),'times_s':ts.tolist(),'ranges':{k:{'min':float(v.min()),'max':float(v.max())}for k,v in values.items()},'static_model_from_rigid':flat(R[0]),'static_model_from_optical':flat(O[0]),'model_from_rigid_series':R.transpose(0,2,1).reshape(-1,16).tolist(),'model_from_optical_series':O.transpose(0,2,1).reshape(-1,16).tolist()})
save('measured_attachment_poses.json',{'glb_sha256':sh,'units':'metres and named degrees; glTF+Yup','clips':measure,'scope':'Source-scale physical/optical references only; no camera, ADS, mounting force or shared shoulder support approval'})
for n in ['STAGE_F_SOURCE.json','STATIC_F_SEMANTIC_PIN.json','MOVEMENT_F_SEMANTIC_PIN.json','GEOMETRY_UV_MATERIAL_BINDINGS.json','COMPATIBILITY_AND_BINDINGS.json','EXPORT_INTENT.json','FRESH_REPLAY_VERIFICATION.json','SEALED_ARCHIVE_REPLAY_RECEIPT.json']:
 f=source/n
 if f.exists():shutil.copy2(f,p/('SOURCE_'+n))
for n in ['INDEPENDENT_STAGE_F_GATE.json','FINAL_STAGE_F_REVIEW.md','movement_joints/JOINT_REVIEW.md','movement_surfaces/MOVEMENT_SURFACES.json','attachments/F_PADDING_PROXIMITY_REVIEW.md','attachments/F_ATTACHMENT_REVIEW.json']:
 f=source/'qa'/n
 if f.exists():shutil.copy2(f,p/('SOURCE_'+Path(n).name))
for n in ['upper-gear-remake-f-neutral-comparison.jpg','upper-gear-remake-f-movement-review.mp4','ordered-movement-frames.jpg']:shutil.copy2(source/n,p/('source_'+n))
save('SOURCE_PROVENANCE.json',{'source_checkpoint':{'file':'swat-upper-gear-remake-f-selfcontained-checkpoint.tar.gz','bytes':18171720,'sha256':'1e586e869db06e5e6a0026b5c56860e5e0ed7f2d9bc1ae9bbee0eb8ca1fd3e35'},'static_source_sha256':'4271f2279bc3cbbcb46594157752b2ac0ca052628c24b4c8629a82c6771a3fc0','movement_source_sha256':'7165d1454e0526f01ca85c81f12e0245dfecb22071191918f984477a42c091b1','original_N_sha256':'de60108a89bfe7f2f5bb92f2b35f2d692d3a659ca7f1dbc310ca7023572a33ef','original_character':'Adobe Mixamo character; inherited character/animation terms apply','original_rifle':'Numbered weapon7 user upload; exact product/creator/license identity remains unresolved','new_gear':'Locally authored F derivative in sealed source scripts; does not remove original-source licensing obligations','distribution':'Private project review; no public raw asset redistribution authorization'})
print('F_METADATA_READY',len(jointmap),len(meshes),len(clips),rn,rs,hn,hs)
