#pragma once

#include "ps_constants.h"

enum {
    PS_OBS_PLAYER_BASE = 0,
    PS_OBS_BOSS_BASE = PS_OBS_PLAYER_BASE + PS_PLAYER_FEATURES,
    PS_OBS_ENEMY_BASE = PS_OBS_BOSS_BASE + PS_BOSS_FEATURES,
    PS_OBS_DROP_BASE = PS_OBS_ENEMY_BASE + PS_SECTORS * PS_RINGS * PS_ENEMY_CHANNELS,
    PS_OBS_OBSTACLE_BASE = PS_OBS_DROP_BASE + PS_SECTORS * PS_RINGS * PS_DROP_CHANNELS,
    PS_OBS_WEAPON_BASE = PS_OBS_OBSTACLE_BASE + PS_OBSTACLE_FEATURES,
    PS_OBS_UPGRADE_BASE = PS_OBS_WEAPON_BASE + PS_WEAPON_FEATURES,
    PS_OBS_MOVING_OBSTACLE_BASE = PS_OBS_UPGRADE_BASE + PS_UPGRADE_SLOTS * PS_UPGRADE_FEATURES,
    PS_OBS_END = PS_OBS_MOVING_OBSTACLE_BASE + PS_MOVING_OBSTACLE_OBS_FEATURES,
};

enum {
    PS_PLAYER_VISIBLE_ENEMIES = 8,
    PS_PLAYER_VISIBLE_DROPS = 9,
    PS_PLAYER_BUBBLE_READY = 10,
    PS_PLAYER_NEAREST_HEALTH_DISTANCE = 20,
    PS_PLAYER_NEAREST_XP_DX = 21,
    PS_PLAYER_NEAREST_XP_DY = 22,
    PS_PLAYER_NEAREST_XP_DISTANCE = 23,
    PS_PLAYER_VISIBLE_XP_VALUE = 24,
    PS_PLAYER_XP_CAN_LEVEL = 25,
};

enum {
    PS_BOSS_PRESENT = 0,
    PS_BOSS_DX = 1,
    PS_BOSS_DY = 2,
    PS_BOSS_PROXIMITY = 3,
    PS_BOSS_HP_FRACTION = 4,
    PS_BOSS_MAX_HP = 5,
    PS_BOSS_COUNT = 6,
};

#if defined(__cplusplus)
static_assert(PS_OBS_END == PS_OBS_SIZE, "Observation layout does not match PS_OBS_SIZE");
#else
_Static_assert(PS_OBS_END == PS_OBS_SIZE, "Observation layout does not match PS_OBS_SIZE");
#endif
