import argparse,json,numpy as np
from pathlib import Path
from replay_f import GLB,C,sha,facekey
ap=argparse.ArgumentParser();ap.add_argument('--package',type=Path,required=True);ap.add_argument('--source-capture',type=Path,required=True);ap.add_argument('--output',type=Path,required=True);a=ap.parse_args();P=a.package;g=GLB(P/'swat_upper_gear_remake_f_v1.glb');meta=json.loads(Path(str(a.source_capture)+'.json').read_text());z=dict(np.load(str(a.source_capture)+'.npz'));z={k:np.moveaxis(v,-1,0) if meta.get('time_axis_last') and ('_eval' in k or k.endswith('_bones')) else v for k,v in z.items()};mi=meta['mesh_names'].index('SWAT_Wearer');b=dict(np.load(P/'body_native_correspondence.npz'));e=dict(np.load(P/'body_export_correspondence.npz'));groups=json.loads((P/'body_texture_group_correspondence.json').read_text());assert sha(P/'body_native_correspondence.npz')==groups['native_correspondence_sha256'] and sha(P/'body_export_correspondence.npz')==groups['export_correspondence_sha256'] and groups['glb_sha256']==g.sha
assert np.array_equal(b['F_triangle_vertices'],z[f'tris{mi}']) and np.array_equal(b['F_triangle_loop_indices'],z[f'tri_loops{mi}']) and np.array_equal(b['F_loop_vertex'],z[f'loop_vertex{mi}']) and np.array_equal(b['F_loop_UV_0'],z[f'uv{mi}_0']) and np.array_equal(b['F_polygon_material_slot'][b['F_triangle_polygon']],z[f'tri_mat{mi}'])
vm=json.loads((P/'native_vertex_and_polygon_map.json').read_text())['native_vertex_map'];assert all(vm[str(old)]==i for i,old in enumerate(b['F_vertex_to_original_N_vertex']));prs={p['primitive']:p for p in g.primitives if p['name']=='SWAT_Wearer'};tri_lookup={}
for ti,tri in enumerate(b['F_triangle_vertices']):tri_lookup.setdefault(facekey(tri),[]).append(ti)
rows=[]
for gr in groups['material_groups']:
 pi=gr['gltf_primitive'];pr=prs[pi];ids=e[f'primitive_{pi}_vertex_to_F'];old=e[f'primitive_{pi}_vertex_to_original_N'];fp=e[f'primitive_{pi}_triangle_to_F_polygon'];op=e[f'primitive_{pi}_triangle_to_original_N_polygon'];assert np.array_equal(pr['p'][:,:3],z[f'p{mi}'][ids]@C[:3,:3].T);assert np.array_equal(old,b['F_vertex_to_original_N_vertex'][ids]);assert np.array_equal(op,b['F_polygon_to_original_N_polygon'][fp]);assert gr['gltf_material_index']==pr['material'] and gr['gltf_material_name']==g.doc['materials'][pr['material']]['name'];assert np.all(b['F_polygon_material_slot'][fp]==gr['F_material_slot']);assert gr['F_material_slot']==gr['original_N_material_slot'];assert len(set(op))==gr['unique_original_polygons'];assert len(pr['tris'])==gr['exported_triangles'] and len(ids)==gr['exported_vertices'];uvmax=0.
 for gi,tri in enumerate(pr['tris']):
  native=ids[tri];match=[i for i in tri_lookup[facekey(native)] if b['F_triangle_polygon'][i]==fp[gi]];assert len(match)==1;ti=match[0];verts=b['F_triangle_vertices'][ti];loops=b['F_triangle_loop_indices'][ti]
  for gv,fv in zip(tri,native):
   uv=b['F_loop_UV_0'][loops[list(verts).index(fv)]].copy();uv[1]=1-uv[1];uvmax=max(uvmax,float(abs(g.acc(pr['attributes']['TEXCOORD_0'])[gv]-uv).max()))
 assert abs(uvmax-gr['max_UV_error_after_standard_V_flip'])<1e-12;assert uvmax<1e-7
 rows.append({'primitive':pi,'vertices':len(ids),'triangles':len(pr['tris']),'F_and_original_vertex_polygon_maps_exact':True,'material_group_exact':True,'uv_max_error':uvmax})
assert sum(x['triangles'] for x in rows)==groups['all_retained_triangles_mapped']==42339
fit=json.loads((P/'measured_static_fit.json').read_text());assert fit['glb_sha256']==g.sha;W=g.world(0,0);M=lambda v:np.array(v).reshape(4,4).T;assert np.array_equal(M(fit['root_world_column_major']),W[fit['root_node']]);actual={pi:g.skin(W,pr) for pi,pr in prs.items()};allpos=np.concatenate(list(actual.values()));bounds_error=float(abs(np.array(fit['wearer_only_body_bounds_model_xyz_m'])-np.array([allpos.min(0),allpos.max(0)])).max());assert bounds_error<1e-10;native=z[f'neutral_eval{mi}'][0]@C[:3,:3].T;normw=z[f'w{mi}'].copy();normw/=normw.sum(1)[:,None];feet=[];centers=[]
for side,r in fit['sole_support'].items():
 selected=[i for i,n in enumerate(meta['bone_names']) if side.capitalize() in n and any(part in n for part in ['Foot','Toe'])];mask=normw[:,selected].sum(1)>.5;subset=np.flatnonzero(mask);minimum=native[subset,1].min();support=subset[native[subset,1]<=minimum+.001];assert r['native_subset_count']==len(subset);assert np.array_equal(support,r['F_native_support_vertices']);assert abs(r['native_evaluated_min_y_m']-minimum)<1e-8
 samples=[];unique_samples=[];exported=[]
 for pi,pr in prs.items():
  ids=e[f'primitive_{pi}_vertex_to_F'];exported.extend(actual[pi][mask[ids]])
 for q in r['support_mapping']:
  fid=q['F_native_vertex'];assert q['original_N_native_vertex']==int(b['F_vertex_to_original_N_vertex'][fid]);found=set()
  for pi,pr in prs.items():
   ids=e[f'primitive_{pi}_vertex_to_F']
   for vi in np.flatnonzero(ids==fid):found.add((pi,int(vi)))
  assert found=={(x['primitive'],x['vertex']) for x in q['gltf_matches']}
  group_samples=[]
  for x in q['gltf_matches']:
   pi,vi=x['primitive'],x['vertex'];assert np.array_equal(x['bind_mesh_point'],prs[pi]['p'][vi,:3]);samples.append(actual[pi][vi]);group_samples.append(actual[pi][vi])
  unique_samples.append(np.mean(group_samples,axis=0))
 assert len(exported)==r['exported_subset_count_with_seams'];assert abs(min(p[1] for p in exported)-r['actual_export_min_y_m'])<1e-10;centroid=np.mean(unique_samples,axis=0);assert abs(centroid-r['support_centroid_model_xyz_m']).max()<1e-10;centers.append(centroid);feet.append({'side':side,'native_foot_subset':len(subset),'unique_source_support_points':len(support),'exported_support_samples_with_seams':len(samples),'all_three_index_namespaces_exact':True,'centroid_method':'one mean position per unique F support vertex; coincident seam copies averaged first','native_min_y_m':float(minimum),'exported_min_y_m':float(min(p[1] for p in exported))})
A=M(fit['preview_alignment_candidate']['model_to_engine_heading0_feet_origin_column_major']);assert fit['preview_alignment_candidate']['uniform_scale']==1 and fit['preview_alignment_candidate']['baked_into_asset'] is False;assert abs(A[:3,:3].T@A[:3,:3]-np.eye(3)).max()<1e-12 and abs(np.linalg.det(A[:3,:3])-1)<1e-12;foot_origin=np.mean(centers,axis=0);foot_origin[1]=min(x['exported_min_y_m'] for x in feet);assert abs(A@np.r_[foot_origin,1]-[0,0,0,1]).max()<1e-12;phy=json.loads((P/'physical_and_optical_bindings.json').read_text())['rigid_rifle'];R=W[phy['node']]@g.ibm[phy['skin_slot']]@M(phy['B_bind_mesh']);forward=R[:3,0].copy();forward[1]=0;forward/=np.linalg.norm(forward);assert abs(A[:3,:3]@forward-[1,0,0]).max()<1e-12
files=['measured_static_fit.json','body_native_correspondence.json','body_native_correspondence.npz','body_export_correspondence.npz','body_texture_group_correspondence.json'];out={'status':'PASS','glb_sha256':g.sha,'metadata_sha256':{n:sha(P/n) for n in files},'wearer_triangle_polygon_material_UV_correspondence':rows,'root_world_exact':True,'wearer_bounds_max_error_m':bounds_error,'sole_support':feet,'preview_uniform_heading_and_feet_origin_transform_correct':True,'scope':'Actual binary/source reference correspondence and metadata fitting only. Separate original texture package bytes are not reopened; historical texture-group labels retain their existing source-material association.'};a.output.write_text(json.dumps(out,indent=2)+'\n');print('PASS',a.output)
