#define _GNU_SOURCE
#include "cdp.h"
#include "dom.h"
#include <assert.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
static char *read_script(void){FILE *f=fopen("ocean/webnav/web/dom_snapshot.js","rb");assert(f);fseek(f,0,SEEK_END);long n=ftell(f);rewind(f);char *s=calloc((size_t)n+1,1);assert(s&&fread(s,1,(size_t)n,f)==(size_t)n);fclose(f);return s;}
int main(void){WebCdp *c=calloc(1,sizeof *c);WebDom *o=calloc(1,sizeof *o);assert(c&&o);c->input=c->output=-1;c->pid=-1;const char *chrome=getenv("WEBNAV_CHROME");if(!chrome)chrome="build/webnav/chrome-headless-shell-linux64/chrome-headless-shell";assert(!web_cdp_start_ready(c,chrome,"about:blank","Boolean(document.body)"));char *script=read_script();cJSON *r=web_cdp_eval(c,script);assert(r);free(script);cJSON_Delete(r);
 r=web_cdp_eval(c,"document.body.innerHTML='<div id=\"query\">Buy blue shoes</div><div id=\"area\"><label for=\"x\">Visible label</label><input id=\"x\" aria-label=\"ARIA label\" value=\"two  spaces\"><button style=\"display:none\">Hidden answer</button><button>Submit</button><span style=\"cursor:pointer\">Custom link</span></div>';true");assert(r);cJSON_Delete(r);
 for(int quality=0;quality<4;quality++){char js[100];snprintf(js,sizeof js,"webnavDOM('#area','#query',%d)",quality);r=web_cdp_eval(c,js);assert(r&&!web_dom_parse(o,r)&&o->quality==(unsigned)quality);assert(!strcmp(web_dom_text(o,o->instruction),"Buy blue shoes"));int input=0,custom=0;for(unsigned i=0;i<o->count;i++){const WebDomNode *n=o->nodes+i;assert(!strstr(web_dom_text(o,n->text),"Hidden answer"));if(n->role==WEB_ROLE_TEXTBOX){input++;assert(!strcmp(web_dom_text(o,n->value),"two  spaces"));if(quality==0)assert(!strcmp(web_dom_text(o,n->name),"ARIA label"));if(quality==1)assert(!strcmp(web_dom_text(o,n->name),"Visible label"));if(quality==2)assert(!*web_dom_text(o,n->name));}if(!strcmp(web_dom_text(o,n->text),"Custom link")){custom++;assert(n->flags&WEB_ACTIONABLE);}}assert(input==1&&custom==1);
 cJSON_SetNumberValue(cJSON_GetObjectItem(r,"version"),999);assert(web_dom_parse(o,r)==-1);cJSON_Delete(r);}
 r=web_cdp_eval(c,"document.getElementById('area').innerHTML=Array.from({length:200},(_,i)=>'<p>Context '+i+'</p>').join('')+'<button style=\"position:fixed;top:10px;left:10px\">Important</button>';webnavDOM()");assert(r&&!web_dom_parse(o,r)&&o->count==128&&o->omitted==73);int found=0;for(unsigned i=0;i<o->count;i++)found|=!strcmp(web_dom_text(o,o->nodes[i].name),"Important");assert(found);
 cJSON *nodes=cJSON_GetObjectItem(r,"nodes"),*first=cJSON_GetArrayItem(nodes,0),*second=cJSON_GetArrayItem(nodes,1);cJSON_SetNumberValue(cJSON_GetObjectItem(second,"ref"),cJSON_GetObjectItem(first,"ref")->valuedouble);assert(web_dom_parse(o,r)==-1);cJSON_Delete(r);
 r=web_cdp_eval(c,"document.getElementById('area').innerHTML='<table><tr><td>First</td><td>One</td></tr><tr><td>Second</td><td>Two</td></tr></table>';webnavDOM()");assert(r&&!web_dom_parse(o,r));unsigned parents[4]={0};const char *labels[]={"First","One","Second","Two"};for(unsigned i=0;i<o->count;i++)for(unsigned j=0;j<4;j++)if(!strcmp(web_dom_text(o,o->nodes[i].text),labels[j]))parents[j]=o->nodes[i].parent;assert(parents[0]&&parents[0]==parents[1]&&parents[2]&&parents[2]==parents[3]&&parents[0]!=parents[2]);cJSON_Delete(r);
 r=web_cdp_eval(c,"document.body.innerHTML='<div id=query>Choose country</div><ul id=popup role=listbox><li role=option>France</li><li role=option style=\"display:none\">Hidden option</li></ul><div id=area><input><button>Submit</button></div><div id=hud><button>Private reward</button></div>';webnavDOM()");assert(r&&!web_dom_parse(o,r)&&o->count==2);cJSON_Delete(r);
 r=web_cdp_eval(c,"webnavDOM('#area','#query',0,['#popup li','#popup','#popup'])");assert(r&&!web_dom_parse(o,r)&&o->count==4);unsigned popup=0,option=0;for(unsigned i=0;i<o->count;i++){const WebDomNode *n=o->nodes+i;assert(!strstr(web_dom_text(o,n->text),"Private reward"));assert(!strstr(web_dom_text(o,n->text),"Hidden option"));if(n->role==WEB_ROLE_OPTION){option++;assert(!strcmp(web_dom_text(o,n->name),"France"));assert(n->parent==popup&&popup);}else if(!strcmp(web_dom_text(o,n->text),"France"))popup=n->ref;}assert(option==1);cJSON_Delete(r);
 r=web_cdp_eval(c,"document.getElementById('popup').style.display='none';webnavDOM('#area','#query',0,['#popup'])");assert(r&&!web_dom_parse(o,r)&&o->count==2);cJSON_Delete(r);
 web_cdp_close(c);free(c);free(o);puts("PASS: DOM roles, name provenance, quality tiers, whitespace, hidden-text exclusion, visible-control priority, table-row relationships, scoped external popups, bounds and malformed schema rejection");return 0;}
