[base]
package = ocean
env_name = incremental_maze

[vec]
total_agents = 512
num_buffers = 4.85531
num_threads = 0

[selfplay]
enabled = 0
max_size = 16
swap_winrate = 0.8
min_games = 2048
elo_init = 0
elo_k = 16
seed = 42
snapshot_interval = 1000000000
opp_timeout_steps = 500000000

[env]
num_maps = 22
map_size = 5

[policy]
hidden_size = 512
num_layers = 3.69832
expansion_factor = 1

[train]
gpus = 1
seed = 42
total_timesteps = 62914600
learning_rate = 0.00252438
anneal_lr = 1
min_lr_ratio = 0
gamma = 0.986462
gae_lambda = 0.832218
replay_ratio = 3.78119
clip_coef = 0.0109792
vf_coef = 2.0678
vf_clip_coef = 1.95785
max_grad_norm = 0.148096
ent_coef = 0.00165263
anneal_ent_coef = 0
min_ent_coef_ratio = 0.1
momentum = 0.947875
eps = 0.0001
minibatch_size = 16384
horizon = 512
vtrace_rho_clip = 5
vtrace_c_clip = 1.75138
prio_alpha = 0.82507
prio_beta0 = 0.738469
#prio_alpha = 0.0
#prio_beta0 = 0.0

#state_buffer_size = 10_000
#cl_frac = 0.8
#anneal_cl = 0
#warmup_states = 1000
#explore_alpha = 0.0

[sweep]
downsample = 5

#[sweep.train.total_timesteps]
#distribution = log_normal
#min = 1e8
#max = 1e9
#mean = 3e8
#scale = time

#[sweep.train.state_buffer_size]
#distribution = int_uniform
#min = 100_000
#max = 5_000_000
#scale = auto

#[sweep.train.cl_frac]
#distribution = uniform
#min = 0.0
#max = 0.9
#scale = auto

#[sweep.train.explore_alpha]
#distribution = uniform
#min = 0.0
#max = 1.0
#scale = auto

#[sweep.train.explore_beta]
#distribution = uniform
#min = 0.0
#max = 1.0
#scale = auto
