[base]
package = ocean
env_name = maze

[vec]
total_agents = 2048
num_buffers = 3.64705
num_threads = 2

[env]
#max_size = 47
num_maps = 8192
map_size = 31

[policy]
hidden_size = 256
num_layers = 6.58366
expansion_factor = 1

[train]
gpus = 1
seed = 42
total_timesteps = 131792999
learning_rate = 0.00131503
anneal_lr = 1
min_lr_ratio = 0
gamma = 0.990055
gae_lambda = 0.954947
replay_ratio = 2.63039
clip_coef = 0.0751099
vf_coef = 4.69454
vf_clip_coef = 1.33322
max_grad_norm = 3.31769
ent_coef = 0.000135452
beta1 = 0.991318
beta2 = 0.999968
eps = 0.0001
minibatch_size = 32768
horizon = 64
vtrace_rho_clip = 4.74953
vtrace_c_clip = 1.85314
#prio_alpha = 0.63544
#prio_alpha = 0.99
#prio_beta0 = 0.814514
prio_alpha = 0.0
prio_beta0 = 0.0
anneal_prio_beta = 0
use_rnn = 1
env = 0

state_buffer_size = 1_000_000
cl_frac = 0.8
anneal_cl = 0
warmup_states = 1_000
explore_alpha = 2.0
explore_beta = 0.0

[sweep]
downsample = 5

[sweep.train.total_timesteps]
distribution = log_normal
min = 1e8
max = 1e9
mean = 3e8
scale = time
