[base]
package = morph
env_name = morph
vec = native
policy_name = Policy
# rnn_name = Recurrent

[policy]
input_dim = 934
action_dim = 69
demo_dim = 358
hidden = 2048

[env]
motion_file = "resources/morph/dfaust_one_leg_jump.pkl"
#has_self_collision = True
has_self_collision = False
num_envs = 2048
; num_envs = 32
#headless = False

[train]
seed = 1
torch_deterministic = True
device = cuda

cpu_offload = False
compile = False
norm_adv = True
target_kl = None

total_timesteps = 5_000_000_000
eval_timesteps = 100_000

num_workers = 1
num_envs = 1
batch_size = 65536
minibatch_size = 16384
; batch_size = 1024
; minibatch_size = 256

disc_coef = 5.0

update_epochs = 4
bptt_horizon = 8
anneal_lr = False
gae_lambda = 0.97
gamma = 0.90
clip_coef = 0.5
clip_vloss = True
vf_coef = 1.0
vf_clip_coef = 0.5
max_grad_norm = 0.5
ent_coef = 0.0001
learning_rate = 2e-4
checkpoint_interval = 10000
