[base]
package = morph
env_name = morph morph-render
vec = native
policy_name = Policy
# rnn_name = Recurrent

[policy]
; input_dim = 934
; action_dim = 69
; demo_dim = 358
hidden_size = 2048

[env]
motion_file = "resources/morph/totalcapture_acting_poses.pkl"
has_self_collision = True
num_envs = 2048
#num_envs = 32
#headless = False

[train]
seed = 1
torch_deterministic = True
device = cuda

cpu_offload = False
compile = False
norm_adv = True
target_kl = None

total_timesteps = 5_000_000_000
eval_timesteps = 100_000

num_workers = 1
num_envs = 1
batch_size = 65536
minibatch_size = 16384
; batch_size = 1024
; minibatch_size = 256

disc_coef = 5.0

update_epochs = 4
bptt_horizon = 8
anneal_lr = False
gae_lambda = 0.99
gamma = 0.95
clip_coef = 0.2
clip_vloss = True
vf_coef = 2.0
vf_clip_coef = 0.2
max_grad_norm = 1.0
ent_coef = 0.0
learning_rate = 2e-5
checkpoint_interval = 10000
