[base]
env_name = trianglepath
seed = 73
async = 0
cudagraphs = 1
load_model_path = None
load_enemy_model_path = None
checkpoint_interval = 50
num_games = 8192
eval_agents = 8192

[vec]
total_agents = 16384
num_buffers = 1
num_threads = 4
action_mask_size = 2
gpu_env = 1

[selfplay]
enabled = 0
max_size = 32
seed = 42
opp_timeout_steps = 1000000
eval_pool_size = 8
eval_games = 0
eval_agents = 8192

[policy]
hidden_size = 256
num_layers = 2
expansion_factor = 1

[env]
seed = 42
height = 6
cell_min = 1
cell_max = 9
# 0 = dense cells; 1 = terminal score / fixed maximum; 2 = score / DP optimal
reward_mode = 2

[train]
total_timesteps = 4000000000
learning_rate = 0.00114444818
anneal_lr = 1
gamma = 0.997069895
gae_lambda = 0.988910258
replay_ratio = 1
clip_coef = 0.1
vf_coef = 0.5
vf_clip_coef = 1.0
max_grad_norm = 0.5
ent_coef = 0.00313891773
emag_kl_coef = 0.0
emag_tau = 0.0001
anneal_ent_coef = 0
momentum = 0.9
minibatch_size = 16384
horizon = 16
prio_alpha = 0
prio_beta0 = 0.6
epoch_sampling = 1
gpus = 1

[sweep]
metric = regret
metric_distribution = linear
goal = minimize
max_suggestion_cost = 300
max_runs = 16
gpus = 0
downsample = 1
use_gpu = True
prune_pareto = True
sweep_only = train.ent_coef, train.gamma, train.gae_lambda

[sweep.train.ent_coef]
distribution = log_normal
min = 0.0005
max = 0.01
scale = auto

[sweep.train.gamma]
distribution = logit_normal
min = 0.98
max = 0.9999
scale = auto

[sweep.train.gae_lambda]
distribution = logit_normal
min = 0.95
max = 0.999
scale = auto
