[base]
env_name = trianglepath
seed = 73
async = 1
cudagraphs = 0
load_model_path = latest
load_enemy_model_path = None
checkpoint_interval = 50
num_games = 8192
eval_agents = 32

[vec]
total_agents = 4096
num_buffers = 1
num_threads = 4
action_mask_size = 2
gpu_env = 1

[selfplay]
enabled = 0
max_size = 32
seed = 42
opp_timeout_steps = 1000000
eval_pool_size = 8
eval_games = 0
eval_agents = 8192

[policy]
hidden_size = 8
num_layers = 2
expansion_factor = 1

[env]
seed = 42
height = 4
cell_min = 1
cell_max = 9
# 0 = dense cells; 1 = terminal score / fixed maximum; 2 = score / DP optimal
reward_mode = 2

[train]
total_timesteps = 20000000
learning_rate = 0.0001
anneal_lr = 1
gamma = 0.994708121
gae_lambda = 0.99655509
replay_ratio = 4
clip_coef = 0.1
vf_coef = 0.5
vf_clip_coef = 1.0
max_grad_norm = 0.5
ent_coef = 0.00426739827
emag_kl_coef = 0.0
emag_tau = 0.0001
anneal_ent_coef = 0
momentum = 0.9
minibatch_size = 4096
horizon = 16
prio_alpha = 0
prio_beta0 = 0.6
epoch_sampling = 1
gpus = 1

[sweep]
metric = regret
metric_distribution = linear
goal = minimize
max_suggestion_cost = 300
max_runs = 40
gpus = 0
downsample = 1
use_gpu = True
prune_pareto = True
sweep_only = train.ent_coef, train.gamma, train.gae_lambda

[sweep.env.height]
distribution = uniform_pow2
min = 8
max = 64
scale = auto

[sweep.train.ent_coef]
distribution = log_normal
min = 0.001
max = 0.1
scale = auto

[sweep.train.gamma]
distribution = logit_normal
min = 0.9
max = 0.9999
scale = auto

[sweep.train.gae_lambda]
distribution = logit_normal
min = 0.8
max = 0.999
scale = auto
