// Import the delivered metre-scale shell without running authoring scripts.
const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
const root=path.resolve(__dirname,'..');
let out='// Generated by tools/import_motel_props.cjs from hash-checked original GLBs.\n',assets=[];
const deliveries=[{file:'motel_service_trolley.glb',handoff:'motel-trolley',triangles:2416},{file:'motel_fire_extinguisher.glb',handoff:'motel-extinguisher',triangles:2412},{file:'motel_reception_noticeboard.glb',handoff:'motel-noticeboard',triangles:1416},{file:'chair_dining_spindle.glb',handoff:'motel-spindle-chair',triangles:1884}];
for(let index=0;index<deliveries.length;index++) {
const delivery=deliveries[index],file=path.join(root,'assets/environment/motel_props',delivery.file);
const bytes=fs.readFileSync(file),manifest=JSON.parse(fs.readFileSync(path.join(root,'art_handoffs',delivery.handoff,'manifest.json')));
assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),manifest.runtime_sha256??manifest.runtime.sha256);
assert.equal(bytes.readUInt32LE(0),0x46546c67);assert.equal(bytes.readUInt32LE(4),2);assert.equal(bytes.readUInt32LE(8),bytes.length);
const end=20+bytes.readUInt32LE(12),g=JSON.parse(bytes.subarray(20,end)),bin=bytes.subarray(end+8);
function data(id){const a=g.accessors[id],v=g.bufferViews[a.bufferView],n={SCALAR:1,VEC3:3}[a.type],size={5123:2,5125:4,5126:4}[a.componentType];assert(n&&size&&!a.sparse);return Array.from({length:a.count},(_,i)=>Array.from({length:n},(_,j)=>{const at=(v.byteOffset||0)+(a.byteOffset||0)+i*(v.byteStride||n*size)+j*size;return a.componentType===5126?bin.readFloatLE(at):size===2?bin.readUInt16LE(at):bin.readUInt32LE(at);}));}
const vertices=[],indices=[];
for(const node of g.nodes){assert(!node.matrix&&!node.translation&&!node.rotation&&!node.scale&&!node.skin);if(node.mesh===undefined)continue;for(const p of g.meshes[node.mesh].primitives){assert(p.mode===undefined||p.mode===4);const v=data(p.attributes.POSITION),idx=data(p.indices).flat();assert(idx.every(x=>x>=0&&x<v.length));indices.push(...idx.map(i=>i+vertices.length));vertices.push(...v);}}
assert.equal(indices.length/3,delivery.triangles);assert(vertices.flat().every(Number.isFinite));
const min=[0,1,2].map(a=>Math.min(...vertices.map(v=>v[a]))),max=[0,1,2].map(a=>Math.max(...vertices.map(v=>v[a]))),center=min.map((v,a)=>(v+max[a])/2),half=min.map((v,a)=>(max[a]-v)/2);
const audit=['motel-trolley','motel-spindle-chair'].includes(delivery.handoff)?manifest:JSON.parse(fs.readFileSync(path.join(root,'art_handoffs',delivery.handoff,'qa/runtime_audit.json')));
for(let a=0;a<3;a++){assert(Math.abs(min[a]-audit.bounds_min_m[a])<1e-7);assert(Math.abs(max[a]-audit.bounds_max_m[a])<1e-7);}
const f=x=>{let s=(Math.abs(x)<1e-12?0:x).toPrecision(9);return(s.includes('.')||s.includes('e')?s:s+'.0')+'f';};
out+='static b3Vec3 prop_vertices_'+index+'[]={\n'+vertices.map(v=>'{'+v.map((x,a)=>f(x-center[a])).join(',')+'}').join(',\n')+'};\n';
out+='static int32_t prop_indices_'+index+'[]={'+indices.join(',')+'};\n';
out+='static const SwatMotelMaterial prop_materials_'+index+'[]={'+g.materials.map(m=>'{'+f(m.pbrMetallicRoughness.roughnessFactor??1)+','+f(m.pbrMetallicRoughness.metallicFactor??1)+'}').join(',')+'};\n';
assets.push('{"'+delivery.file+'",{'+center.map(f)+'},{'+half.map(f)+'},prop_vertices_'+index+','+vertices.length+',prop_indices_'+index+','+delivery.triangles+',prop_materials_'+index+','+g.materials.length+'}');
}
out+='static const SwatMotelAsset prop_assets[]={'+assets.join(',')+'};\n';
const f=x=>{let s=(Math.abs(x)<1e-12?0:x).toPrecision(9);return(s.includes('.')||s.includes('e')?s:s+'.0')+'f';};
const anchors=JSON.parse(fs.readFileSync(path.join(root,'art_handoffs/motel-trolley/qa/ground_anchor_audit.json'))).four_measured_wheel_contacts;
assert.equal(anchors.length,4);out+='static const b3Vec3 prop_wheel_anchors[]={'+anchors.map(a=>'{'+a.measured_center_xyz_m.map(f).join(',')+'}').join(',')+'};\n';
const mounts=JSON.parse(fs.readFileSync(path.join(root,'art_handoffs/motel-extinguisher/qa/contact_anchors.json'))).wall_contacts;
assert.equal(mounts.length,2);out+='static const b3Vec3 prop_extinguisher_anchors[]={'+mounts.map(a=>'{'+a.position_gltf_m.map(f).join(',')+'}').join(',')+'};\n';
const board=JSON.parse(fs.readFileSync(path.join(root,'art_handoffs/motel-noticeboard/qa/mounting.json'))).mount_anchor_centers_m;
assert.equal(board.length,2);out+='static const b3Vec3 prop_noticeboard_anchors[]={'+board.map(a=>'{'+a.map(f).join(',')+'}').join(',')+'};\n';
const feet=JSON.parse(fs.readFileSync(path.join(root,'art_handoffs/motel-spindle-chair/ENGINE_CONTACTS.json'))).anchors;
assert.equal(feet.length,4);out+='static const b3Vec3 prop_chair_anchors[]={'+feet.map(a=>'{'+a.map(f).join(',')+'}').join(',')+'};\n';
const target=path.join(root,'motel_props_data.h');if(!fs.existsSync(target)||fs.readFileSync(target,'utf8')!==out)fs.writeFileSync(target,out);
console.log('PASS prop import: original hashes, identity metre-scale nodes, 8128 exact prop triangles, measured bounds and contact anchors');
