// Flatten original scene transforms for collision only; rendering keeps each GLB.
// Run from ocean/swat after checking the receipt's original GLB SHA-256 values.
#include "../vendor/cgltf_private.h"
#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>

static void emit(const char* file,int first,int expected) {
    char path[256];snprintf(path,sizeof(path),"assets/environment/motel_props/%s",file);
    cgltf_options options={0};cgltf_data* data=NULL;
    assert(cgltf_parse_file(&options,path,&data)==cgltf_result_success);
    assert(cgltf_load_buffers(&options,data,path)==cgltf_result_success && cgltf_validate(data)==cgltf_result_success);
    int at=first,total=0;float feet[4][3]={{0}};int samples[4]={0};
    for(int i=0;i<4;i++)feet[i][1]=INFINITY;
    for(size_t n=0;n<data->nodes_count;n++) {
        cgltf_node* node=&data->nodes[n];if(!node->mesh)continue;
        float matrix[16];cgltf_node_transform_world(node,matrix);
        for(size_t p=0;p<node->mesh->primitives_count;p++,at++) {
            cgltf_primitive* prim=&node->mesh->primitives[p];assert(prim->indices && prim->type==cgltf_primitive_type_triangles);
            const cgltf_accessor* positions=cgltf_find_accessor(prim,cgltf_attribute_type_position,0);assert(positions);
            size_t count=positions->count;float (*vertices)[3]=malloc(count*sizeof(*vertices));assert(vertices);
            float lo[]={INFINITY,INFINITY,INFINITY},hi[]={-INFINITY,-INFINITY,-INFINITY};
            for(size_t v=0;v<count;v++) {
                float local[3];assert(cgltf_accessor_read_float(positions,v,local,3));
                for(int k=0;k<3;k++) {
                    float x=matrix[k]*local[0]+matrix[4+k]*local[1]+matrix[8+k]*local[2]+matrix[12+k];
                    assert(isfinite(x));vertices[v][k]=x;lo[k]=fminf(lo[k],x);hi[k]=fmaxf(hi[k],x);
                }
                if(vertices[v][1]<.001f) {
                    int foot=(vertices[v][0]>0)+2*(vertices[v][2]>0);samples[foot]++;
                    if(vertices[v][1]<feet[foot][1])for(int k=0;k<3;k++)feet[foot][k]=vertices[v][k];
                }
            }
            float center[3],half[3];for(int k=0;k<3;k++){center[k]=(lo[k]+hi[k])*.5f;half[k]=(hi[k]-lo[k])*.5f;}
            printf("static b3Vec3 seating_vertices_%d[]={\n",at);
            for(size_t v=0;v<count;v++)printf("{%.9ef,%.9ef,%.9ef},\n",vertices[v][0]-center[0],vertices[v][1]-center[1],vertices[v][2]-center[2]);
            printf("};\nstatic int32_t seating_indices_%d[]={\n",at);
            for(size_t i=0;i<prim->indices->count;i++){size_t ix=cgltf_accessor_read_index(prim->indices,i);assert(ix<count);printf("%zu,",ix);}
            puts("};");int triangles=(int)prim->indices->count/3;total+=triangles;
            printf("static const SwatMotelMaterial seating_materials_%d[]={",at);
            for(size_t m=0;m<data->materials_count;m++)printf("{%.9ef,%.9ef},",data->materials[m].pbr_metallic_roughness.roughness_factor,data->materials[m].pbr_metallic_roughness.metallic_factor);
            printf("};\nstatic const SwatMotelAsset seating_asset_%d={\"%s\",{%.9ef,%.9ef,%.9ef},{%.9ef,%.9ef,%.9ef},seating_vertices_%d,%zu,seating_indices_%d,%d,seating_materials_%d,%zu};\n",
                at,file,center[0],center[1],center[2],half[0],half[1],half[2],at,count,at,triangles,at,data->materials_count);
            fprintf(stderr,"part%d material%s vertices%zu triangles%d bounds %.6f %.6f %.6f / %.6f %.6f %.6f\n",at,prim->material->name,count,triangles,lo[0],lo[1],lo[2],hi[0],hi[1],hi[2]);free(vertices);
        }
    }
    assert(total==expected && at-first==(first==0?2:1));
    printf("static const b3Vec3 seating_feet_%d[]={\n",first);
    for(int i=0;i<4;i++){assert(samples[i]>=3);printf("{%.9ef,%.9ef,%.9ef},\n",feet[i][0],feet[i][1],feet[i][2]);}
    puts("};");cgltf_free(data);
}
int main(void) {
    puts("// Generated by tools/import_motel_seating.c; original primitive groups and full scene transforms, metres.");
    emit("modern_arm_chair_01_floor_centered_2k.glb",0,8916);
    emit("vintage_day_bed_floor_centered_2k.glb",2,2715);
    puts("static const SwatMotelAsset* seating_assets[]={&seating_asset_0,&seating_asset_1,&seating_asset_2};");
}
