// Import the frozen, audited R1 packet. Run with its extracted directory. No Python.
const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
const input=process.argv[2];assert(input,'Pass extracted briar_court_windows_realistic_r1 directory');
const out=path.join(__dirname,'..'),manifest=JSON.parse(fs.readFileSync(path.join(input,'component_manifest.json'))).components,contacts=JSON.parse(fs.readFileSync(path.join(input,'support_relationships.json'))).contacts;
const material={painted_timber:'SWAT_WOOD',teal_timber:'SWAT_WOOD',painted_aluminum:'SWAT_ALUMINUM',painted_steel:'SWAT_STEEL',rubber:'SWAT_RUBBER',cloth:'SWAT_CLOTH',glass:'SWAT_OPAQUE_GLASS'};
let text='// Generated by tools/import_motel_windows.cjs from frozen R1 GLBs and component manifest.\n';
let reports=[];const models=[];
const sources=[['room_window_insert','room_window_insert_realistic_r1.glb','18112ea6a0675875db3ca452d3307fce0fa32242a77bb624747aa2a6df181fe9'],['lobby_glazed_facade','lobby_glazed_facade_realistic_r1.glb','f77dac494b028fac16902709fea32bb9f3a187e3b541fe9b659fecfaabea0241']];
const vec=a=>'{'+a.map(v=>Number(v).toExponential(9)+'f').join(',')+'}';
for(let kind=0;kind<2;kind++){
 const [asset,file,hash]=sources[kind],bytes=fs.readFileSync(path.join(input,'assets',file));assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),hash);
 const json=JSON.parse(bytes.subarray(20,20+bytes.readUInt32LE(12))),bin=bytes.subarray(28+bytes.readUInt32LE(12));
 function read(ai,i){const a=json.accessors[ai],v=json.bufferViews[a.bufferView],size={5126:4,5125:4,5123:2}[a.componentType],dim=a.type==='VEC3'?3:1,offset=(v.byteOffset||0)+(a.byteOffset||0)+i*(v.byteStride||size*dim);assert(size);return Array.from({length:dim},(_,k)=>a.componentType===5126?bin.readFloatLE(offset+k*size):size===2?bin.readUInt16LE(offset+k*size):bin.readUInt32LE(offset+k*size));}
 const components=manifest.filter(c=>c.asset===asset),byId=new Map(components.map(c=>[c.id,c])),short=c=>c.id.slice(asset.length+6);
 const adj=new Map(components.map(c=>[c.id,[]]));for(let e of contacts)if(byId.has(e.a)&&byId.has(e.b)){adj.get(e.a).push(e.b);adj.get(e.b).push(e.a);}
 const primary=components.filter(c=>['frame_profile','sill','header','hardware','rod_socket','curtain_panel','glass_pane'].includes(c.kind));
 const primarySet=new Set(primary.map(c=>c.id));
 // Auxiliary topology follows its nearest authored contact-connected load member.
 // Glass and cloth are terminal covers, so seals/fasteners prefer actual frames.
 function parent(c){if(primarySet.has(c.id))return c.id;const queue=[c.id],seen=new Set(queue);while(queue.length){let candidates=[];const n=queue.length;for(let q=0;q<n;q++){const id=queue.shift();for(let next of adj.get(id)){if(seen.has(next))continue;seen.add(next);if(primarySet.has(next)&& (c.substrate!=='cloth'||byId.get(next).substrate==='cloth'))candidates.push(next);else queue.push(next);}}if(candidates.length){candidates.sort((a,b)=>Number(['glass_pane','curtain_panel'].includes(byId.get(a).kind))-Number(['glass_pane','curtain_panel'].includes(byId.get(b).kind))||a.localeCompare(b));return candidates[0];}}throw Error('No contact-connected parent '+c.id);}
 const grouping=new Map(),assigned=new Map();
 for(let c of components){const p=parent(c),key=p+'|'+c.substrate;if(!grouping.has(key))grouping.set(key,{key,parent:p,root:byId.get(p),material:material[c.substrate],components:[],supports:[],thickness:c.nominal_material_thickness_m});const g=grouping.get(key);g.components.push(c);g.thickness=Math.min(g.thickness,c.nominal_material_thickness_m);assigned.set(c.id,g);assert(g.material);}
 function main(name){const c=components.find(c=>short(c)===name);assert(c,name);return assigned.get(c.id);}
 // Explicit fictional assembly dependencies; not a finite-element load solver.
 // Primary profiles depend on existing canonical opening owners. Actual source
 // adjacency supplies grouping; these game dependencies are not measured joint strengths.
 const rules=kind===0?{
  bottom_rail:['timber_sill'],head_rail:['left_jamb','right_jamb'],center_steel_divider:['bottom_rail','head_rail'],
  curtain_rod:['left_rod_socket','right_rod_socket'],left_curtain:['curtain_rod'],right_curtain:['curtain_rod'],
  room_glass_left:['left_jamb','center_steel_divider','bottom_rail','head_rail'],room_glass_right:['right_jamb','center_steel_divider','bottom_rail','head_rail']
 }:{
  left_base_rail:['door_glazing_post','middle_post'],left_middle_rail:['door_glazing_post','middle_post'],left_head_rail:['door_glazing_post','middle_post'],
  right_base_rail:['middle_post','right_post'],right_middle_rail:['middle_post','right_post'],right_head_rail:['middle_post','right_post'],
  lobby_glass_left_lower:['door_glazing_post','middle_post','left_base_rail','left_middle_rail'],lobby_glass_left_upper:['door_glazing_post','middle_post','left_middle_rail','left_head_rail'],
  lobby_glass_right_lower:['middle_post','right_post','right_base_rail','right_middle_rail'],lobby_glass_right_upper:['middle_post','right_post','right_middle_rail','right_head_rail']
 };
 for(const g of grouping.values()){
  const primaryGroup=assigned.get(g.parent);g.supports=g===primaryGroup?(rules[short(g.root)]||[]).map(main):[primaryGroup];
  if(g===primaryGroup)g.thickness=g.root.nominal_material_thickness_m;
  assert(!g.supports.includes(g) && g.supports.length<=5);
 }
 const ordered=[],visiting=new Set();function visit(g){if(ordered.includes(g))return;assert(!visiting.has(g),'Cyclic supports');visiting.add(g);g.supports.forEach(visit);visiting.delete(g);ordered.push(g);}grouping.forEach(visit);assert(ordered.length<=64,'Render mask exhausted');
 const triangles=[],triParts=[],ranges=[];
 for(let ni=0;ni<json.nodes.length;ni++){const node=json.nodes[ni];if(node.mesh===undefined)continue;assert(!node.matrix && !node.rotation && !node.translation && !node.scale,'Unexpected transform; update importer rather than drop it');const mesh=json.meshes[node.mesh];for(let pi=0;pi<mesh.primitives.length;pi++){const prim=mesh.primitives[pi],count=json.accessors[prim.indices].count/3,start=triangles.length;for(let t=0;t<count;t++){let c=components.find(c=>c.runtime_mapping.node_name===node.name && c.runtime_mapping.primitive_index===pi && t>=c.runtime_mapping.triangle_range_half_open[0]&&t<c.runtime_mapping.triangle_range_half_open[1]);assert(c);triangles.push([0,1,2].map(k=>read(prim.attributes.POSITION,read(prim.indices,t*3+k)[0])));triParts.push(ordered.indexOf(assigned.get(c.id)));}ranges.push({mesh:node.mesh,primitive:pi,start,count});}}
 const vertices=triangles.flat(),modelName='window_r1_'+kind;
 text+='static const b3Vec3 '+modelName+'_vertices[]={\n'+vertices.map(vec).join(',\n')+'\n};\n';
 text+='static const uint8_t '+modelName+'_triangle_parts[]={'+triParts.join(',')+'};\n';
 const rows=ordered.map((g,i)=>{const tris=triangles.filter((_,t)=>triParts[t]===i).flat(),lo=[0,1,2].map(k=>Math.min(...tris.map(v=>v[k]))),hi=[0,1,2].map(k=>Math.max(...tris.map(v=>v[k])));g.index=i;g.center=lo.map((v,k)=>(v+hi[k])/2);g.half=lo.map((v,k)=>(hi[k]-v)/2);return '{"'+short(g.root)+'",'+vec(g.center)+','+vec(g.half)+','+g.material+','+g.thickness+'f,{'+Array.from({length:5},(_,k)=>g.supports[k]?ordered.indexOf(g.supports[k]):-1).join(',')+'}}';});
 text+='static const SwatWindowPart '+modelName+'_parts[]={\n'+rows.join(',\n')+'\n};\n';
 models.push('{"'+file+'",'+modelName+'_vertices,'+modelName+'_triangle_parts,'+triangles.length+','+modelName+'_parts,'+ordered.length+'}');
 reports.push({asset,groups:ordered.length,triangles:triangles.length,groupsDetail:ordered.map(g=>({index:g.index,name:short(g.root),substrate:g.material,healthSection:g.thickness,components:g.components.map(c=>short(c)),supports:g.supports.map(s=>ordered.indexOf(s))})),ranges});
}
text+='static const SwatWindowModel window_r1_models[]={'+models.join(',')+'};\n';
fs.writeFileSync(path.join(out,'motel_windows_data.h'),text);fs.writeFileSync(path.join(input,'engine-groups.json'),JSON.stringify(reports,null,2));
const count=reports[1].groups+4*reports[0].groups;fs.writeFileSync(path.join(out,'motel_windows_count.h'),'// Generated by tools/import_motel_windows.cjs\n#define SWAT_WINDOW_R1_PIECES '+count+'\n');console.log(reports.map(x=>({asset:x.asset,groups:x.groups,triangles:x.triangles})),count);
