// Read original GLBs only. No Blender/authoring scripts are executed.
const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),dir=path.join(root,'assets/environment/motel_surroundings');
const covered=JSON.parse(fs.readFileSync(path.join(root,'art_handoffs/motel-surroundings/source/COVERED_FILES.json'))).files;
const current=Object.fromEntries(fs.readFileSync(path.join(root,'art_handoffs/motel-surroundings/source/RUNTIME_SHA256SUMS.txt'),'utf8').trim().split('\n').map(line=>{const [hash,name]=line.split(/\s+/);return[name,hash];}));
function glb(name){const bytes=fs.readFileSync(path.join(dir,name+'.glb'));const hash=crypto.createHash('sha256').update(bytes).digest('hex');assert.equal(hash,current['runtime/'+name+'.glb']);if(name.endsWith('_collision'))assert.equal(hash,covered.find(f=>f.path.endsWith('/'+name+'.glb')).sha256);assert.equal(bytes.readUInt32LE(0),0x46546c67);assert.equal(bytes.readUInt32LE(4),2);const end=20+bytes.readUInt32LE(12);return {json:JSON.parse(bytes.subarray(20,end)),bin:bytes.subarray(end+8),hash};}
function data(g,id){const a=g.json.accessors[id],v=g.json.bufferViews[a.bufferView],n={SCALAR:1,VEC2:2,VEC3:3,VEC4:4}[a.type],size={5123:2,5125:4,5126:4}[a.componentType];assert(n&&size&&!a.sparse);return Array.from({length:a.count},(_,i)=>Array.from({length:n},(_,j)=>{const at=(v.byteOffset||0)+(a.byteOffset||0)+i*(v.byteStride||n*size)+j*size;return a.componentType===5126?g.bin.readFloatLE(at):size===2?g.bin.readUInt16LE(at):g.bin.readUInt32LE(at)}));}
function geometry(g,mesh){const p=g.json.meshes[mesh].primitives;assert.equal(p.length,1);assert(p[0].mode===undefined||p[0].mode===4);return {vertices:data(g,p[0].attributes.POSITION),indices:data(g,p[0].indices).flat()};}
const shoulder=glb('shoulder_collision'),bank=glb('bank_collision'),render=glb('bank_render');
for(const g of [shoulder,bank,render])for(const node of g.json.nodes)assert(!node.matrix&&!node.translation&&!node.rotation&&!node.scale&&!node.children);
const parts=[...shoulder.json.nodes.map(n=>geometry(shoulder,n.mesh)),...bank.json.nodes.map(n=>geometry(bank,n.mesh))];assert.equal(parts.length,15);
function point(v){return v.map(x=>Math.round(x*1e6)).join(',');}
function triangle(g,t){return g.indices.slice(t*3,t*3+3).map(i=>point(g.vertices[i])).sort().join(';');}
const rockOwners=new Map();let closedTriangles=0;
for(let k=0;k<parts.length;k++){
 const g=parts[k];assert(g.indices.length/3<=240);closedTriangles+=g.indices.length/3;
 // Count oriented welded edges, independently of exported UV/normal splits.
 const edges=new Map();for(let t=0;t<g.indices.length;t+=3)for(let e=0;e<3;e++){const a=point(g.vertices[g.indices[t+e]]),b=point(g.vertices[g.indices[t+(e+1)%3]]),key=[a,b].sort().join('|');let q=edges.get(key)||{count:0,balance:0};q.count++;q.balance+=a<b?1:-1;edges.set(key,q);}
 for(const e of edges.values())assert(e.count===2&&e.balance===0,'non-closed or inconsistent mesh');
 g.min=[0,1,2].map(a=>Math.min(...g.vertices.map(v=>v[a])));g.max=[0,1,2].map(a=>Math.max(...g.vertices.map(v=>v[a])));g.center=g.min.map((v,i)=>(v+g.max[i])/2);g.half=g.min.map((v,i)=>(g.max[i]-v)/2);
 if(k>=2)for(let t=0;t<g.indices.length/3;t++){const key=triangle(g,t);assert(!rockOwners.has(key));rockOwners.set(key,k-1);}
}
const rocks=geometry(render,1),mapping=[];assert.equal(rocks.indices.length/3,1040);
for(let t=0;t<rocks.indices.length/3;t++){let part=rockOwners.get(triangle(rocks,t));assert(part,'render/collision rock mismatch');mapping.push(part);}
for(let k=1;k<=13;k++)assert.equal(mapping.filter(x=>x===k).length,80);
const f=x=>{if(Math.abs(x)<1e-12)x=0;let s=x.toPrecision(9);return (s.includes('.')||s.includes('e')?s:s+'.0')+'f';};
let out='// Generated by tools/import_motel_surroundings.cjs from original, hash-checked GLBs.\n';
for(let k=0;k<parts.length;k++){const p=parts[k];out+=`static b3Vec3 surroundings_vertices_${k}[]={\n`+p.vertices.map(v=>'{'+v.map((x,i)=>f(x-p.center[i])).join(',')+'}').join(',\n')+'};\n';out+=`static int32_t surroundings_indices_${k}[]={${p.indices.join(',')}};\n`;}
out+='static const SwatMotelAsset surroundings_parts[]={\n'+parts.map((p,k)=>`{NULL,{${p.center.map(f)}},{${p.half.map(f)}},surroundings_vertices_${k},${p.vertices.length},surroundings_indices_${k},${p.indices.length/3},NULL,0}`).join(',\n')+'};\n';
out+='static const unsigned char surroundings_rock_triangles[]={'+mapping.join(',')+'};\n';
const manifest=JSON.parse(fs.readFileSync(path.join(dir,'placement_manifest.json')));assert.equal(manifest.instances.length,10);
out+='static const SwatMotelInstance surroundings_placements[]={\n'+manifest.instances.map(p=>`{${p.module==='shoulder'?0:1},{${p.translation_yup.map(f)}},{1,1,1},${f(p.rotation_y_radians)},SWAT_SOIL,false,false}`).join(',\n')+'};\n';
fs.writeFileSync(path.join(root,'motel_surroundings_data.h'),out);
console.log(JSON.stringify({sourceHashes:{shoulder:shoulder.hash,bank:bank.hash,render:render.hash},parts:parts.length,closedTriangles,placements:5,physicalComponents:75,rockRenderTrianglesMatched:mapping.length},null,2));
