// Offline, deterministic collision import. Runtime/headless code loads no GLBs.
// cc -O2 tools/import_motel_utility.c -lm -o /tmp/import_motel_utility
// Run from ocean/swat; stdout is motel_utility_data.h.
#include "../vendor/cgltf_private.h"
#include <assert.h>
#include <stdbool.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

int main(int argc,char** argv) {
    bool fence=argc==2 && !strcmp(argv[1],"--fence");
    assert(argc==1 || fence);
    const char* files[]={fence?"chainlink_panel_2m.glb":"mu01_luggage_rack_lod0.glb",fence?"chainlink_terminal_post.glb":"mu01_wastebasket_small_lod0.glb"};
    const char* prefix=fence?"fence":"utility",*directory=fence?"motel_fence":"motel_utility_v1";
    float centers[2][3],halves[2][3];size_t counts[2][2],materials[2];
    puts("// Generated by tools/import_motel_utility.c from the original metre-scale GLBs.");
    for(int a=0;a<2;a++) {
        char path[512];snprintf(path,sizeof(path),"assets/environment/%s/%s",directory,files[a]);
        cgltf_options opt={0};cgltf_data* data=NULL;
        assert(cgltf_parse_file(&opt,path,&data)==cgltf_result_success);
        assert(cgltf_load_buffers(&opt,data,path)==cgltf_result_success);
        assert(cgltf_validate(data)==cgltf_result_success);
        float (*vertices)[3]=calloc(50000,sizeof(*vertices));unsigned* indices=calloc(150000,sizeof(*indices));
        assert(vertices && indices);size_t nv=0,ni=0;
        float lo[3]={INFINITY,INFINITY,INFINITY},hi[3]={-INFINITY,-INFINITY,-INFINITY};
        for(size_t n=0;n<data->nodes_count;n++) {
            cgltf_node* node=&data->nodes[n];if(!node->mesh)continue;assert(!node->skin);
            float m[16];cgltf_node_transform_world(node,m);
            for(size_t p=0;p<node->mesh->primitives_count;p++) {
                cgltf_primitive* prim=&node->mesh->primitives[p];assert(prim->type==cgltf_primitive_type_triangles);
                cgltf_accessor* pos=NULL;
                for(size_t j=0;j<prim->attributes_count;j++)if(prim->attributes[j].type==cgltf_attribute_type_position)pos=prim->attributes[j].data;
                assert(pos && prim->indices && nv+pos->count<50000 && ni+prim->indices->count<150000);
                for(size_t v=0;v<pos->count;v++) {
                    float x[3];assert(cgltf_accessor_read_float(pos,v,x,3));
                    for(int k=0;k<3;k++) {
                        float y=m[k]*x[0]+m[4+k]*x[1]+m[8+k]*x[2]+m[12+k];assert(isfinite(y));
                        vertices[nv+v][k]=y;lo[k]=fminf(lo[k],y);hi[k]=fmaxf(hi[k],y);
                    }
                }
                for(size_t t=0;t<prim->indices->count;t++){size_t i=cgltf_accessor_read_index(prim->indices,t);assert(i<pos->count);indices[ni++]=(unsigned)(nv+i);}
                nv+=pos->count;
            }
        }
        assert(nv && ni%3==0);
        for(int k=0;k<3;k++){centers[a][k]=(lo[k]+hi[k])*.5f;halves[a][k]=(hi[k]-lo[k])*.5f;}
        printf("static b3Vec3 %s_vertices_%d[]={\n",prefix,a);
        for(size_t v=0;v<nv;v++)printf("{%.9ef,%.9ef,%.9ef},\n",vertices[v][0]-centers[a][0],vertices[v][1]-centers[a][1],vertices[v][2]-centers[a][2]);
        printf("};\nstatic int32_t %s_indices_%d[]={\n",prefix,a);
        for(size_t i=0;i<ni;i+=3)printf("%u,%u,%u,\n",indices[i],indices[i+1],indices[i+2]);
        printf("};\nstatic const SwatMotelMaterial %s_materials_%d[]={",prefix,a);
        for(size_t i=0;i<data->materials_count;i++)printf("{%.9ef,%.9ef},",data->materials[i].pbr_metallic_roughness.roughness_factor,data->materials[i].pbr_metallic_roughness.metallic_factor);
        puts("};");counts[a][0]=nv;counts[a][1]=ni/3;materials[a]=data->materials_count;
        free(vertices);free(indices);cgltf_free(data);
    }
    printf("static const SwatMotelAsset %s_assets[]={\n",prefix);
    for(int a=0;a<2;a++)printf("{\"%s\",{%.9ef,%.9ef,%.9ef},{%.9ef,%.9ef,%.9ef},%s_vertices_%d,%zu,%s_indices_%d,%zu,%s_materials_%d,%zu},\n",files[a],centers[a][0],centers[a][1],centers[a][2],halves[a][0],halves[a][1],halves[a][2],prefix,a,counts[a][0],prefix,a,counts[a][1],prefix,a,materials[a]);
    puts("};");return 0;
}
