#!/usr/bin/env python3
"""Import the CC0 batch-15 modular motel; generate deterministic mesh collision.
Usage: python tools/import_motel.py /path/to/motor_court_motel_batch15_CC0
Requires NumPy. No Blender scripts are executed. Source GLBs remain unchanged.
"""
from pathlib import Path
import hashlib,json,struct,sys,shutil
import numpy as np
ROOT=Path(__file__).resolve().parents[1]
def read_glb(path):
    raw=path.read_bytes(); assert raw[:4]==b'glTF' and struct.unpack_from('<I',raw,8)[0]==len(raw)
    size=struct.unpack_from('<I',raw,12)[0]; doc=json.loads(raw[20:20+size]); blob=raw[28+size:]
    def accessor(i):
        a=doc['accessors'][i]; v=doc['bufferViews'][a['bufferView']]; dtype={5126:'<f4',5125:'<u4',5123:'<u2',5121:'u1'}[a['componentType']]
        width={'SCALAR':1,'VEC3':3,'VEC2':2,'VEC4':4}[a['type']]; step=v.get('byteStride',np.dtype(dtype).itemsize*width)
        return np.ndarray((a['count'],width),dtype,blob,v.get('byteOffset',0)+a.get('byteOffset',0),(step,np.dtype(dtype).itemsize)).copy()
    vertices=[]; indices=[]; offset=0
    def walk(i,parent):
        nonlocal offset
        n=doc['nodes'][i]
        if 'matrix' in n: m=np.array(n['matrix']).reshape(4,4).T
        else:
            x,y,z,w=n.get('rotation',[0,0,0,1]); m=np.eye(4)
            m[:3,:3]=[[1-2*(y*y+z*z),2*(x*y-z*w),2*(x*z+y*w)],[2*(x*y+z*w),1-2*(x*x+z*z),2*(y*z-x*w)],[2*(x*z-y*w),2*(y*z+x*w),1-2*(x*x+y*y)]]
            m[:3,:3] @= np.diag(n.get('scale',[1,1,1])); m[:3,3]=n.get('translation',[0,0,0])
        m=parent@m
        if 'mesh' in n:
            for prim in doc['meshes'][n['mesh']]['primitives']:
                assert prim.get('mode',4)==4
                a=accessor(prim['attributes']['POSITION']); v=(np.c_[a,np.ones(len(a))]@m.T)[:,:3]
                idx=accessor(prim['indices']).reshape(-1) if 'indices' in prim else np.arange(len(a))
                if np.linalg.det(m[:3,:3])<0: idx=idx.reshape(-1,3)[:,[0,2,1]].reshape(-1)
                vertices.append(v); indices.append(idx+offset); offset+=len(v)
        for child in n.get('children',[]):walk(child,m)
    for i in doc['scenes'][doc.get('scene',0)]['nodes']:walk(i,np.eye(4))
    return np.concatenate(vertices),np.concatenate(indices),doc

def number(x):
    value=f'{float(x):.8g}'; return value+('f' if '.' in value or 'e' in value else '.0f')
def vec(v):return '{'+','.join(map(number,v))+'}'
def main(source):
    manifest=json.loads((source/'manifest.json').read_text()); assert manifest['license']=='CC0-1.0' and manifest['asset_count']==24
    instances=json.loads((source/'assembly_manifest.json').read_text())['instances']; assert len(instances)==146
    assets=manifest['assets']+manifest['reused_existing_assets']; dest=ROOT/'assets/environment/motel_v1';dest.mkdir(exist_ok=True)
    header=['// Generated by tools/import_motel.py from original CC0 batch 15.','// Static local triangles retain actual openings and furniture clearances.']
    specs=[]; material_values=[]
    for i,a in enumerate(assets):
        path=source/a['file']; assert hashlib.sha256(path.read_bytes()).hexdigest()==a['sha256']; name=path.name; shutil.copyfile(path,dest/name)
        v,t,d=read_glb(path); lo=v.min(0);hi=v.max(0);center=(lo+hi)/2
        # Do not collapse a facade, ramp or furniture mesh into its bounding box.
        header+=['static b3Vec3 motel_vertices_%d[]={'%i,','.join(vec(x-center) for x in v),'};','static int32_t motel_indices_%d[]={'%i,','.join(str(int(x)) for x in t),'};']
        materials=d.get('materials',[]); factors=[]
        for m in materials:
            p=m.get('pbrMetallicRoughness',{}); factors.append((p.get('roughnessFactor',1),p.get('metallicFactor',1)))
        material_values+=['static const SwatMotelMaterial motel_materials_%d[]={'%i,','.join('{'+number(r)+','+number(m)+'}' for r,m in factors),'};']
        specs.append('{"%s",%s,%s,motel_vertices_%d,%d,motel_indices_%d,%d,motel_materials_%d,%d}'%(name,vec(center),vec((hi-lo)/2),i,len(v),i,len(t)//3,i,len(factors)))
    header+=material_values+['static const SwatMotelAsset motel_assets[]={',',\n'.join(specs),'};']
    ids={a['id']:i for i,a in enumerate(assets)}; placement=[]
    for a in instances:
        x,y,z=a['position_source_m'];sx,sy,sz=a['scale']; door=a['asset_id']=='mc15_room_door_leaf'; yaw=0 if door else a['yaw_source_deg']*np.pi/180
        name=a['asset_id']; material='SWAT_PLASTER' if any(n in name for n in ['wall','facade','partition','pier']) else 'SWAT_WOOD'
        if any(n in name for n in ['floor','walkway','ramp','wheel_stop']):material='SWAT_CONCRETE'
        if any(n in name for n in ['machine','washer','dryer','railing','canopy_post','through_wall_ac','sign']):material='SWAT_STEEL'
        roof=a['collection']=='02b_ROOFS_toggle_cutaway'
        placement.append('{%d,%s,%s,%s,%s,%s,%s}'%(ids[name],vec([x,z,-y]),vec([sx,sz,sy]),number(yaw),material,'true' if door else 'false','true' if roof else 'false'))
    header+=['static const SwatMotelInstance motel_instances[]={',',\n'.join(placement),'};']
    (ROOT/'motel_data.h').write_text('\n'.join(header)+'\n')
    for name in ['LICENSE.txt','README.md','manifest.json','assembly_manifest.json'] :shutil.copyfile(source/name,dest/name)
    report={'source_archive_sha256':'92896091ee009a131cf76e73e0e3c6f94e543bb9e50debda797f89568c213fb3','assets':len(assets),'instances':len(instances),'collision':'Original static GLB triangle surfaces, independent instance identities. Door leaves use functional canonical hinged boxes.','units':'Metres; source (x,y,z) -> engine (x,z,-y) exactly once.'}
    (dest/'engine_import.json').write_text(json.dumps(report,indent=2)+'\n');print(report)
if __name__=='__main__':main(Path(sys.argv[1]))
