// Offline source flattening; verify the receipt SHA before running from ocean/swat.
#include "../vendor/cgltf_private.h"
#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
int main(void){
 const char* file="painted_wooden_nightstand_floor_centered_2k.glb";
 char path[256];snprintf(path,sizeof(path),"assets/environment/motel_props/%s",file);
 cgltf_options options={0};cgltf_data* data=NULL;
 assert(cgltf_parse_file(&options,path,&data)==cgltf_result_success);
 assert(cgltf_load_buffers(&options,data,path)==cgltf_result_success && cgltf_validate(data)==cgltf_result_success);
 float vertices[503][3],lo[]={INFINITY,INFINITY,INFINITY},hi[]={-INFINITY,-INFINITY,-INFINITY};int indices[1410],nv=0,nt=0;
 for(size_t n=0;n<data->nodes_count;n++){
  cgltf_node* node=&data->nodes[n];if(!node->mesh)continue;float matrix[16];cgltf_node_transform_world(node,matrix);
  for(size_t p=0;p<node->mesh->primitives_count;p++){
   cgltf_primitive* prim=&node->mesh->primitives[p];assert(prim->indices && prim->type==cgltf_primitive_type_triangles);
   cgltf_accessor* positions=NULL;for(size_t a=0;a<prim->attributes_count;a++)if(prim->attributes[a].type==cgltf_attribute_type_position)positions=prim->attributes[a].data;
   assert(positions && nv+(int)positions->count<=503 && nt+(int)prim->indices->count<=1410);int base=nv;
   for(size_t v=0;v<positions->count;v++,nv++){
    float local[3];assert(cgltf_accessor_read_float(positions,v,local,3));
    for(int k=0;k<3;k++){float value=matrix[k]*local[0]+matrix[4+k]*local[1]+matrix[8+k]*local[2]+matrix[12+k];assert(isfinite(value));vertices[nv][k]=value;lo[k]=fminf(lo[k],value);hi[k]=fmaxf(hi[k],value);}
   }
   for(size_t i=0;i<prim->indices->count;i++){size_t ix=cgltf_accessor_read_index(prim->indices,i);assert(ix<positions->count);indices[nt++]=base+ix;}
  }
 }
 assert(nv==503 && nt==1410 && fabsf(lo[1])<1e-6f);
 assert(fabsf(hi[0]-lo[0]-.504564583f)<1e-6f && fabsf(hi[1]-lo[1]-.615520971f)<1e-6f && fabsf(hi[2]-lo[2]-.508716002f)<1e-6f);
 float center[3],half[3],feet[4][3]={{0}};int counts[4]={0};
 for(int k=0;k<3;k++){center[k]=(hi[k]+lo[k])*.5f;half[k]=(hi[k]-lo[k])*.5f;}
 for(int v=0;v<nv;v++)if(vertices[v][1]<lo[1]+1e-5f){int at=(vertices[v][0]>0)+2*(vertices[v][2]>0);counts[at]++;for(int k=0;k<3;k++)feet[at][k]+=vertices[v][k];}
 puts("// Generated by tools/import_motel_nightstand.c; full scene-node transforms, metres.");
 puts("static b3Vec3 nightstand_vertices[]={");
 for(int v=0;v<nv;v++)printf("{%.9ef,%.9ef,%.9ef},\n",vertices[v][0]-center[0],vertices[v][1]-center[1],vertices[v][2]-center[2]);
 puts("};\nstatic int32_t nightstand_indices[]={");for(int i=0;i<nt;i++)printf("%d,",indices[i]);
 puts("};\nstatic const SwatMotelMaterial nightstand_materials[]={{1,0}};");
 printf("static const SwatMotelAsset nightstand_asset={\"%s\",{%.9ef,%.9ef,%.9ef},{%.9ef,%.9ef,%.9ef},nightstand_vertices,%d,nightstand_indices,470,nightstand_materials,1};\n",file,center[0],center[1],center[2],half[0],half[1],half[2],nv);
 puts("static const b3Vec3 nightstand_feet[]={");
 for(int i=0;i<4;i++){assert(counts[i]>=3);for(int k=0;k<3;k++)feet[i][k]/=counts[i];printf("{%.9ef,%.9ef,%.9ef},\n",feet[i][0],feet[i][1],feet[i][2]);fprintf(stderr,"Measured foot%d: %.9f %.9f %.9f (%d bottom vertices)\n",i,feet[i][0],feet[i][1],feet[i][2],counts[i]);}
 puts("};");cgltf_free(data);return 0;
}
