#!/usr/bin/env python3
"""Import original CC0 batch 16, retaining source triangles and metric materials.
The eight site meshes are extracted from the example without changing geometry.
Usage: python tools/import_storefront.py /path/neighborhood_storefronts_batch16_CC0
"""
from pathlib import Path
import copy, hashlib, json, shutil, struct, sys
import numpy as np
from import_motel import ROOT, read_glb, number, vec

def site_glb(raw, doc, indices):
    size = struct.unpack_from('<I', raw, 12)[0]
    source_binary=raw[28+size:]; binary=bytearray()
    result={'asset':copy.deepcopy(doc['asset']),'scene':0,'scenes':[{'nodes':list(range(len(indices)))}],
            'nodes':[],'meshes':[],'materials':[],'textures':[],'images':[],'samplers':[],
            'accessors':[],'bufferViews':[]}
    maps={k:{} for k in ['bufferViews','accessors','images','samplers','textures','materials']}
    def use(kind,i):
        if i in maps[kind]: return maps[kind][i]
        value=copy.deepcopy(doc[kind][i]); index=len(result[kind]); maps[kind][i]=index
        if kind=='bufferViews':
            assert value.get('buffer',0)==0
            binary.extend(b'\0'*(-len(binary)%4));offset=value.get('byteOffset',0)
            binary.extend(source_binary[offset:offset+value['byteLength']]);value['buffer']=0;value['byteOffset']=len(binary)-value['byteLength']
        elif kind=='accessors':
            assert 'sparse' not in value
            value['bufferView']=use('bufferViews',value['bufferView'])
        elif kind=='images':
            assert 'bufferView' in value
            value['bufferView']=use('bufferViews',value['bufferView'])
        elif kind=='textures':
            value['source']=use('images',value['source'])
            if 'sampler' in value:value['sampler']=use('samplers',value['sampler'])
        elif kind=='materials':
            def remap(v):
                if isinstance(v,dict):
                    for key,item in v.items():
                        if key.endswith('Texture') and isinstance(item,dict) and 'index' in item:item['index']=use('textures',item['index'])
                        else: remap(item)
            remap(value)
        result[kind].append(value);return index
    for i in indices:
        node=copy.deepcopy(doc['nodes'][i]);assert not node.get('children') and 'skin' not in node
        mesh=copy.deepcopy(doc['meshes'][node['mesh']]);node['mesh']=len(result['meshes'])
        for p in mesh['primitives']:
            p['attributes']={key:use('accessors',v) for key,v in p['attributes'].items()}
            if 'indices' in p:p['indices']=use('accessors',p['indices'])
            if 'material' in p:p['material']=use('materials',p['material'])
        result['nodes'].append(node);result['meshes'].append(mesh)
    result['buffers']=[{'byteLength':len(binary)}]
    binary.extend(b'\0'*(-len(binary)%4))
    data = json.dumps(result, separators=(',', ':')).encode()
    data += b' ' * (-len(data) % 4)
    return struct.pack('<III', 0x46546c67, 2, 28+len(data)+len(binary))+struct.pack('<II', len(data), 0x4e4f534a)+data+struct.pack('<II', len(binary), 0x004e4942)+binary

def main(source):
    manifest=json.loads((source/'manifest.json').read_text())
    assert manifest['license'].startswith('CC0-1.0') and manifest['asset_count']==24
    assembly=json.loads((source/'assembly_manifest.json').read_text())
    assets=manifest['assets']+manifest['reused_existing_assets']
    assert len(assets)==39 and len(assembly['instances'])==151
    dest=ROOT/'assets/environment/storefront_v1'; dest.mkdir(parents=True,exist_ok=True)
    specs=[]; header=['// Generated by tools/import_storefront.py: original CC0 batch 16.']
    for i,a in enumerate(assets):
        path=source/a['file']; assert hashlib.sha256(path.read_bytes()).hexdigest()==a['sha256']
        shutil.copyfile(path,dest/path.name)
    # The authored sidewalk, apron and street belong to the example rather
    # than the modular manifest. One static asset retains all eight site nodes.
    raw=(source/'storefronts_example.glb').read_bytes(); size=struct.unpack_from('<I',raw,12)[0]; doc=json.loads(raw[20:20+size])
    site=[i for i,n in enumerate(doc['nodes']) if n.get('name','').startswith('SITE_')]; assert len(site)==8
    (dest/'site.glb').write_bytes(site_glb(raw,doc,site))
    assets=assets+[{'id':'site','file':'site.glb'}]
    for i,a in enumerate(assets):
        path=dest/Path(a['file']).name; vertices,indices,d=read_glb(path)
        lo=vertices.min(0); hi=vertices.max(0); center=(lo+hi)/2
        header+=['static b3Vec3 storefront_vertices_%d[]={'%i,','.join(vec(x-center) for x in vertices),'};',
                 'static int32_t storefront_indices_%d[]={'%i,','.join(str(int(x)) for x in indices),'};']
        factors=[]
        for m in d.get('materials',[]):
            p=m.get('pbrMetallicRoughness',{}); factors.append('{'+number(p.get('roughnessFactor',1))+','+number(p.get('metallicFactor',1))+'}')
        header+=['static const SwatMotelMaterial storefront_materials_%d[]={'%i,','.join(factors),'};']
        specs.append('{"%s",%s,%s,storefront_vertices_%d,%d,storefront_indices_%d,%d,storefront_materials_%d,%d}'%(path.name,vec(center),vec((hi-lo)/2),i,len(vertices),i,len(indices)//3,i,len(factors)))
    header+=['static const SwatMotelAsset storefront_assets[]={',',\n'.join(specs),'};']
    ids={a['id']:i for i,a in enumerate(assets)}; placements=[]
    for p in assembly['instances']+[{'asset_id':'site','position_source_m':[0,0,0],'scale':[1,1,1],'yaw_source_deg':0,'collection':'site'}]:
        name=p['asset_id']; x,y,z=p['position_source_m']; sx,sy,sz=p['scale']
        door=name in ['ns16_storefront_glass_door','ns16_stockroom_door_leaf','ns16_rear_service_door']
        # The example is open. Close leaves around their original floor hinge;
        # rear exit opens inward from its opposed 180-degree closed orientation.
        yaw=(180 if name=='ns16_rear_service_door' else 0) if door else p['yaw_source_deg']
        material='SWAT_PLASTER' if any(n in name for n in ['wall','pier','partition','frame','fascia']) else 'SWAT_WOOD'
        if any(n in name for n in ['slab','site']): material='SWAT_CONCRETE'
        if any(n in name for n in ['washer','dryer','machine','shutter','steel','rear_service_door','glass_door']): material='SWAT_STEEL'
        roof=p['collection']=='02b_ROOFS_toggle_cutaway'
        placements.append('{%d,%s,%s,%s,%s,%s,%s}'%(ids[name],vec([x,z,-y]),vec([sx,sz,sy]),number(yaw*np.pi/180),material,str(door).lower(),str(roof).lower()))
    header+=['static const SwatMotelInstance storefront_instances[]={',',\n'.join(placements),'};']
    (ROOT/'storefront_data.h').write_text('\n'.join(header)+'\n')
    for name in ['LICENSE.txt','README.md','manifest.json','assembly_manifest.json']: shutil.copyfile(source/name,dest/name)
    report={'assets':len(assets),'instances':len(placements),'source_archive_sha256':'deb1caf7a7b8785d39e1faad64ea342c69d72aa304cd71669105431df4392b1f',
            'collision':'Original static triangles; five functional hinged leaves; site retains all original eight meshes.',
            'site_source_sha256':hashlib.sha256(raw).hexdigest(),'site_glb_sha256':hashlib.sha256((dest/'site.glb').read_bytes()).hexdigest()}
    (dest/'engine_import.json').write_text(json.dumps(report,indent=2)+'\n');print(report)
if __name__=='__main__': main(Path(sys.argv[1]))
