// Import the delivered metre-scale shell without running authoring scripts.
const fs=require('fs'),path=require('path'),assert=require('assert'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),file=path.join(root,'assets/environment/motel_mounted/motel_surface_junction.glb');
const bytes=fs.readFileSync(file),manifest=JSON.parse(fs.readFileSync(path.join(root,'art_handoffs/motel-mounted/manifest.json')));
assert.equal(crypto.createHash('sha256').update(bytes).digest('hex'),manifest.runtime_measured.sha256);
assert.equal(bytes.readUInt32LE(0),0x46546c67);assert.equal(bytes.readUInt32LE(4),2);assert.equal(bytes.readUInt32LE(8),bytes.length);
const end=20+bytes.readUInt32LE(12),g=JSON.parse(bytes.subarray(20,end)),bin=bytes.subarray(end+8);
function data(id){const a=g.accessors[id],v=g.bufferViews[a.bufferView],n={SCALAR:1,VEC3:3}[a.type],size={5123:2,5125:4,5126:4}[a.componentType];assert(n&&size&&!a.sparse);return Array.from({length:a.count},(_,i)=>Array.from({length:n},(_,j)=>{const at=(v.byteOffset||0)+(a.byteOffset||0)+i*(v.byteStride||n*size)+j*size;return a.componentType===5126?bin.readFloatLE(at):size===2?bin.readUInt16LE(at):bin.readUInt32LE(at);}));}
const vertices=[],indices=[];
for(const node of g.nodes){assert(!node.matrix&&!node.translation&&!node.rotation&&!node.scale&&!node.skin);if(node.mesh===undefined)continue;for(const p of g.meshes[node.mesh].primitives){assert(p.mode===undefined||p.mode===4);const v=data(p.attributes.POSITION),idx=data(p.indices).flat();assert(idx.every(x=>x>=0&&x<v.length));indices.push(...idx.map(i=>i+vertices.length));vertices.push(...v);}}
assert.equal(indices.length/3,1464);assert(vertices.flat().every(Number.isFinite));
const min=[0,1,2].map(a=>Math.min(...vertices.map(v=>v[a]))),max=[0,1,2].map(a=>Math.max(...vertices.map(v=>v[a]))),center=min.map((v,a)=>(v+max[a])/2),half=min.map((v,a)=>(max[a]-v)/2);
for(let a=0;a<3;a++){assert(Math.abs(min[a]-manifest.runtime_measured.gltf_bounds_min_m[a])<1e-7);assert(Math.abs(max[a]-manifest.runtime_measured.gltf_bounds_max_m[a])<1e-7);}
const f=x=>{let s=(Math.abs(x)<1e-12?0:x).toPrecision(9);return(s.includes('.')||s.includes('e')?s:s+'.0')+'f';};
let out='// Generated by tools/import_motel_mounted.cjs from hash-checked original GLB.\n';
out+='static b3Vec3 mounted_vertices_0[]={\n'+vertices.map(v=>'{'+v.map((x,a)=>f(x-center[a])).join(',')+'}').join(',\n')+'};\n';
out+='static int32_t mounted_indices_0[]={'+indices.join(',')+'};\n';
out+='static const SwatMotelMaterial mounted_materials_0[]={'+g.materials.map(m=>'{'+f(m.pbrMetallicRoughness.roughnessFactor??1)+','+f(m.pbrMetallicRoughness.metallicFactor??1)+'}').join(',')+'};\n';
out+=`static const SwatMotelAsset mounted_assets[]={{"motel_surface_junction.glb",{${center.map(f)}},{${half.map(f)}},mounted_vertices_0,${vertices.length},mounted_indices_0,1464,mounted_materials_0,${g.materials.length}}};\n`;
const target=path.join(root,'motel_mounted_data.h');if(!fs.existsSync(target)||fs.readFileSync(target,'utf8')!==out)fs.writeFileSync(target,out);
console.log('PASS junction import: original hash, identity metre-scale nodes, 1464 exact shell triangles and measured bounds');
