// Offline source import; run from ocean/swat. No runtime asset parsing.
// cc -O2 tools/import_motel_panes.c -lm -o /tmp/import_motel_panes
#include "../vendor/cgltf_private.h"
#include <assert.h>
#include <math.h>
#include <stdio.h>
#include <string.h>
int main(void) {
    const char* files[]={"room_window_insert.glb","lobby_glazed_facade.glb"};
    puts("// Generated by tools/import_motel_panes.c; original opaque panes, metre units.");
    puts("static const SwatMotelPaneSource pane_sources[]={");
    for(int asset=0;asset<2;asset++) {
        char path[256];snprintf(path,sizeof(path),"assets/environment/motel_v1/%s",files[asset]);
        cgltf_options options={0};cgltf_data* data=NULL;
        assert(cgltf_parse_file(&options,path,&data)==cgltf_result_success);
        assert(cgltf_load_buffers(&options,data,path)==cgltf_result_success);
        assert(cgltf_validate(data)==cgltf_result_success);
        int ids[2][44],count[2]={0},triangle=0;
        float lo[2][3],hi[2][3];
        for(int side=0;side<2;side++)for(int k=0;k<3;k++){lo[side][k]=INFINITY;hi[side][k]=-INFINITY;}
        for(size_t n=0;n<data->nodes_count;n++) {
            cgltf_node* node=&data->nodes[n];if(!node->mesh)continue;
            float matrix[16];cgltf_node_transform_world(node,matrix);
            for(size_t p=0;p<node->mesh->primitives_count;p++) {
                cgltf_primitive* prim=&node->mesh->primitives[p];assert(prim->indices && prim->type==cgltf_primitive_type_triangles);
                cgltf_accessor* positions=NULL;
                for(size_t j=0;j<prim->attributes_count;j++)if(prim->attributes[j].type==cgltf_attribute_type_position)positions=prim->attributes[j].data;
                assert(positions);
                for(size_t t=0;t<prim->indices->count;t+=3,triangle++) {
                    if(!prim->material || strcmp(prim->material->name,"MC15_glass"))continue;
                    float v[3][3],cx=0;
                    for(int j=0;j<3;j++) {
                        float local[3];assert(cgltf_accessor_read_float(positions,cgltf_accessor_read_index(prim->indices,t+j),local,3));
                        for(int k=0;k<3;k++)v[j][k]=matrix[k]*local[0]+matrix[4+k]*local[1]+matrix[8+k]*local[2]+matrix[12+k];
                        cx+=v[j][0]/3;
                    }
                    // The source panes are disconnected and separated by their central frame.
                    int side=cx>(asset?.65f:0);assert(count[side]<44);ids[side][count[side]++]=triangle;
                    for(int j=0;j<3;j++)for(int k=0;k<3;k++){lo[side][k]=fminf(lo[side][k],v[j][k]);hi[side][k]=fmaxf(hi[side][k],v[j][k]);}
                }
            }
        }
        assert(triangle==(asset?1004:792));
        for(int side=0;side<2;side++) {
            assert(count[side]==44);
            printf("{%d,{%.9ef,%.9ef,%.9ef},{%.9ef,%.9ef,%.9ef},{",asset?12:10,
                (lo[side][0]+hi[side][0])*.5f,(lo[side][1]+hi[side][1])*.5f,(lo[side][2]+hi[side][2])*.5f,
                (hi[side][0]-lo[side][0])*.5f,(hi[side][1]-lo[side][1])*.5f,(hi[side][2]-lo[side][2])*.5f);
            for(int t=0;t<44;t++)printf("%d,",ids[side][t]);
            puts("}},");
        }
        cgltf_free(data);
    }
    puts("};");return 0;
}
