// Preserve complete connected components when partitioning dense contact meshes.
// Rendering and ballistic thickness keep their original full-mesh source.
const fs=require('fs'),path=require('path'),assert=require('assert');
const root=path.resolve(__dirname,'..');let text;
function array(type,name){
 const match=text.match(new RegExp('static '+type+' '+name+'\\[\\]=\\{([\\s\\S]*?)\\};'));assert(match,name);
 return JSON.parse('['+match[1].replace(/([\d.])f\b/g,'$1').replace(/\{/g,'[').replace(/\}/g,']').replace(/,\s*$/,'')+']');
}
const entries=[],report={limit:240,partitioned:[],remaining:[]};let output='// Generated by tools/partition_motel_contacts.cjs. Whole connected components only.\n';
for(let asset=0;asset<42;asset++){
 const utility=asset>=40,prefix=utility?'utility':'motel',index=utility?asset-40:asset;
 text=fs.readFileSync(path.join(root,utility?'motel_utility_data.h':'motel_data.h'),'utf8');
 const vertices=array('b3Vec3',prefix+'_vertices_'+index),indices=array('int32_t',prefix+'_indices_'+index),count=indices.length/3;
 if(count<=240)continue;
 const parents=Array.from({length:count},(_,i)=>i),owners=new Map();
 function rootOf(i){while(parents[i]!==i){parents[i]=parents[parents[i]];i=parents[i];}return i;}
 for(let t=0;t<count;t++)for(const v of indices.slice(t*3,t*3+3)){
  const key=vertices[v].map(x=>Math.round(x*1e6)).join(',');
  if(owners.has(key))parents[rootOf(t)]=rootOf(owners.get(key));else owners.set(key,t);
 }
 const groups=new Map();for(let t=0;t<count;t++){const r=rootOf(t);if(!groups.has(r))groups.set(r,[]);groups.get(r).push(t);}
 const components=[...groups.values()];
 if(components.some(c=>c.length>240)){report.remaining.push({asset,triangles:count,largestComponent:Math.max(...components.map(c=>c.length))});continue;}
 // Keep nearby parts in the same bounded mesh for tighter broadphase boxes.
 function center(c){const sum=[0,0,0];for(const t of c)for(const v of indices.slice(t*3,t*3+3))for(let a=0;a<3;a++)sum[a]+=vertices[v][a];return sum.map(x=>x/(c.length*3));}
 const axes=[0,1,2].map(a=>Math.max(...vertices.map(v=>v[a]))-Math.min(...vertices.map(v=>v[a]))),axis=axes.indexOf(Math.max(...axes));
 components.sort((a,b)=>center(a)[axis]-center(b)[axis]||a[0]-b[0]);
 const batches=[];for(const component of components){if(!batches.length||batches.at(-1).length+component.length>240)batches.push([]);batches.at(-1).push(...component);}
 const first=entries.length;for(const batch of batches){const name='motel_contact_indices_'+entries.length,part=batch.flatMap(t=>indices.slice(t*3,t*3+3));output+=`static const int32_t ${name}[]={${part.join(',')}};\n`;entries.push(`{${asset},${name},${batch.length}}`);}
 assert.equal(batches.flat().length,count);assert.equal(new Set(batches.flat()).size,count);
 report.partitioned.push({asset,triangles:count,components:components.length,first,parts:batches.length});
}
output+='static const SwatMotelContactSource motel_contact_sources[]={\n'+entries.join(',\n')+'\n};\n';
fs.writeFileSync(path.join(root,'motel_contacts_data.h'),output);
console.log(JSON.stringify(report,null,2));
