import bpy,json,hashlib
import numpy as np
from pathlib import Path
O=Path(__file__).resolve().parent;C=O.parent/'candidate_c/support_grip_surface_c.editable.blend';C1=O/'support_grip_index_release_c1.editable.blend';P='mixamorig:LeftHandIndex1';path='pose.bones["'+P+'"].rotation_quaternion';auth=json.loads((O/'CANDIDATE_C1_AUTHORING.json').read_text())
def curves(a):return {(f.data_path,f.array_index):{'extrapolation':f.extrapolation,'keys':[(list(k.co),k.interpolation,k.easing,list(k.handle_left),list(k.handle_right),k.handle_left_type,k.handle_right_type)for k in f.keyframe_points]}for f in a.fcurves}
def pos(o):
 e=o.evaluated_get(bpy.context.evaluated_depsgraph_get());m=e.to_mesh();x=np.array([e.matrix_world@v.co for v in m.vertices]);e.to_mesh_clear();return x
bpy.ops.wm.open_mainfile(filepath=str(C));bpy.context.scene.frame_set(0);bpy.context.view_layer.update();r=bpy.data.objects['SWAT_Mixamo_Rig'];source=curves(r.animation_data.action);source_action=r.animation_data.action.name;B={b.name:np.array(b.matrix_basis)for b in r.pose.bones};M={b.name:np.array(b.matrix)for b in r.pose.bones};gun=pos(bpy.data.objects['Rifle 7']);beforeq=list(r.pose.bones[P].rotation_quaternion)
bpy.ops.wm.open_mainfile(filepath=str(C1));bpy.context.scene.frame_set(0);bpy.context.view_layer.update();r=bpy.data.objects['SWAT_Mixamo_Rig'];target=curves(r.animation_data.action);preserved=curves(bpy.data.actions[source_action]);different=[k for k in source if source[k]!=target[k]];assert set(different)=={(path,j)for j in range(4)};assert preserved==source;localmax=max(float(np.abs(np.array(b.matrix_basis)-B[b.name]).max())for b in r.pose.bones if b.name!=P);fixedmax=max(float(np.abs(np.array(b.matrix)-M[b.name]).max())for b in r.pose.bones if not b.name.startswith('mixamorig:LeftHandIndex'));riflemax=float(np.linalg.norm(pos(bpy.data.objects['Rifle 7'])-gun,axis=1).max()*1000);assert localmax==fixedmax==riflemax==0.;out={'C_source_sha256':hashlib.sha256(C.read_bytes()).hexdigest(),'C1_sha256':hashlib.sha256(C1.read_bytes()).hexdigest(),'C_action_retained_exact':True,'C1_action':r.animation_data.action.name,'frame':0,'rig_bones':len(r.data.bones),'only_changed_curves':[{'data_path':p,'index':j}for p,j in different],'untouched_fcurve_count':len(source)-4,'all_716_untouched_curves_exact':True,'other_bone_local_matrix_max_abs_error':localmax,'hand_arm_gear_rifle_right_and_other_fingers_world_matrix_max_abs_error':fixedmax,'rifle_evaluated_vertex_max_delta_mm':riflemax,'native_bone':P,'C_rotation_quaternion_wxyz':beforeq,'C1_rotation_quaternion_wxyz':list(r.pose.bones[P].rotation_quaternion),'right_multiplicative_delta_quaternion_wxyz':auth['local_delta_quaternion_wxyz'],'native_local_added_x_flexion_deg':{'C':4.451142948549993,'C1':auth['chosen']['index1_added_native_local_x_deg']},'native_local_added_z_spread_deg_unchanged':auth['chosen']['index1_added_native_local_z_spread_deg'],'children':'Index2, Index3 and Index4 keep exact C local curves; their world poses follow Index1','hand_and_coordinate_frames':'Hand matrix is unchanged from corrected candidate_c/EXACT_LEFT_GRIP_HANDOFF.json; native mesh and stock-origin physical frames remain distinct'};(O/'EXACT_INDEX_RELEASE_HANDOFF.json').write_text(json.dumps(out,indent=2)+'\n');print(json.dumps(out,indent=2))
